# Generated by Django 5.2.11 on 2026-02-18 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_add_indexes_retailer_fields_product_is_active'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_is_acti_cat_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_is_acti_fac_idx',
        ),
        migrations.AlterField(
            model_name='product',
            name='gw_sku',
            field=models.CharField(blank=True, db_index=True, help_text='Games Workshop SKU / product code', max_length=50),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', 'category'], name='products_pr_is_acti_1cd666_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', 'faction'], name='products_pr_is_acti_857aa9_idx'),
        ),
    ]
