# Generated by Django 6.0.2 on 2026-03-04 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_products_pr_is_acti_cat_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ebay_search_name',
            field=models.CharField(blank=True, default='', help_text='Override name used when building eBay search queries. Leave blank to use the product name. Use this when eBay sellers list a product under a different name than its display name — e.g. Deathwatch units sold as Space Marine kits.', max_length=200),
        ),
    ]
