# Generated by Django 6.0.2 on 2026-03-05 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_add_ebay_search_name_to_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ebay_allow_no_box',
            field=models.BooleanField(default=False, help_text='When True, eBay listings with "no box" in the title are not filtered out for this product. Use for kits commonly sold as loose sprues without retail packaging (e.g. Bloodletters, small infantry sets).'),
        ),
    ]
