# Generated by Django 6.0.2 on 2026-03-05 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_ebay_allow_no_box'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ebay_negative_keywords',
            field=models.CharField(blank=True, default='', help_text='Space-separated words to exclude from eBay searches (eBay -word syntax). Use when eBay returns a similar but wrong product. e.g. "plastic" for Super Glue excludes "Citadel Plastic Glue" listings; "mk2" for Painting Handle XL excludes standard Mk2 handle listings.', max_length=200),
        ),
    ]
