# Generated by Django 6.0.2 on 2026-03-11 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_ebay_negative_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gw_search_name',
            field=models.CharField(blank=True, default='', help_text='Override name used when matching against the Games Workshop spreadsheet. Set this to the EXACT GW product title when the automatic matching picks the wrong product (e.g. "Khorne Berzerkers" for World Eaters Berzerkers, "Infiltrator Squad" for Space Marine Infiltrators). Leave blank to use the standard fuzzy-matching algorithm.', max_length=300),
        ),
    ]
