# Generated by Django 6.0.2 on 2026-03-20 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_newsletter_signup'),
    ]

    operations = [
        migrations.AddField(
            model_name='faction',
            name='parent_faction',
            field=models.ForeignKey(blank=True, help_text='Parent faction whose units this faction can also field (e.g. Space Marines for Ultramarines).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_factions', to='products.faction'),
        ),
    ]
