# Generated by Django 6.0.2 on 2026-04-03 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
        ('products', '0026_faction_stats_corrections6'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='batch_tag',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Internal label used to group products by the batch they were added in (e.g. "phase-2", "phase-3"). Never shown on the site. Use list_batch_skus to export a SKU list for any tag.', max_length=50),
        ),
        migrations.AlterField(
            model_name='faction',
            name='blog_tag',
            field=models.ForeignKey(blank=True, help_text='Blog tag whose posts appear in the Related Posts section of the faction page.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factions', to='blog.tag'),
        ),
        migrations.AlterField(
            model_name='faction',
            name='difficulty',
            field=models.CharField(blank=True, default='', help_text='Difficulty rating shown in the Quick Stats bar (e.g. "Beginner Friendly").', max_length=50),
        ),
        migrations.AlterField(
            model_name='faction',
            name='hero_image_url',
            field=models.URLField(blank=True, default='', help_text='URL to faction hero banner image.'),
        ),
        migrations.AlterField(
            model_name='faction',
            name='hero_tagline',
            field=models.CharField(blank=True, default='', help_text='Short hero strapline shown on the faction page (e.g. "The Emperor\'s Elite").', max_length=200),
        ),
        migrations.AlterField(
            model_name='faction',
            name='model_count_rating',
            field=models.CharField(blank=True, default='', help_text='Model count shown in the Quick Stats bar (e.g. "Low (20-40 models)").', max_length=50),
        ),
        migrations.AlterField(
            model_name='faction',
            name='painting_complexity',
            field=models.CharField(blank=True, default='', help_text='Painting complexity shown in the Quick Stats bar (e.g. "Easy-Medium").', max_length=50),
        ),
        migrations.AlterField(
            model_name='faction',
            name='playstyle',
            field=models.CharField(blank=True, default='', help_text='Playstyle summary shown in the Quick Stats bar (e.g. "Melee Elite").', max_length=100),
        ),
        migrations.AlterField(
            model_name='faction',
            name='price_range_display',
            field=models.CharField(blank=True, default='', help_text='Price range shown in the Quick Stats bar (e.g. "£-££").', max_length=50),
        ),
        migrations.AlterField(
            model_name='faction',
            name='synopsis',
            field=models.TextField(blank=True, default='', help_text='SEO-optimised faction description (~150-200 words) shown on the faction page.'),
        ),
    ]
