# Generated by Django 6.0.2 on 2026-04-10 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_add_batch_tag_to_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(max_length=60)),
                ('description', models.TextField()),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('emailed_at', models.DateTimeField(blank=True, help_text='When this report was included in the daily digest email.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_reports', to='products.product')),
            ],
            options={
                'verbose_name': 'Issue Report',
                'verbose_name_plural': 'Issue Reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
