# Generated by Django 6.0.2 on 2026-04-12 18:29

from django.db import migrations


# Keywords added to ALL products — general terms that pollute eBay results
# with sports merchandise and branded apparel.
GLOBAL_KEYWORDS = ['logo', 'ny rangers', 'new york']


def add_negative_keywords(apps, schema_editor):
    """Append general negative keywords to every product that lacks them."""
    Product = apps.get_model('products', 'Product')
    for product in Product.objects.all():
        existing = product.ebay_negative_keywords or ''
        existing_lower = existing.lower()
        to_add = [kw for kw in GLOBAL_KEYWORDS if kw not in existing_lower]
        if to_add:
            separator = ' ' if existing else ''
            product.ebay_negative_keywords = existing + separator + ' '.join(to_add)
            product.save(update_fields=['ebay_negative_keywords'])


def remove_negative_keywords(apps, schema_editor):
    """Strip the added keywords back out (best-effort reverse)."""
    Product = apps.get_model('products', 'Product')
    for product in Product.objects.all():
        if not product.ebay_negative_keywords:
            continue
        keywords = product.ebay_negative_keywords
        for kw in GLOBAL_KEYWORDS:
            keywords = keywords.replace(' ' + kw, '').replace(kw + ' ', '').replace(kw, '')
        product.ebay_negative_keywords = keywords.strip()
        product.save(update_fields=['ebay_negative_keywords'])


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_add_issue_report_model'),
    ]

    operations = [
        migrations.RunPython(add_negative_keywords, remove_negative_keywords),
    ]
