# Generated by Django 6.0.2 on 2026-04-12 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_add_general_ebay_negative_keywords'),
    ]

    operations = [
        migrations.RunPython(
            code=lambda apps, schema_editor: (
                apps.get_model('products', 'Product')
                .objects.filter(name='Ork Warboss with Attack Squig')
                .delete()
            ),
            reverse_code=migrations.RunPython.noop,
        ),
    ]
