# Generated by Django 6.0.2 on 2026-04-12 19:27
# SKUs sourced from miniaturemarket.com, wonderlandmodels.com, gamegoblins.com
# Only products with MISSING gw_sku are updated — existing values are preserved.

from django.db import migrations

# (name, sku) — same-kit products share one SKU (e.g. all four Ork flyers = 50-32)
ORK_SKUS = [
    ('Beastboss',                       '50-53'),
    ('Beastboss on Squigosaur',         '50-55'),
    ('Mozrog Skragbad',                 '50-55'),
    ("Big'ed Bossbunka",                '50-45'),
    ('Big Mek',                         '50-68'),
    ('Big Mek in Mega Armour',          '50-08'),
    ('Blitza-Bommer',                   '50-32'),
    ('Burna-Bommer',                    '50-32'),
    ('Dakkajet',                        '50-32'),
    ('Wazbom Blastajet',                '50-32'),
    ('Boomdakka Snazzwagon',            '50-39'),
    ('Boss Snikrot',                    '50-42'),
    ('Deffkilla Wartrike',              '50-38'),
    ('Deffkoptas',                      '50-58'),
    ('Ghazghkull Thraka',               '50-29'),
    ('Gorkanaut',                       '50-19'),
    ('Morkanaut',                       '50-19'),
    ('Hunta Rig',                       '50-46'),
    ('Kill Rig',                        '50-46'),
    ('Kommandos',                       '50-70'),
    ('Kustom Boosta-blasta',            '50-37'),
    ('Megatrakk Scrapjet',              '50-36'),
    ('Mek Gunz: Bubblechukka',          '50-26'),
    ('Mek Gunz: Kustom Mega-kannon',    '50-26'),
    ('Mek Gunz: Smasha Gun',            '50-26'),
    ('Mek Gunz: Traktor Kannon',        '50-26'),
    ('Ork Beast Snagga Boyz',           '50-51'),
    ('Ork Painboy',                     '50-25'),
    ('Ork Stormboyz',                   '50-13'),
    ('Ork Warbiker Mob',                '50-07'),
    ('Painboss',                        '50-49'),
    ('Rukkatrukk Squigbuggy',           '50-35'),
    ('Shokkjump Dragsta',               '50-34'),
    ('Squighog Boyz',                   '50-54'),
    ('Weirdboy',                        '50-62'),
    ('Zodgrod Wortsnagga',              '50-50'),
]


def _populate_ork_skus(apps, schema_editor):
    """Set gw_sku on Ork products that are currently missing one."""
    Product = apps.get_model('products', 'Product')
    for name, sku in ORK_SKUS:
        Product.objects.filter(name=name, gw_sku='').update(gw_sku=sku)
        # Also catch rows where gw_sku was never set (NULL stored as empty)
        Product.objects.filter(name=name, gw_sku__isnull=True).update(gw_sku=sku)


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_delete_ork_warboss_attack_squig'),
    ]

    operations = [
        migrations.RunPython(
            code=_populate_ork_skus,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
