# Generated by Django 6.0.2 on 2026-05-21 13:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0057_newsletter_preferences'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['sort_order', 'name'], 'verbose_name_plural': 'categories'},
        ),
        migrations.AddField(
            model_name='product',
            name='msrp_gbp',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='GW UK retail price in GBP. Populated by the GW UK MSRP scraper.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='newslettersignup',
            name='is_confirmed',
            field=models.BooleanField(default=True, help_text='Email address confirmed via opt-in link. Existing subscribers are True by default. New homepage signups start False until confirmation link is clicked.'),
        ),
        migrations.AlterField(
            model_name='newslettersignup',
            name='sunday_faction',
            field=models.BooleanField(default=False, help_text='Receive a Sunday personalised faction deal digest. Subscriber must also select at least one faction.'),
        ),
        migrations.AlterField(
            model_name='newslettersignup',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique token used to generate one-click confirm and unsubscribe links.', unique=True),
        ),
    ]
