# Generated by Django 6.0.2 on 2026-05-21 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0058_add_msrp_gbp'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ebay_search_name_uk',
            field=models.CharField(blank=True, default='', help_text='UK-only override for the eBay search query name (EBAY_GB). Leave blank to fall back to ebay_search_name, then product name. Use when UK eBay listings use different terminology than US listings.', max_length=200),
        ),
    ]
