# Generated by Django 6.0.2 on 2026-05-25 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0059_add_ebay_search_name_uk'),
    ]

    operations = [
        migrations.AddField(
            model_name='faction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp of the last field change — used by the sitemap for crawl prioritisation.'),
        ),
    ]
