# Generated by Django 6.0.2 on 2026-06-01 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0060_add_updated_at_to_faction'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='secondary_factions',
            field=models.ManyToManyField(blank=True, help_text='Additional factions this product should appear under on the site. The primary faction FK above is unchanged. Use this to surface cross-faction units (e.g. Chaos Daemons units that also belong to a mono-god faction).', related_name='secondary_products', to='products.faction'),
        ),
    ]
