# Generated by Django 5.2.11 on 2026-07-25 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0062_retailer_is_uk'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ebay_allow_forge_world',
            field=models.BooleanField(default=False, help_text='When True, eBay listings with "forge world" in the title are not filtered out for this product. Use only when Forge World IS the official manufacturer of this exact catalog SKU (e.g. Blood Bowl Star Players) rather than a different, untracked resin product sharing the same unit name.'),
        ),
    ]
