# Generated by Django 6.0.2 on 2026-08-12 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0063_add_ebay_allow_forge_world'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ebay_allow_3d',
            field=models.BooleanField(default=False, help_text='When True, the default -"3D" search exclusion (meant to block 3D-printed proxy/knockoff listings) is skipped for this product. Use ONLY when the official product name itself contains "3D" (e.g. "Deluxe Buildable 3D Terrain Set"), making that exclusion self-defeating since genuine listings also say "3D". Set explicitly per SKU — never auto-detected from the name, to avoid accidentally exposing other products to real 3D-printed knockoffs.'),
        ),
    ]
