# Generated by Django 6.0.2 on 2026-09-04 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0065_widen_ebay_negative_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='parent_category',
            field=models.ForeignKey(blank=True, help_text='Parent category for nested groupings (e.g. "Warhammer" under "Books and Novels"). Blank for top-level categories.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='products.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='author',
            field=models.CharField(blank=True, default='', help_text='Book author, displayed under the title as "by: Author Name". Blank for non-book products.', max_length=200),
        ),
    ]
