# Generated by Django 6.0.2 on 2026-09-07 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0066_category_parent_category_product_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ebay_trust_best_match',
            field=models.BooleanField(default=False, help_text='Books only (update_ebay_book_prices). When True, skips the cheaper-alternative comparison and always uses eBay Best Match #1, exactly like every book was matched before that comparison existed. Use for a title whose search query is too short/generic (a single bare word, no ISBN anchor) to safely rank by price -- confirmed on "Fulgrim", where the query kept surfacing new unrelated cheap items (bits, a t-shirt, a paint pot) no matter what negative keywords were added, while Best Match #1 was reliably correct.'),
        ),
    ]
