# Generated by Django 6.0.2 on 2026-09-11 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0067_product_ebay_trust_best_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='current_edition',
            field=models.CharField(blank=True, default='', help_text='Current edition ordinal (e.g. "10th", "4th", "11th"), used as a required eBay search keyword when the ISBN search returns no results, so the match still prefers a listing that states the current edition over an unlabelled or old one. Leave blank for non-rulebook products.', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='isbn',
            field=models.CharField(blank=True, default='', help_text='ISBN-10 of the current print edition, used as a precise eBay search anchor for rules books that get reprinted at each new game edition (Codexes, Battletomes) -- same principle as BookFormatPrice.isbn for novels. Leave blank for non-rulebook products.', max_length=20),
        ),
    ]
