# Generated by Django 6.0.2 on 2026-09-16 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0068_product_current_edition_product_isbn'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslettersignup',
            name='custom_categories',
            field=models.ManyToManyField(blank=True, help_text='Categories to include in the Monday Customized Game System email.', related_name='newsletter_subscribers', to='products.category'),
        ),
        migrations.AddField(
            model_name='newslettersignup',
            name='monday_custom',
            field=models.BooleanField(default=False, help_text='Receive the Monday Customized Game System deal digest. Off by default -- subscriber must opt in manually and select at least one category below.'),
        ),
        migrations.AlterField(
            model_name='newslettersignup',
            name='monday_40k',
            field=models.BooleanField(default=True, help_text='Receive the Wednesday Warhammer 40K deal digest.'),
        ),
    ]
