# Generated by Django 6.0.2 on 2026-09-16 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0069_newslettersignup_custom_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslettersignup',
            name='region',
            field=models.CharField(choices=[('us', 'US'), ('uk', 'UK')], default='us', help_text='Which region this subscriber gets ALL of their digests in -- one field controls currency/retailer scope for every digest below (Wednesday/Friday/Sunday/Monday), not a per-digest choice. US sends use USD prices from US retailers; UK sends use GBP prices from UK retailers (games-workshop-uk, ebay-uk, etc). Set explicitly at signup, not inferred silently from browsing.', max_length=2),
        ),
    ]
