# Generated by Django 6.0.2 on 2026-09-18 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0071_enable_pg_trgm'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslettersignup',
            name='consecutive_send_failures',
            field=models.PositiveIntegerField(default=0, help_text='Consecutive failed sends since the last successful one. Reset to 0 on success.'),
        ),
        migrations.AddField(
            model_name='newslettersignup',
            name='last_send_error',
            field=models.TextField(blank=True, default='', help_text='Error message from the most recent failed send attempt.'),
        ),
        migrations.AddField(
            model_name='newslettersignup',
            name='last_send_failed_at',
            field=models.DateTimeField(blank=True, help_text='When the most recent failed send attempt happened.', null=True),
        ),
    ]
