"""
Management command: import_prices

Imports product prices, URLs, and stock status from a CSV file into the
CurrentPrice model. Designed to work with the price_import_template.csv
file generated by this project.

CSV format (columns):
    gw_sku      - Games Workshop SKU (e.g. 48-75)
    product_name - Human-readable product name (informational only)
    retailer    - Retailer name as stored in DB (e.g. "Games Workshop", "Amazon")
    price       - Decimal price (e.g. 34.99). Leave blank to mark as unknown.
    url         - Direct buy link. Leave blank to clear.
    in_stock    - TRUE/FALSE/1/0/yes/no. Defaults to True if blank.

Usage:
    # Preview without saving (recommended first run):
    python manage.py import_prices --file price_import_template.csv --dry-run

    # Import only rows that have a price or URL filled in:
    python manage.py import_prices --file price_import_template.csv --skip-empty

    # Full import (all rows including blanks):
    python manage.py import_prices --file price_import_template.csv

    # Import a single retailer only:
    python manage.py import_prices --file price_import_template.csv --retailer "Amazon"

Notes:
    - Rows with no price AND no URL are skipped by default unless --import-empty
      is passed.
    - Retailer names must exactly match what is in the DB (case-insensitive).
    - Product lookup is by gw_sku. If a SKU is not found, the row is skipped
      with a warning.
    - Uses update_or_create so re-running is always safe (idempotent).
    - Price history is NOT written by this command — use the scraper for that.
"""

import csv
import os
from decimal import Decimal, InvalidOperation

from django.core.management.base import BaseCommand

from prices.models import CurrentPrice
from products.models import Product, Retailer


# Truthy strings for the in_stock column
_TRUTHY = {'true', '1', 'yes', 'y', 't'}
_FALSY  = {'false', '0', 'no', 'n', 'f'}


class Command(BaseCommand):
    """
    Import prices, URLs, and stock status from a CSV file.

    Idempotent — safe to re-run. Existing records are updated in place.
    """

    help = 'Import prices from a CSV file into CurrentPrice records.'

    def add_arguments(self, parser):
        """Register command-line arguments."""
        parser.add_argument(
            '--file',
            type=str,
            required=True,
            metavar='PATH',
            help='Path to the CSV file to import.',
        )
        parser.add_argument(
            '--dry-run',
            action='store_true',
            default=False,
            help='Preview changes without saving to the database.',
        )
        parser.add_argument(
            '--skip-empty',
            action='store_true',
            default=True,
            help=(
                'Skip rows where both price and URL are blank (default: on). '
                'Use --no-skip-empty to import blank rows too.'
            ),
        )
        parser.add_argument(
            '--no-skip-empty',
            dest='skip_empty',
            action='store_false',
            help='Import rows even if price and URL are both blank.',
        )
        parser.add_argument(
            '--retailer',
            type=str,
            default=None,
            metavar='NAME',
            help='Only import rows for this retailer (case-insensitive).',
        )

    def handle(self, *args, **options):
        """Entry point — parse CSV and update CurrentPrice records."""
        csv_path = options['file']
        dry_run   = options['dry_run']
        skip_empty = options['skip_empty']
        retailer_filter = options['retailer']

        # ── Validate file path ────────────────────────────────────────────────
        if not os.path.isfile(csv_path):
            self.stderr.write(self.style.ERROR(f'File not found: {csv_path}'))
            return

        self.stdout.write('\nCSV Price Import')
        self.stdout.write('=' * 55)
        self.stdout.write(f'  File       : {csv_path}')
        self.stdout.write(f'  Dry run    : {dry_run}')
        self.stdout.write(f'  Skip empty : {skip_empty}')
        if retailer_filter:
            self.stdout.write(f'  Retailer   : {retailer_filter}')
        self.stdout.write('=' * 55 + '\n')

        # ── Build lookup caches (avoid N+1 queries) ───────────────────────────
        product_cache = {
            p.gw_sku: p
            for p in Product.objects.filter(is_active=True)
        }
        retailer_cache = {
            r.name.lower(): r
            for r in Retailer.objects.filter(is_active=True)
        }

        self.stdout.write(
            f'Loaded {len(product_cache)} active products, '
            f'{len(retailer_cache)} active retailers.\n'
        )

        # ── Counters ──────────────────────────────────────────────────────────
        updated   = 0
        skipped   = 0
        not_found = 0
        errors    = 0
        row_num   = 0

        # ── Process CSV ───────────────────────────────────────────────────────
        with open(csv_path, newline='', encoding='utf-8-sig') as fh:
            reader = csv.DictReader(fh)

            # Validate headers
            required_cols = {'gw_sku', 'product_name', 'retailer', 'price', 'url', 'in_stock'}
            if reader.fieldnames:
                missing = required_cols - {c.strip().lower() for c in reader.fieldnames}
                if missing:
                    self.stderr.write(
                        self.style.ERROR(
                            f'CSV is missing required columns: {", ".join(sorted(missing))}'
                        )
                    )
                    return

            for row_num, row in enumerate(reader, start=2):  # row 1 = header
                # ── Extract and clean fields ──────────────────────────────────
                gw_sku        = row.get('gw_sku', '').strip()
                retailer_name = row.get('retailer', '').strip()
                price_raw     = row.get('price', '').strip()
                url_raw       = row.get('url', '').strip()
                in_stock_raw  = row.get('in_stock', '').strip()

                # ── Apply retailer filter ─────────────────────────────────────
                if retailer_filter and retailer_name.lower() != retailer_filter.lower():
                    skipped += 1
                    continue

                # ── Skip empty rows ───────────────────────────────────────────
                if skip_empty and not price_raw and not url_raw:
                    skipped += 1
                    continue

                # ── Lookup product ────────────────────────────────────────────
                product = product_cache.get(gw_sku)
                if not product:
                    self.stdout.write(
                        self.style.WARNING(
                            f'  [row {row_num}] SKU not found: {gw_sku!r} '
                            f'({retailer_name}) — skipped'
                        )
                    )
                    not_found += 1
                    continue

                # ── Lookup retailer ───────────────────────────────────────────
                retailer = retailer_cache.get(retailer_name.lower())
                if not retailer:
                    self.stdout.write(
                        self.style.WARNING(
                            f'  [row {row_num}] Retailer not found: {retailer_name!r} '
                            f'(SKU {gw_sku}) — skipped'
                        )
                    )
                    not_found += 1
                    continue

                # ── Parse price ───────────────────────────────────────────────
                price = None
                if price_raw:
                    try:
                        price = Decimal(price_raw.replace('£', '').replace('$', '').replace(',', ''))
                        if price < 0:
                            raise ValueError('Negative price')
                    except (InvalidOperation, ValueError) as exc:
                        self.stdout.write(
                            self.style.ERROR(
                                f'  [row {row_num}] Invalid price {price_raw!r} '
                                f'for {gw_sku} @ {retailer_name}: {exc}'
                            )
                        )
                        errors += 1
                        continue

                # ── Parse in_stock ────────────────────────────────────────────
                if in_stock_raw.lower() in _FALSY:
                    in_stock = False
                else:
                    # Default to True if blank or truthy
                    in_stock = True

                # ── Determine not_available ───────────────────────────────────
                # A row is "not available" only if we explicitly mark out of
                # stock AND there's no price — means retailer doesn't carry it.
                not_available = (price is None and url_raw == '' and not in_stock)

                # ── Preview (dry run) ─────────────────────────────────────────
                price_display = f'£{price:.2f}' if price is not None else '(no price)'
                stock_display = 'in stock' if in_stock else 'out of stock'
                url_display   = url_raw[:60] + '…' if len(url_raw) > 60 else url_raw or '(no url)'

                self.stdout.write(
                    f'  {gw_sku:8s}  {retailer_name:20s}  '
                    f'{price_display:10s}  {stock_display:12s}  {url_display}'
                )

                # ── Save to DB ────────────────────────────────────────────────
                if not dry_run:
                    defaults = {
                        'in_stock':      in_stock,
                        'not_available': not_available,
                        'url':           url_raw,
                    }
                    if price is not None:
                        defaults['price'] = price

                    try:
                        CurrentPrice.objects.update_or_create(
                            product=product,
                            retailer=retailer,
                            defaults=defaults,
                        )
                    except Exception as exc:  # noqa: BLE001
                        self.stdout.write(
                            self.style.ERROR(
                                f'  [row {row_num}] DB error for {gw_sku} @ '
                                f'{retailer_name}: {exc}'
                            )
                        )
                        errors += 1
                        continue

                updated += 1

        # ── Summary ───────────────────────────────────────────────────────────
        self.stdout.write('\n' + '=' * 55)
        self.stdout.write(self.style.SUCCESS('Summary'))
        self.stdout.write('=' * 55)
        self.stdout.write(f'  Rows processed  : {row_num}')
        self.stdout.write(self.style.SUCCESS(f'  Records updated : {updated}'))
        if skipped:
            self.stdout.write(f'  Skipped (empty) : {skipped}')
        if not_found:
            self.stdout.write(
                self.style.WARNING(f'  Not found       : {not_found} (bad SKU or retailer name)')
            )
        if errors:
            self.stdout.write(
                self.style.ERROR(f'  Errors          : {errors}')
            )
        if dry_run:
            self.stdout.write(
                self.style.WARNING('\n  DRY RUN — no changes saved to database.')
            )
        self.stdout.write('=' * 55 + '\n')
