"""
Management command: populate_astartes_legions_products

Creates / updates all Astartes Legions product entries for ThriftHammer,
seeds GW CurrentPrice records at MSRP.

Category: Horus Heresy (already exists in DB)
Faction:  Astartes Legions (created if not present)

Safe to run repeatedly (idempotent via update_or_create keyed on slug).

Usage:
    python manage.py populate_astartes_legions_products
"""

from django.core.management.base import BaseCommand

from prices.models import CurrentPrice
from products.models import Category, Faction, Product, Retailer

_IMG = 'https://www.warhammer.com/app/resources/catalog/product/920x950/{filename}'

# (slug, gw_sku, name, msrp, image_filename, gw_url, ebay_search_name)
PRODUCTS = [
    (
        'warhammer-the-horus-heresy-saturnine',
        'AL-001',
        'Warhammer: The Horus Heresy – Saturnine',
        322.00,
        '60013099002_ENGHorusHeresyAgeofDarknessSaturnine2ndEditionFirstWaveCoreGame1.jpg',
        'https://www.warhammer.com/en-US/shop/horus-heresy-age-of-darkness-saturnine-2025-eng',
        'Warhammer: The Horus Heresy – Saturnine',
    ),
    (
        'legiones-astartes-maximus-battle-group',
        'AL-002',
        'Legiones Astartes: Maximus Battle Group',
        220.00,
        '99123001078_HorusHeresyLegionesAstartesMaximusBattleGroup01.jpg',
        'https://www.warhammer.com/en-US/shop/legiones-astartes-maximus-battle-group-2026',
        'Legiones Astartes: Maximus Battle Group Horus Heresy',
    ),
    (
        'liber-astartes-loyalist-legiones-astartes-army-book',
        'AL-003',
        'Liber Astartes: Loyalist Legiones Astartes Army Book',
        73.50,
        '60043099014_ENGHorusHeresyLiberAstartesCodex1.jpg',
        'https://www.warhammer.com/en-US/shop/horus-heresy-liber-astartes-2025-eng',
        'Liber Astartes: Loyalist Legiones Astartes Army Book Horus Heresy',
    ),
    (
        'legiones-astartes-combat-force',
        'AL-004',
        'Legiones Astartes: Combat Force',
        170.00,
        '99123001092_HorusHeresyLegionesAstartesCombatForceArmyBox1.jpg',
        'https://www.warhammer.com/en-US/shop/horus-heresy-legiones-astartes-combat-force-2025',
        'Legiones Astartes: Combat Force Horus Heresy',
    ),
    (
        'whirlwind-missile-tank',
        'AL-005',
        'Whirlwind Missile Tank',
        69.00,
        '99123001082_HorusHeresyLegionesAstartesWhirlwindMissileTank01.jpg',
        'https://www.warhammer.com/en-US/shop/legiones-astartes-whirlwind-missile-tank-2026',
        'Whirlwind Missile Tank Horus Heresy',
    ),
    (
        'falchion-super-heavy-tank-destroyer',
        'AL-006',
        'Falchion Super-heavy Tank Destroyer',
        210.00,
        '99123001077_HorusHeresyLegionesAstartesFalchionSuperheavyTankDestroyer01.jpg',
        'https://www.warhammer.com/en-US/shop/legiones-astartes-falcion-super-heavy-tank-destroyer-2026',
        'Falchion Super-heavy Tank Destroyer Horus Heresy',
    ),
    (
        'spartan-prometheus-assault-tank',
        'AL-007',
        'Spartan Prometheus Assault Tank',
        122.00,
        '99123001081_HorusHeresyLegionesAstartesSpartanPrometheus01.jpg',
        'https://www.warhammer.com/en-US/shop/legiones-astartes-spartan-prometheus-assault-tank-2026',
        'Spartan Prometheus Assault Tank Horus Heresy',
    ),
    (
        'mkii-tactical-squad',
        'AL-008',
        'MKII Tactical Squad',
        90.00,
        '99123001058_HorusHeresyMkIITacticalSquad1.jpg',
        'https://www.warhammer.com/en-US/shop/legiones-astartes-mk2-tactical-squad-2025',
        'MKII Tactical Squad Horus Heresy',
    ),
    (
        'legion-praetor-with-power-axe',
        'AL-009',
        'Legion Praetor with Power Axe',
        37.25,
        '99123001028_HHPraetorPowerAxeLead.jpg',
        'https://www.warhammer.com/en-US/shop/legiones-astartes-praetor-with-power-axe-2022',
        'Legion Praetor with Power Axe Horus Heresy',
    ),
    (
        'legion-praetor-with-power-sword',
        'AL-010',
        'Legion Praetor with Power Sword',
        37.25,
        '99123001004_PraetorPowerSwordLead.jpg',
        'https://www.warhammer.com/en-US/shop/legiones-astartes-praetor-with-power-sword-2022',
        'Legion Praetor with Power Sword Horus Heresy',
    ),
    (
        'legion-cataphractii-praetor-and-chaplain-consul',
        'AL-011',
        'Legion Cataphractii Praetor & Chaplain Consul',
        60.00,
        '99123001023_HHPraetorandChaplainConsulLead.jpg',
        'https://www.warhammer.com/en-US/shop/legiones-astartes-praetor-and-chaplain-consul-2022',
        'Legion Cataphractii Praetor & Chaplain Consul Horus Heresy',
    ),
    (
        'legion-tartaros-terminator-squad',
        'AL-012',
        'Legion Tartaros Terminator Squad',
        96.00,
        '99123001022_TartarosTerminatorSquadLead.jpg',
        'https://www.warhammer.com/en-US/shop/legiones-astartes-terminator-tartaros-squad-2022',
        'Legion Tartaros Terminator Squad Horus Heresy',
    ),
    (
        'geigor-fell-hand',
        'AL-013',
        'Geigor Fell-Hand',
        35.00,
        '99123001021_HHGeigorFellHandLead.jpg',
        'https://www.warhammer.com/en-US/shop/hh-space-wolves-geigor-fell-hand-2022',
        'Geigor Fell-Hand Horus Heresy',
    ),
    (
        'dominion-zephon',
        'AL-014',
        'Dominion Zephon',
        35.00,
        '99123001020_DominionZephonLead.jpg',
        'https://www.warhammer.com/en-US/shop/horus-heresy-blood-angels-dominion-zephon-2022',
        'Dominion Zephon Horus Heresy',
    ),
    (
        'fafnir-rann',
        'AL-015',
        'Fafnir Rann',
        35.00,
        '99123001019_HHIFFafnirRannLead.jpg',
        'https://www.warhammer.com/en-US/shop/horus-heresy-imperial-fists-fafnir-rann-2022',
        'Fafnir Rann Horus Heresy',
    ),
    (
        'breacher-squad-upgrade-set',
        'AL-016',
        'Breacher Squad Upgrade Set',
        48.50,
        '99123001073_HorusHeresyLegionesAstartesBreacherSquadUpgradeSet1.jpg',
        'https://www.warhammer.com/en-US/shop/breacher-squad-upgrade-set-2026',
        'Breacher Squad Upgrade Set Horus Heresy',
    ),
    (
        'mkiii-breacher-squad',
        'AL-017',
        'MKIII Breacher Squad',
        73.50,
        '99123001072_HorusHeresyLegionesAstartesMkIIIBreacherSquad1.jpg',
        'https://www.warhammer.com/en-US/shop/horus-heresy-mk3-breacher-squad-2026',
        'MKIII Breacher Squad Horus Heresy',
    ),
    (
        'cataphractii-terminators-with-combi-bolters-and-power-fists',
        'AL-018',
        'Cataphractii Terminators with Combi-bolters and Power Fists',
        69.00,
        '99123001074_HorusHeresyLegionsAstartesCataphractiiTerminatorswithCombiBoltersPowerFists1.jpg',
        'https://www.warhammer.com/en-US/shop/cataphractii-terminators-combi-bolters-and-power-fists-2026',
        'Cataphractii Terminators with Combi-bolters and Power Fists Horus Heresy',
    ),
    (
        'mkii-assault-squad',
        'AL-019',
        'MkII Assault Squad',
        73.50,
        '99123001070_HorusHeresyLegionesAstartesMkIIAssaultSquad1.jpg',
        'https://www.warhammer.com/en-US/shop/legiones-astartes-mk2-assault-squad-2025',
        'MkII Assault Squad Horus Heresy',
    ),
    (
        'saturnine-praetor',
        'AL-020',
        'Saturnine Praetor',
        53.00,
        '99123001061_HorusHeresySaturninePraetor1.jpg',
        'https://www.warhammer.com/en-US/shop/legiones-astartes-saturnine-praetor-2025',
        'Saturnine Praetor Horus Heresy',
    ),
    (
        'saturnine-terminator-squad',
        'AL-021',
        'Saturnine Terminator Squad',
        82.00,
        '99123001059_HorusHeresySaturnineTerminators1.jpg',
        'https://www.warhammer.com/en-US/shop/legiones-astartes-saturnine-terminators-2025',
        'Saturnine Terminator Squad Horus Heresy',
    ),
    (
        'mkii-veteran-squad-with-disintegrator-weapons',
        'AL-022',
        'MKII Veteran Squad with Disintegrator Weapons',
        64.00,
        '99123001080_HorusHeresyMkIIDisintegratorVeteran1.jpg',
        'https://www.warhammer.com/en-US/shop/legiones-astartes-mk2-veteran-squad-with-disintegrators-2025',
        'MKII Veteran Squad with Disintegrator Weapons Horus Heresy',
    ),
    (
        'legion-mkvi-assault-squad',
        'AL-023',
        'Legion MKVI Assault Squad',
        73.50,
        '99123001041_HHMKVIAssaultSquad01.jpg',
        'https://www.warhammer.com/en-US/shop/horus-heresy-mk6-assault-marines-2023',
        'Legion MKVI Assault Squad Horus Heresy',
    ),
    (
        'legion-vindicator-siege-tank',
        'AL-024',
        'Legion Vindicator Siege Tank',
        78.00,
        '99123001030_HHVindicatorSiegeTank01.jpg',
        'https://www.warhammer.com/en-US/shop/legiones-astartes-vindicator-siege-tank-2023',
        'Legion Vindicator Siege Tank Horus Heresy',
    ),
    (
        'cerberus-heavy-tank-destroyer',
        'AL-025',
        'Cerberus Heavy Tank Destroyer',
        125.00,
        '99123001027_HHCerberusHeavyTank01.jpg',
        'https://www.warhammer.com/en-US/shop/legion-cerberus-heavy-tank-2023',
        'Cerberus Heavy Tank Destroyer Horus Heresy',
    ),
    (
        'sicaran-venator-tank-hunter',
        'AL-026',
        'Sicaran Venator Tank Hunter',
        89.00,
        '99123001016_SicaranVenator1.jpg',
        'https://www.warhammer.com/en-US/shop/legiones-astartes-sicaran-venator-2023',
        'Sicaran Venator Tank Hunter Horus Heresy',
    ),
    (
        'scimitar-jetbike-squadron',
        'AL-027',
        'Scimitar Jetbike Squadron',
        69.00,
        '99123001015_SkyHunterSquad2.jpg',
        'https://www.warhammer.com/en-US/shop/horus-heresy-sky-hunter-squadron-2023',
        'Scimitar Jetbike Squadron Horus Heresy',
    ),
    (
        'typhon-heavy-siege-tank',
        'AL-028',
        'Typhon Heavy Siege Tank',
        125.00,
        '99123001026_HHTyphonHeavySiegeTank01.jpg',
        'https://www.warhammer.com/en-US/shop/legion-typhon-heavy-siege-tank-2023',
        'Typhon Heavy Siege Tank Horus Heresy',
    ),
    (
        'scorpius-missile-tank',
        'AL-029',
        'Scorpius Missile Tank',
        73.00,
        '99123001017_HHWhirlwindScorpius01.jpg',
        'https://www.warhammer.com/en-US/shop/horus-heresy-scorpius-missile-tank-2022',
        'Scorpius Missile Tank Horus Heresy',
    ),
    (
        'deimos-pattern-predator-support-tank',
        'AL-030',
        'Deimos Pattern Predator Support Tank',
        78.00,
        '99123001018_HHPredatorTankLead.jpg',
        'https://www.warhammer.com/en-US/shop/horus-heresy-predator-support-tank-2022',
        'Deimos Pattern Predator Support Tank Horus Heresy',
    ),
    (
        'land-raider-explorator-carrier',
        'AL-031',
        'Land Raider Explorator/Carrier',
        96.00,
        '99123001014_HHLandRaiderProteusLead.jpg',
        'https://www.warhammer.com/en-US/shop/legiones-astartes-land-raider-proteus-2022',
        'Land Raider Explorator/Carrier Horus Heresy',
    ),
    (
        'heavy-weapons-upgrade-set-volkite-culverins-lascannons-and-autocannons',
        'AL-032',
        'Heavy Weapons Upgrade Set – Volkite Culverins, Lascannons, and Autocannons',
        48.50,
        '99123001011_HHHeavyWeaponsVolkiteCulverinsLascannonAutocannonSet3Lead.jpg',
        'https://www.warhammer.com/en-US/shop/legiones-astartes-volkite-culverins-and-lascannons-2022',
        'Heavy Weapons Upgrade Set – Volkite Culverins, Lascannons, and Autocannons Horus Heresy',
    ),
    (
        'heavy-weapons-upgrade-set-heavy-flamers-multi-meltas-and-plasma-cannons',
        'AL-033',
        'Heavy Weapons Upgrade Set – Heavy Flamers, Multi-meltas, and Plasma Cannons',
        48.50,
        '99123001010_HHWeaponHeavyFlamersMultiMeltasPlasmaCannonSet2Lead.jpg',
        'https://www.warhammer.com/en-US/shop/legiones-astartes-multi-meltas-and-plasma-cannons-2022',
        'Heavy Weapons Upgrade Set – Heavy Flamers, Multi-meltas, and Plasma Cannons Horus Heresy',
    ),
    (
        'leviathan-siege-dreadnought-with-claw-and-drill-weapons',
        'AL-034',
        'Leviathan Siege Dreadnought with Claw & Drill Weapons',
        89.00,
        '99123001031_LevDreadCCClawDrillLead.jpg',
        'https://www.warhammer.com/en-US/shop/leviathan-siege-dreadnought-with-claw-and-drill-weapons-2022',
        'Leviathan Siege Dreadnought with Claw & Drill Weapons Horus Heresy',
    ),
    (
        'leviathan-siege-dreadnought-ranged-weapons-frame',
        'AL-035',
        'Leviathan Siege Dreadnought Ranged Weapons Frame',
        32.00,
        '99123001034_LEVDreadRangedWeaponFRAMELead.jpg',
        'https://www.warhammer.com/en-US/shop/leviathan-dreadnought-ranged-weapons-frame-2022',
        'Leviathan Siege Dreadnought Ranged Weapons Frame Horus Heresy',
    ),
    (
        'contemptor-dreadnought-weapons-frame-2',
        'AL-036',
        'Contemptor Dreadnought Weapons Frame 2',
        32.00,
        '99123001033_ContemptorWeaponsFrame2Lead.jpg',
        'https://www.warhammer.com/en-US/shop/contemptor-dreadnought-weapons-frame-2-2022',
        'Contemptor Dreadnought Weapons Frame 2 Horus Heresy',
    ),
    (
        'contemptor-dreadnought-weapons-frame-1',
        'AL-037',
        'Contemptor Dreadnought Weapons Frame 1',
        32.00,
        '99123001032_ContemptorWeaponsFrame1Lead.jpg',
        'https://www.warhammer.com/en-US/shop/contemptor-dreadnought-weapons-frame-1-2022',
        'Contemptor Dreadnought Weapons Frame 1 Horus Heresy',
    ),
    (
        'leviathan-siege-dreadnought-with-ranged-weapons',
        'AL-038',
        'Leviathan Siege Dreadnought with Ranged Weapons',
        89.00,
        '99123001008_LeviathanDreadnoughtRangedWeaponsLead.jpg',
        'https://www.warhammer.com/en-US/shop/leviathan-dreadnought-with-ranged-weapons-2022',
        'Leviathan Siege Dreadnought with Ranged Weapons Horus Heresy',
    ),
    (
        'special-weapons-upgrade-set',
        'AL-039',
        'Special Weapons Upgrade Set',
        48.50,
        '99123001013_HHSpecialWeaponsUpgradeSetLead.jpg',
        'https://www.warhammer.com/en-US/shop/legiones-astartes-special-weapons-upgrade-set-2022',
        'Special Weapons Upgrade Set Horus Heresy',
    ),
    (
        'heavy-weapons-upgrade-set-missile-launchers-and-heavy-bolters',
        'AL-040',
        'Heavy Weapons Upgrade Set – Missile Launchers and Heavy Bolters',
        48.50,
        '99123001009_HHSMMissileLaunchersHeavyBoltersLead.jpg',
        'https://www.warhammer.com/en-US/shop/legiones-astartes-missile-launchers-and-heavy-bolters-2022',
        'Heavy Weapons Upgrade Set – Missile Launchers and Heavy Bolters Horus Heresy',
    ),
    (
        'kratos-assault-tank',
        'AL-041',
        'Kratos Assault Tank',
        136.50,
        '99123001002_HHKratosHeavyAssaultTankLead.jpg',
        'https://www.warhammer.com/en-US/shop/legiones-astartes-kratos-heavy-assault-tank-2022',
        'Kratos Assault Tank Horus Heresy',
    ),
    (
        'deimos-pattern-rhino',
        'AL-042',
        'Deimos Pattern Rhino',
        56.00,
        '99123001001_HHDeimosPatternRhinoLead.jpg',
        'https://www.warhammer.com/en-US/shop/legiones-astartes-deimos-pattern-rhino-2022',
        'Deimos Pattern Rhino Horus Heresy',
    ),
    (
        'glaive-super-heavy-special-weapons-tank',
        'AL-043',
        'Glaive Super-heavy Special Weapons Tank',
        210.00,
        '99123001076_HorusHeresyLegionesAstartesGlaiveSuperheavySpecialWeaponsTank01.jpg',
        'https://www.warhammer.com/en-US/shop/legiones-astartes-glaive-super-heavy-special-weapons-tank-2026',
        'Glaive Super-heavy Special Weapons Tank Horus Heresy',
    ),
    (
        'fellblade-super-heavy-battle-tank',
        'AL-044',
        'Fellblade Super-Heavy Battle Tank',
        210.00,
        '99123001071_HorusHeresyFellblade1.jpg',
        'https://www.warhammer.com/en-US/shop/legiones-astartes-fellblade-super-heavy-battle-tank-2025',
        'Fellblade Super-Heavy Battle Tank Horus Heresy',
    ),
    (
        'araknae-quad-accelerator-platform',
        'AL-045',
        'Araknae Quad Accelerator Platform',
        69.00,
        '99123001060_HorusHeresyLegionesAstartesAraknaeQuadAcceleratorPlatform1.jpg',
        'https://www.warhammer.com/en-US/shop/legiones-astartes-araknae-quad-accelerator-platform-2025',
        'Araknae Quad Accelerator Platform Horus Heresy',
    ),
    (
        'disintegrator-weapons-upgrade-set',
        'AL-046',
        'Disintegrator Weapons Upgrade Set',
        32.00,
        '99123001069_HorusHeresyUpgrades1.jpg',
        'https://www.warhammer.com/en-US/shop/horus-heresy-disintegrator-upgrade-set-2025',
        'Disintegrator Weapons Upgrade Set Horus Heresy',
    ),
    (
        'saturnine-dreadnought-weapons-ophion-configuration',
        'AL-047',
        'Saturnine Dreadnought Weapons – Ophion Configuration',
        32.00,
        '99123001068_HorusHeresySaturnineDreadnoughtWeaponsOphion1.jpg',
        'https://www.warhammer.com/en-US/shop/saturnine-dreadnought-weapons-ophion-2025',
        'Saturnine Dreadnought Weapons – Ophion Configuration Horus Heresy',
    ),
    (
        'saturnine-dreadnought-weapons-chiron-configuration',
        'AL-048',
        'Saturnine Dreadnought Weapons – Chiron Configuration',
        32.00,
        '99123001067_HorusHeresySaturnineDreadnoughtWeaponsChiron1.jpg',
        'https://www.warhammer.com/en-US/shop/saturnine-dreadnought-weapons-chiron-2025',
        'Saturnine Dreadnought Weapons – Chiron Configuration Horus Heresy',
    ),
    (
        'legion-drop-pod',
        'AL-049',
        'Legion Drop Pod',
        60.00,
        '99123001083_HorusHeresyLegionesAstartesDropPodRepackaged1.jpg',
        'https://www.warhammer.com/en-US/shop/legiones-astartes-drop-pod-2025',
        'Legion Drop Pod Horus Heresy',
    ),
    (
        'saturnine-siege-dreadnought-ophion-configuration',
        'AL-050',
        'Saturnine Siege Dreadnought – Ophion Configuration',
        114.00,
        '99123001066_HorusHeresySaturnineDreadnoughtOphionConfiguration1.jpg',
        'https://www.warhammer.com/en-US/shop/legion-astartes-saturnine-dreadnought-ophion-2025',
        'Saturnine Siege Dreadnought – Ophion Configuration Horus Heresy',
    ),
    (
        'saturnine-siege-dreadnought-chiron-configuration',
        'AL-051',
        'Saturnine Siege Dreadnought – Chiron Configuration',
        114.00,
        '99123001065_HorusHeresySaturnineDreadnoughtChironConfiguration1.jpg',
        'https://www.warhammer.com/en-US/shop/legiones-astartes-saturnine-dreadnought-chiron-2025',
        'Saturnine Siege Dreadnought – Chiron Configuration Horus Heresy',
    ),
    (
        'tarantula-sentry-guns',
        'AL-052',
        'Tarantula Sentry Guns',
        60.00,
        '99123001064_THHTarantulaSentryGuns01.jpg',
        'https://www.warhammer.com/en-US/shop/legiones-astartes-tarantula-sentry-guns-2025',
        'Tarantula Sentry Guns Horus Heresy',
    ),
    (
        'tarantula-missile-battery',
        'AL-053',
        'Tarantula Missile Battery',
        60.00,
        '99123001063_THHTarantulaMissileBattery01.jpg',
        'https://www.warhammer.com/en-US/shop/legiones-astartes-tarantula-missile-battery-2025',
        'Tarantula Missile Battery Horus Heresy',
    ),
    (
        'rapier-quad-heavy-bolters-and-graviton-cannon-battery',
        'AL-054',
        'Rapier Quad Heavy Bolters and Graviton Cannon Battery',
        73.50,
        '99123001057_THHRapierQuadHeavyBolters01.jpg',
        'https://www.warhammer.com/en-US/shop/legiones-astartes-rapier-quad-heavy-bolters-2025',
        'Rapier Quad Heavy Bolters and Graviton Cannon Battery Horus Heresy',
    ),
    (
        'rapier-laser-destroyer-and-quad-launcher-battery',
        'AL-055',
        'Rapier Laser Destroyer and Quad Launcher Battery',
        73.50,
        '99123001044_THHRapierLaserDestroyer01.jpg',
        'https://www.warhammer.com/en-US/shop/legiones-astartes-rapier-laser-destroyer-2025',
        'Rapier Laser Destroyer and Quad Launcher Battery Horus Heresy',
    ),
    (
        'melee-weapons-upgrade-set',
        'AL-056',
        'Melee Weapons Upgrade Set',
        48.50,
        '99123001042_THHLegionAstartesMeleeWeaponsUpgradeSet01.jpg',
        'https://www.warhammer.com/en-US/shop/legion-astartes-melee-weapons-upgrade-2024',
        'Melee Weapons Upgrade Set Horus Heresy',
    ),
    (
        'mkiii-legion-command-squad',
        'AL-057',
        'MKIII Legion Command Squad',
        53.00,
        '99123001046_THHMKIIICommandSquad01.jpg',
        'https://www.warhammer.com/en-US/shop/legiones-astartes-mkiii-command-squad-2024',
        'MKIII Legion Command Squad Horus Heresy',
    ),
    (
        'mkvi-legion-command-squad',
        'AL-058',
        'MKVI Legion Command Squad',
        53.00,
        '99123001045_THHMKVICommandSquad01.jpg',
        'https://www.warhammer.com/en-US/shop/legiones-astartes-mkvi-command-squad-2024',
        'MKVI Legion Command Squad Horus Heresy',
    ),
    (
        'deredeo-dreadnought-anvilus-configuration',
        'AL-059',
        'Deredeo Dreadnought: Anvilus Configuration',
        89.00,
        '99123001036_HHDeredeoDreadniughtAnvilusConfiguration01.jpg',
        'https://www.warhammer.com/en-US/shop/deredeo-dreadnought-anvilus-configuration-2023',
        'Deredeo Dreadnought: Anvilus Configuration Horus Heresy',
    ),
    (
        'centurion-with-power-maul',
        'AL-060',
        'Centurion with Power Maul',
        40.00,
        '99123001062_HorusHeresyCenturionPowerMaul1.jpg',
        'https://www.warhammer.com/en-US/shop/legiones-astartes-centurion-with-power-maul-2025',
        'Centurion with Power Maul  Horus Heresy',
    ),
    (
        'leviathan-siege-dreadnought-close-combat-weapons',
        'AL-061',
        'Leviathan Siege Dreadnought Close Combat Weapons',
        32.00,
        '99123001035_LeviathanDreadnoughtCloseCombatWeaponsFrameNewLead.jpg',
        'https://www.warhammer.com/en-US/shop/leviathan-dreadnought-close-combat-weapons-frame-2022',
        'Leviathan Siege Dreadnought Close Combat Weapons Horus Heresy',
    ),
    (
        'liber-hereticus-traitor-legiones-astartes-army-book',
        'AL-062',
        'Liber Hereticus: Traitor Legiones Astartes Army Book',
        73.50,
        '60043099015_ENGHorusHeresyLiberHereticusCodex1.jpg',
        'https://www.warhammer.com/en-US/shop/horus-heresy-liber-hereticus-2025-eng',
        'Liber Hereticus: Traitor Legiones Astartes Army Book Horus Heresy',
    ),
    (
        'ahzek-ahriman',
        'AL-063',
        'Ahzek Ahriman',
        35.00,
        '99123002003_AzhekAhrimanLead.jpg',
        'https://www.warhammer.com/en-US/shop/hh-thousand-sons-azhek-ahriman-2022',
        'Ahzek Ahriman Horus Heresy',
    ),
]


class Command(BaseCommand):
    help = 'Creates / updates Astartes Legions products and seeds GW prices. Idempotent.'

    def handle(self, *args, **options):
        hh_category, _ = Category.objects.get_or_create(
            slug='horus-heresy',
            defaults={'name': 'Horus Heresy'},
        )
        faction, _ = Faction.objects.get_or_create(
            slug='astartes-legions',
            defaults={'name': 'Astartes Legions', 'category': hh_category},
        )
        gw_retailer = Retailer.objects.filter(name='Games Workshop').first()

        created_count = updated_count = price_created = price_updated = 0

        for (slug, gw_sku, name, msrp, img_filename, gw_url, ebay_name) in PRODUCTS:
            product, created = Product.objects.update_or_create(
                slug=slug,
                defaults={
                    'name': name,
                    'gw_sku': gw_sku,
                    'msrp': msrp,
                    'image_url': _IMG.format(filename=img_filename),
                    'gw_url': gw_url,
                    'ebay_search_name': ebay_name,
                    'category': hh_category,
                    'faction': faction,
                    'is_active': True,
                    'batch_tag': 'astartes-legions',
                },
            )
            if created:
                created_count += 1
            else:
                updated_count += 1
            self.stdout.write(f'  {"Created" if created else "Updated"}: {name} ({gw_sku})')

            if gw_retailer and msrp is not None:
                _, p_created = CurrentPrice.objects.update_or_create(
                    product=product,
                    retailer=gw_retailer,
                    defaults={
                        'price': msrp,
                        'url': gw_url,
                        'in_stock': True,
                        'not_available': False,
                    },
                )
                if p_created:
                    price_created += 1
                else:
                    price_updated += 1

        self.stdout.write(self.style.SUCCESS(
            f'\npopulate_astartes_legions_products complete. '
            f'Products: {created_count} created, {updated_count} updated. '
            f'GW prices: {price_created} created, {price_updated} updated.'
        ))
