"""
Management command: populate_battletech_products

Creates the BattleTech product line as a new top-level Category
(no Faction subdivision — BattleTech is a standalone game system, not
a multi-faction wargame like 40k/AoS).

MSRP/images/URLs come from Catalyst Game Labs' own store
(store.catalystgamelabs.com), not Games Workshop. This category has no
GW retailer row at all -- product.msrp drives the site's MSRP/discount
reference directly (the existing fallback in views.py uses product.msrp
whenever there is no not_available=False GW CurrentPrice row).

product.gw_url is populated with the Catalyst store product URL (not a
real GW link) per explicit instruction -- this enables the "View" button
on the product detail page. Note the button's hardcoded label still
reads "View on GW" until/unless that template text is made generic.

Usage:
    python manage.py populate_battletech_products
"""

import decimal

from django.core.management.base import BaseCommand

from prices.models import CurrentPrice
from products.models import Category, Product, Retailer

# (slug, gw_sku, name, msrp, image_url, product_url, ebay_search_name)
PRODUCTS = [
    ('battletech-alpha-strike-commanders-edition', 'BT-003', 'BattleTech: Alpha Strike: Commander\'s Edition', decimal.Decimal('39.99'), 'https://store.catalystgamelabs.com/cdn/shop/products/E-CAT35680_BattleTechAlphaStrikeCommandersEdition3rdPrint-1.png?v=1619200943', 'https://store.catalystgamelabs.com/products/battletech-alpha-strike-commanders-edition?_pos=3&_fid=715e41335&_ss=c', 'BattleTech Alpha Strike Commander\'s Edition'),
    ('battletech-battle-of-tukayyid', 'BT-004', 'BattleTech: Battle of Tukayyid', decimal.Decimal('39.99'), 'https://store.catalystgamelabs.com/cdn/shop/products/CC-Battle-of-Tukayyid-Cover-ART.jpg?v=1606506133', 'https://store.catalystgamelabs.com/products/battletech-battle-of-tukayyid?_pos=4&_fid=715e41335&_ss=c', 'BattleTech Battle of Tukayyid'),
    ('battletech-beginner-box', 'BT-006', 'BattleTech: Beginner Box', decimal.Decimal('24.99'), 'https://store.catalystgamelabs.com/cdn/shop/files/Beginner-Box-Full-Layers-40th-Anniv-display_1.jpg?v=1715296907', 'https://store.catalystgamelabs.com/products/battletech-beginner-box?_pos=6&_fid=715e41335&_ss=c', 'BattleTech Beginner Box'),
    ('battletech-campaign-operations', 'BT-007', 'BattleTech: Campaign Operations', decimal.Decimal('39.99'), 'https://store.catalystgamelabs.com/cdn/shop/products/E-CAT35007_BattleTechCampaignOperations3rdPrint-1.png?v=1644339280', 'https://store.catalystgamelabs.com/products/battletech-campaign-operations-pdf?_pos=8&_fid=715e41335&_ss=c', 'BattleTech Campaign Operations'),
    ('battletech-battlemat-grasslands', 'BT-008', 'BattleTech: BattleMat (Grasslands)', decimal.Decimal('39.99'), 'https://store.catalystgamelabs.com/cdn/shop/products/MiniaturesonBattleMatt.jpg?v=1552847889', 'https://store.catalystgamelabs.com/products/battlemats?_pos=9&_fid=715e41335&_ss=c', 'BattleTech BattleMat Grasslands'),
    ('battletech-clan-invasion-salvage-box-93-designs', 'BT-010', 'BattleTech: Clan Invasion Salvage Box - 93 Designs!', decimal.Decimal('7.00'), 'https://store.catalystgamelabs.com/cdn/shop/products/IMG_1754.jpg?v=1645048626', 'https://store.catalystgamelabs.com/products/battletech-salvage-box-clan-invasion-full?_pos=11&_fid=715e41335&_ss=c', 'BattleTech Clan Invasion Salvage Box'),
    ('battletech-a-game-of-armored-combat', 'BT-011', 'BattleTech: A Game of Armored Combat', decimal.Decimal('59.99'), 'https://store.catalystgamelabs.com/cdn/shop/files/BattleTech-AGoAC-Full-Box-40-ANNIV.jpg?v=1715296798', 'https://store.catalystgamelabs.com/products/battletech-a-game-of-armored-combat?_pos=12&_fid=715e41335&_ss=c', 'BattleTech A Game of Armored Combat'),
    ('battletech-mechwarrior-destiny', 'BT-012', 'BattleTech: MechWarrior: Destiny', decimal.Decimal('39.99'), 'https://store.catalystgamelabs.com/cdn/shop/products/E-CAT35185_MechWarriorDestiny3rdprinting-1.png?v=1670634608', 'https://store.catalystgamelabs.com/products/mechwarrior-destiny?_pos=13&_fid=715e41335&_ss=c', 'BattleTech MechWarrior Destiny'),
    ('battletech-a-time-of-war-the-battletech-rpg', 'BT-013', 'BattleTech: A Time of War: The BattleTech RPG', decimal.Decimal('49.99'), 'https://store.catalystgamelabs.com/cdn/shop/products/E-CAT35005_BattleTechATimeofWar-1.jpg?v=1666465408', 'https://store.catalystgamelabs.com/products/battletech-a-time-of-war-the-battletech-rpg-pdf?_pos=14&_fid=715e41335&_ss=c', 'BattleTech A Time of War Roleplaying Game'),
    ('battletech-tactical-operations-advanced-units-equipment', 'BT-014', 'BattleTech: Tactical Operations: Advanced Units & Equipment', decimal.Decimal('39.99'), 'https://store.catalystgamelabs.com/cdn/shop/products/E-CAT35003VB_BattleTechTacticalOperationsAdvancedUnitsandEquipment6thP.jpg?v=1665117632', 'https://store.catalystgamelabs.com/products/battletech-tactical-operations-advanced-units-equipement?_pos=15&_fid=715e41335&_ss=c', 'BattleTech Tactical Operations: Advanced Units & Equipment'),
    ('battletech-tactical-operations-advanced-rules', 'BT-015', 'BattleTech: Tactical Operations: Advanced Rules', decimal.Decimal('39.99'), 'https://store.catalystgamelabs.com/cdn/shop/products/E-CAT35003VA_BattleTechTacticalOperationsAdvancedRules6thP.jpg?v=1665117520', 'https://store.catalystgamelabs.com/products/battletech-tactical-operations-advanced-rules?_pos=16&_fid=715e41335&_ss=c', 'BattleTech Tactical Operations Advanced Rules'),
    ('battletech-battlemat-battles-of-tukayyid', 'BT-016', 'BattleTech: BattleMat (Battles of Tukayyid)', decimal.Decimal('39.99'), 'https://store.catalystgamelabs.com/cdn/shop/products/CAT35800F_Tukayyid_BattleMat_RAC-DEP.png?v=1635460542', 'https://store.catalystgamelabs.com/products/battletech-battlemat-clan-invasion?_pos=17&_fid=715e41335&_ss=c', 'BattleTech BattleMat Battles of Tukayyid'),
    ('battletech-battlemat-alien-worlds', 'BT-017', 'BattleTech: BattleMat (Alien Worlds)', decimal.Decimal('39.99'), 'https://store.catalystgamelabs.com/cdn/shop/products/CAT35800P_Alien_Worlds_BattleMat_Box_RENDER.png?v=1651867790', 'https://store.catalystgamelabs.com/products/battletech-battlemat-alien-worlds?_pos=18&_fid=715e41335&_ss=c', 'BattleTech BattleMat Alien Worlds'),
    ('battletech-strategic-operations', 'BT-018', 'BattleTech: Strategic Operations', decimal.Decimal('39.99'), 'https://store.catalystgamelabs.com/cdn/shop/products/E-CAT35004_BattleTech-Strategic-Operations-4th-Printing.png?v=1645053853', 'https://store.catalystgamelabs.com/products/battletech-strategic-operations?_pos=19&_fid=715e41335&_ss=c', 'BattleTech Strategic Operations'),
    ('battletech-black-knight-premium-miniature', 'BT-019', 'BattleTech: Black Knight (Premium Miniature)', decimal.Decimal('14.99'), 'https://store.catalystgamelabs.com/cdn/shop/files/Black_Knight_3.png?v=1746465078', 'https://store.catalystgamelabs.com/products/black-knight-variant-miniature?_pos=20&_fid=715e41335&_ss=c', 'BattleTech Black Knight'),
    ('battletech-hot-spots-hinterlands', 'BT-021', 'BattleTech: Hot Spots: Hinterlands', decimal.Decimal('39.99'), 'https://store.catalystgamelabs.com/cdn/shop/files/HotSpots-Hinterlands_CoverRender.png?v=1732896900', 'https://store.catalystgamelabs.com/products/battletech-hot-spots-hinterlands?_pos=22&_fid=715e41335&_ss=c', 'BattleTech Hot Spots Hinterlands'),
    ('battletech-star-league-command-lance', 'BT-022', 'BattleTech: Star League Command Lance', decimal.Decimal('39.99'), 'https://store.catalystgamelabs.com/cdn/shop/files/StarLeagueCommandLanceBoxwminis11-27a.png?v=1715297557', 'https://store.catalystgamelabs.com/products/battletech-star-league-command-lance?_pos=23&_fid=715e41335&_ss=c', 'BattleTech Star League Command Lance'),
    ('battletech-interstellar-operations-alternate-eras', 'BT-023', 'BattleTech: Interstellar Operations: Alternate Eras', decimal.Decimal('45.00'), 'https://store.catalystgamelabs.com/cdn/shop/products/E-CAT35006VA_BattleTech-Interstellar-Operations-Alternate-Eras.png?v=1673578219', 'https://store.catalystgamelabs.com/products/battletech-interstellar-operations-alternate-eras?_pos=24&_fid=715e41335&_ss=c', 'BattleTech Interstellar Operations Alternate Eras'),
    ('battletech-alpha-strike-box-set', 'BT-024', 'BattleTech: Alpha Strike Box Set', decimal.Decimal('79.99'), 'https://store.catalystgamelabs.com/cdn/shop/products/ASBoxRenderDimension.png?v=1669137475', 'https://store.catalystgamelabs.com/products/battletech-alpha-strike-box-set?_pos=25&_fid=715e41335&_ss=c', 'BattleTech Alpha Strike Box Set'),
    ('battletech-phoenix-hawk-premium-miniature', 'BT-025', 'BattleTech: Phoenix Hawk (Premium Miniature)', decimal.Decimal('14.99'), 'https://store.catalystgamelabs.com/cdn/shop/files/Phoenix_Hawk_3.png?v=1746465275', 'https://store.catalystgamelabs.com/products/battletech-phoenix-hawk-premium-miniature?_pos=26&_fid=715e41335&_ss=c', 'BattleTech Phoenix Hawk'),
    ('battletech-interstellar-operations-battleforce', 'BT-026', 'BattleTech: Interstellar Operations: BattleForce', decimal.Decimal('50.00'), 'https://store.catalystgamelabs.com/cdn/shop/products/E-CAT35006VB_BattleTech-Interstellar-Operations-BattleForce.png?v=1673578202', 'https://store.catalystgamelabs.com/products/battletech-interstellar-operations-battleforce?_pos=27&_fid=715e41335&_ss=c', 'BattleTech Interstellar Operations BattleForce'),
    ('battletech-forcepack-black-remnant-command-lance', 'BT-027', 'BattleTech: ForcePack: Black Remnant Command Lance', decimal.Decimal('34.99'), 'https://store.catalystgamelabs.com/cdn/shop/files/BlackRemnantboxwithminis3DRender10-15a.png?v=1738001456', 'https://store.catalystgamelabs.com/products/battletech-forcepack-black-remnant-command-lance?_pos=28&_fid=715e41335&_ss=c', 'BattleTech ForcePack Black Remnant Command Lance'),
    ('battletech-forcepack-second-star-league-assault-lance', 'BT-028', 'BattleTech: ForcePack: Second Star League Assault Lance', decimal.Decimal('44.99'), 'https://store.catalystgamelabs.com/cdn/shop/files/sldf_2_lance_box_w_minis_3d_render_900x_07e9f956-4c3e-4d8d-843f-bb1eb3092b9a.webp?v=1734317598', 'https://store.catalystgamelabs.com/products/battletech-forcepack-second-star-league-assault-lance?_pos=29&_fid=715e41335&_ss=c', 'BattleTech ForcePack Second Star League Assault Lance'),
    ('battletech-battlemat-strana-mechty', 'BT-029', 'BattleTech: BattleMat (Strana Mechty)', decimal.Decimal('39.99'), 'https://store.catalystgamelabs.com/cdn/shop/products/CAT35800JStranaMechtyBattleMat.png?v=1635460788', 'https://store.catalystgamelabs.com/products/battletech-battlemat-circle-of-equals?_pos=30&_fid=715e41335&_ss=c', 'BattleTech BattleMat Strana Mechty'),
    ('battletech-essentials', 'BT-030', 'BattleTech: Essentials', decimal.Decimal('18.74'), 'https://store.catalystgamelabs.com/cdn/shop/files/Essentials_FrontCover.png?v=1731709578', 'https://store.catalystgamelabs.com/products/battletech-essentials?_pos=31&_fid=715e41335&_ss=c', 'BattleTech Essentials'),
    ('battletech-rifleman-premium-miniature', 'BT-031', 'BattleTech: Rifleman (Premium Miniature)', decimal.Decimal('14.99'), 'https://store.catalystgamelabs.com/cdn/shop/files/Rifleman_1_Draft1.png?v=1746465207', 'https://store.catalystgamelabs.com/products/battletech-rifleman-premium-miniature?_pos=32&_fid=715e41335&_ss=c', 'BattleTech Rifleman Miniature'),
    ('battletech-aces-scouring-sands', 'BT-032', 'BattleTech Aces Scouring Sands', decimal.Decimal('79.99'), 'https://store.catalystgamelabs.com/cdn/shop/files/Aces_ScouringSands_BoxCover.jpg?v=1763650263', 'https://store.catalystgamelabs.com/products/battletech-aces-scouring-sands?_pos=33&_fid=715e41335&_ss=c', 'BattleTech Aces Scouring Sands'),
    ('battletech-forcepack-house-davion-heavy-battle-lance', 'BT-033', 'BattleTech: ForcePack: House Davion Heavy Battle Lance', decimal.Decimal('34.99'), 'https://store.catalystgamelabs.com/cdn/shop/files/DavionHeavyBattleLance_BoxRender.png?v=1740000216', 'https://store.catalystgamelabs.com/products/battletech-forcepack-house-davion-heavy-battle-lance?_pos=34&_fid=715e41335&_ss=c', 'BattleTech ForcePack House Davion Heavy Battle Lance'),
    ('battletech-salvage-box-urbanmech-lam', 'BT-034', 'BattleTech: Salvage Box: Urbanmech LAM', decimal.Decimal('30.00'), 'https://store.catalystgamelabs.com/cdn/shop/files/UrbanMechLAMBoxdisplayrender4-19a.png?v=1715301767', 'https://store.catalystgamelabs.com/products/battletech-salvage-box-urbanmech-lam?_pos=35&_fid=715e41335&_ss=c', 'BattleTech Salvage Box Urbanmech LAM'),
    ('battletech-mappack-grasslands', 'BT-035', 'BattleTech: MapPack: Grasslands', decimal.Decimal('29.99'), 'https://store.catalystgamelabs.com/cdn/shop/products/CAT35150_BT_MapSet-Grasslands_Front.jpg?v=1552847348', 'https://store.catalystgamelabs.com/products/map-set-grasslands?_pos=36&_fid=715e41335&_ss=c', 'BattleTech MapPack Grasslands'),
    ('battletech-forcepack-3rd-star-league-strike-team', 'BT-036', 'BattleTech: ForcePack: 3rd Star League Strike Team', decimal.Decimal('44.99'), 'https://store.catalystgamelabs.com/cdn/shop/files/3rdStarLeagueStrikeTeamBoxwminis3-12a.png?v=1749842381', 'https://store.catalystgamelabs.com/products/battletech-forcepack-3rd-star-league-strike-team?_pos=37&_fid=715e41335&_ss=c', 'BattleTech ForcePack 3rd Star League Strike Team'),
    ('battletech-alpha-strike-clan-invasion-cards', 'BT-037', 'BattleTech: Alpha Strike: Clan Invasion Cards', decimal.Decimal('19.99'), 'https://store.catalystgamelabs.com/cdn/shop/products/AS-ClanInvasionCards.jpg?v=1635980198', 'https://store.catalystgamelabs.com/products/battletech-alpha-strike-clan-invasion-cards?_pos=38&_fid=715e41335&_ss=c', 'BattleTech Alpha Strike Clan Invasion Cards'),
    ('battletech-forcepack-urbanmech-lance', 'BT-038', 'BattleTech: ForcePack: UrbanMech Lance', decimal.Decimal('34.99'), 'https://store.catalystgamelabs.com/cdn/shop/files/UrbanMechLanceBox3Ddisplaywminis6-17a.png?v=1688148775', 'https://store.catalystgamelabs.com/products/battletech-forcepack-urbanmech-lance?_pos=39&_fid=715e41335&_ss=c', 'UrbanMech Lance Battletech Miniatures'),
    ('battletech-counterspack-alpha-strike', 'BT-039', 'BattleTech: CountersPack: Alpha Strike', decimal.Decimal('24.99'), 'https://store.catalystgamelabs.com/cdn/shop/products/CountersPack-AlphaStrike_Photo.jpg?v=1681487496', 'https://store.catalystgamelabs.com/products/battletech-counterspack-alpha-strike?_pos=40&_fid=715e41335&_ss=c', 'BattleTech: Alpha Strike Counters Pack'),
    ('battletech-mercenaries-box-set', 'BT-040', 'BattleTech: Mercenaries Box Set', decimal.Decimal('74.99'), 'https://store.catalystgamelabs.com/cdn/shop/files/Mercenariesboxset_FrontCover.png?v=1739215416', 'https://store.catalystgamelabs.com/products/battletech-mercenaries-box-set?_pos=41&_fid=715e41335&_ss=c', 'BattleTech Mercenaries Box Set'),
    ('battletech-mappack-alien-worlds', 'BT-041', 'BattleTech: MapPack: Alien Worlds', decimal.Decimal('24.99'), 'https://store.catalystgamelabs.com/cdn/shop/products/MapPack-AlienWorlds.jpg?v=1635438246', 'https://store.catalystgamelabs.com/products/mappack-alien-worlds?_pos=42&_fid=715e41335&_ss=c', 'Catalyst Battletech Map Pack Alien Worlds'),
    ('battletech-union-class-map-scale-dropship', 'BT-042', 'BattleTech: Union-Class Map Scale DropShip', decimal.Decimal('49.99'), 'https://store.catalystgamelabs.com/cdn/shop/files/Union_Dropship_FrontCam_large_d0d7ccca-51f3-44ec-846c-db0f807cd03a.jpg?v=1734316119', 'https://store.catalystgamelabs.com/products/battletech-union-class-map-scale-dropship?_pos=43&_fid=715e41335&_ss=c', 'BattleTech Union-Class Map Scale DropShip'),
    ('battletech-battlemat-bfm-grasslands-desert-base', 'BT-043', 'BattleTech: BattleMat BFM (Grasslands / Desert Base)', decimal.Decimal('159.99'), 'https://store.catalystgamelabs.com/cdn/shop/products/CAT35800MMMegaMat.png?v=1637864801', 'https://store.catalystgamelabs.com/products/battletech-battlemat-bfm-grasslands-desert?_pos=44&_fid=715e41335&_ss=c', 'BattleTech BattleMat BFM Grasslands Desert Base'),
    ('battletech-house-kurita-command-lance-forcepack', 'BT-044', 'BattleTech: House Kurita Command Lance ForcePack', decimal.Decimal('34.99'), 'https://store.catalystgamelabs.com/cdn/shop/files/KuritaCommandLanceboxrenderwithminis7-18a.png?v=1769006459', 'https://store.catalystgamelabs.com/products/battletech-house-kurita-command-lance-forcepack?_pos=45&_fid=715e41335&_ss=c', 'BattleTech House Kurita Command Lance ForcePack'),
    ('battletech-forcepack-proliferation-cycle', 'BT-045', 'BattleTech: ForcePack: Proliferation Cycle', decimal.Decimal('49.99'), 'https://store.catalystgamelabs.com/cdn/shop/files/ProliferationBox3Ddisplaywithminis6-17a.png?v=1688147173', 'https://store.catalystgamelabs.com/products/battletech-forcepack-proliferation-cycle?_pos=46&_fid=715e41335&_ss=c', 'Catalyst Battletech Forcepack Proliferation Cycle'),
    ('battletech-mappack-deserts', 'BT-046', 'BattleTech: MapPack: Deserts', decimal.Decimal('29.99'), 'https://store.catalystgamelabs.com/cdn/shop/products/MapPack-Deserts.jpg?v=1635437305', 'https://store.catalystgamelabs.com/products/mappack-deserts?_pos=47&_fid=715e41335&_ss=c', 'BattleTech MapPack Deserts'),
    ('battletech-initiative-deck', 'BT-047', 'BattleTech: Initiative Deck', decimal.Decimal('9.99'), 'https://store.catalystgamelabs.com/cdn/shop/products/IMG_5482.jpg?v=1637863053', 'https://store.catalystgamelabs.com/products/battletech-initiative-deck?_pos=48&_fid=715e41335&_ss=c', 'BattleTech Initiative Deck'),
    ('battletech-premium-miniature-battlemaster', 'BT-048', 'BattleTech: Premium Miniature: BattleMaster', decimal.Decimal('14.99'), 'https://store.catalystgamelabs.com/cdn/shop/files/Premium_BattleMaster.png?v=1739315923', 'https://store.catalystgamelabs.com/products/battletech-premium-miniature-battlemaster?_pos=49&_fid=715e41335&_ss=c', 'BattleTech Premium Miniature BattleMaster'),
    ('battletech-house-davion-cavalry-lance-forcepack', 'BT-049', 'BattleTech: House Davion Cavalry Lance ForcePack', decimal.Decimal('34.99'), 'https://store.catalystgamelabs.com/cdn/shop/files/DavionCavalryLance_BoxRender.png?v=1742578432', 'https://store.catalystgamelabs.com/products/battletech-house-davion-cavalry-lance-forcepack?_pos=50&_fid=715e41335&_ss=c', 'BattleTech House Davion Cavalry Lance ForcePack'),
    ('battletech-battlemat-aerospace', 'BT-050', 'BattleTech: BattleMat (Aerospace)', decimal.Decimal('39.99'), 'https://store.catalystgamelabs.com/cdn/shop/products/CAT35800LAerospaceBattleMat.png?v=1637864446', 'https://store.catalystgamelabs.com/products/battletech-battlemat-aerospace?_pos=51&_fid=715e41335&_ss=c', 'BattleTech BattleMat Aerospace'),
    ('battletech-overlord-class-map-scale-dropship', 'BT-051', 'BattleTech: Overlord-Class Map Scale DropShip', decimal.Decimal('64.99'), 'https://store.catalystgamelabs.com/cdn/shop/files/Overlord_Dropship_ThreeQuarter_large_92ce34af-eda5-4368-9712-9b8f913100c1.jpg?v=1734316379', 'https://store.catalystgamelabs.com/products/battletech-overlord-class-map-scale-dropship?_pos=52&_fid=715e41335&_ss=c', 'BattleTech Overlord-Class Map Scale DropShip'),
    ('battletech-mappack-battle-of-tukayyid', 'BT-052', 'BattleTech: MapPack: Battle of Tukayyid', decimal.Decimal('34.99'), 'https://store.catalystgamelabs.com/cdn/shop/products/BT-MapPackBattleforTukayyid3Dcover.jpg?v=1613413839', 'https://store.catalystgamelabs.com/products/battletech-mappack-battle-of-tukayyid?_pos=53&_fid=715e41335&_ss=c', 'Battle of Tukayyid Battletech Miniatures Game Catalyst Map Pack'),
    ('battletech-kell-hounds-striker-lance', 'BT-053', 'BattleTech: Kell Hounds Striker Lance', decimal.Decimal('34.99'), 'https://store.catalystgamelabs.com/cdn/shop/files/KellHoundsExclusiveForcePackdisplay4-22a.png?v=1734214823', 'https://store.catalystgamelabs.com/products/battletech-kell-hounds-striker-lance?_pos=54&_fid=715e41335&_ss=c', 'BattleTech Kell Hounds Striker Lance'),
    ('battletech-counterspack-battleforce', 'BT-054', 'BattleTech: CountersPack: BattleForce', decimal.Decimal('19.99'), 'https://store.catalystgamelabs.com/cdn/shop/products/BT-CountersPack-BattleForceFRONTdisplaycover.png?v=1657293697', 'https://store.catalystgamelabs.com/products/battletech-counterspack-battleforce?_pos=55&_fid=715e41335&_ss=c', 'Battletech Battleforce Counters Pack'),
    ('battletech-forcepack-gray-death-legion-heavy-battle-lance', 'BT-055', 'BattleTech: ForcePack: Gray Death Legion Heavy Battle Lance', decimal.Decimal('34.99'), 'https://store.catalystgamelabs.com/cdn/shop/files/GrayDeathLegionExclusiveForcePackdisplay4-22a.png?v=1734186519', 'https://store.catalystgamelabs.com/products/battletech-gray-death-legion-heavy-battle-lance?_pos=56&_fid=715e41335&_ss=c', 'BattleTech ForcePack Gray Death Legion Heavy Battle Lance'),
    ('battletech-forcepack-battle-fire-lances', 'BT-056', 'BattleTech: ForcePack: Battle & Fire Lances', decimal.Decimal('44.99'), 'https://store.catalystgamelabs.com/cdn/shop/files/BattlefieldSupport-Battle_FireLances_BoxRender.png?v=1739219362', 'https://store.catalystgamelabs.com/products/battletech-forcepack-battle-fire-lances?_pos=57&_fid=715e41335&_ss=c', 'BattleTech: Mercenaries Forcepack Battlefield Support Battle & Fire Lances'),
    ('battletech-battlemat-alpha-strike', 'BT-057', 'BattleTech: BattleMat (Alpha Strike)', decimal.Decimal('39.99'), 'https://store.catalystgamelabs.com/cdn/shop/products/CAT35800KAlphaStrikeBattleMat.png?v=1636577632', 'https://store.catalystgamelabs.com/products/battletech-battlemat-alpha-strike?_pos=58&_fid=715e41335&_ss=c', 'BattleTech BattleMat Alpha Strike'),
    ('battletech-gothic', 'BT-058', 'BattleTech: Gothic', decimal.Decimal('99.99'), 'https://store.catalystgamelabs.com/cdn/shop/files/CAT40000GothicBox3DRender1_3b21558e-f7e2-4486-8aa3-8f8476163b52.png?v=1759343102', 'https://store.catalystgamelabs.com/products/battletech-gothic?_pos=59&_fid=715e41335&_ss=c', 'BattleTech Gothic'),
    ('battletech-forcepack-third-star-league-battle-group', 'BT-059', 'BattleTech: ForcePack: Third Star League Battle Group', decimal.Decimal('44.99'), 'https://store.catalystgamelabs.com/cdn/shop/files/3rdStarLeagueBattleLanceBoxwminis2-20a.png?v=1758118642', 'https://store.catalystgamelabs.com/products/battletech-forcepack-third-star-league-battle-group?_pos=60&_fid=715e41335&_ss=c', 'BattleTech ForcePack Third Star League Battle Group'),
    ('battletech-forcepack-recon-hunter-lances', 'BT-060', 'BattleTech: ForcePack: Recon & Hunter Lances', decimal.Decimal('44.99'), 'https://store.catalystgamelabs.com/cdn/shop/files/BattlefieldSupport-Recon_HunterLances_BoxRender.png?v=1743620675', 'https://store.catalystgamelabs.com/products/battletech-forcepack-recon-hunter-lances?_pos=61&_fid=715e41335&_ss=c', 'BattleTech ForcePack Recon & Hunter Lances'),
    ('battletech-northwind-highlanders-command-lance', 'BT-061', 'BattleTech: Northwind Highlanders Command Lance', decimal.Decimal('34.99'), 'https://store.catalystgamelabs.com/cdn/shop/files/NorthwindHighlandersExclusiveForcePackdisplay4-23a.png?v=1734215039', 'https://store.catalystgamelabs.com/products/battletech-northwind-highlanders-command-lance?_pos=62&_fid=715e41335&_ss=c', 'BattleTech Northwind Highlanders Command Lance'),
    ('battletech-overlord-c-class-map-scale-dropship', 'BT-062', 'BattleTech: Overlord C-Class Map Scale Dropship', decimal.Decimal('69.99'), 'https://store.catalystgamelabs.com/cdn/shop/files/OverlordClan_Dropship_FrontCam_large_54dd8111-31ee-40ee-8933-7f8d3a9dd11e.jpg?v=1734316743', 'https://store.catalystgamelabs.com/products/battletech-overlord-c-class-map-scale-dropship?_pos=63&_fid=715e41335&_ss=c', 'BattleTech Overlord C-Class Map Scale Dropship'),
    ('battletech-legendary-mechwarriors-iii-forcepack', 'BT-063', 'BattleTech: Legendary MechWarriors III ForcePack', decimal.Decimal('44.99'), 'https://store.catalystgamelabs.com/cdn/shop/files/Legendary_MechWarriors_III_BoxRender.png?v=1747417089', 'https://store.catalystgamelabs.com/products/battletech-legendary-mechwarriors-iii-forcepack?_pos=64&_fid=715e41335&_ss=c', 'BattleTech Legendary MechWarriors III ForcePack'),
    ('battletech-forcepack-clan-direct-fire-star', 'BT-064', 'BattleTech: ForcePack: Clan Direct Fire Star', decimal.Decimal('39.99'), 'https://store.catalystgamelabs.com/cdn/shop/files/ClanDirectFireStar_BoxRender.png?v=1739216129', 'https://store.catalystgamelabs.com/products/battletech-forcepack-clan-direct-fire-star?_pos=65&_fid=715e41335&_ss=c', 'BattleTech ForcePack Clan Direct Fire Star'),
    ('battletech-house-kurita-ranger-lance-forcepack', 'BT-065', 'BattleTech: House Kurita Ranger Lance ForcePack', decimal.Decimal('34.99'), 'https://store.catalystgamelabs.com/cdn/shop/files/KuritaRangerLanceboxrenderwithminis7-18a.png?v=1770991818', 'https://store.catalystgamelabs.com/products/battletech-house-kurita-ranger-lance-forcepack?_pos=66&_fid=715e41335&_ss=c', 'BattleTech House Kurita Ranger Lance ForcePack'),
    ('battletech-forcepack-inner-sphere-recon-lance', 'BT-066', 'BattleTech: ForcePack: Inner Sphere Recon Lance', decimal.Decimal('34.99'), 'https://store.catalystgamelabs.com/cdn/shop/files/InnerSphereReconLance_BoxRender.png?v=1739218760', 'https://store.catalystgamelabs.com/products/battletech-forcepack-inner-sphere-recon-lance?_pos=67&_fid=715e41335&_ss=c', 'BattleTech ForcePack Inner Sphere Recon Lance'),
    ('battletech-forcepack-inner-sphere-security-lance', 'BT-067', 'BattleTech: ForcePack: Inner Sphere Security Lance', decimal.Decimal('34.99'), 'https://store.catalystgamelabs.com/cdn/shop/files/InnerSphereSecurityLance_BoxRender.png?v=1739995015', 'https://store.catalystgamelabs.com/products/battletech-forcepack-inner-sphere-security-lance?_pos=68&_fid=715e41335&_ss=c', 'BattleTech ForcePack Inner Sphere Security Lance'),
    ('battletech-forcepack-mccarrons-armored-cavalry-assault-lance', 'BT-068', 'BattleTech: Forcepack: McCarron\'s Armored Cavalry Assault Lance', decimal.Decimal('34.99'), 'https://store.catalystgamelabs.com/cdn/shop/files/McCarron_rsArmoredCavalryAssaultLance_BoxRender.png?v=1752515905', 'https://store.catalystgamelabs.com/products/battletech-forcepack-mccarrons-armored-cavalry-assault-lance?_pos=69&_fid=715e41335&_ss=c', 'Battletech McCarron\'s Armored Cavalry Assault Lance'),
    ('battletech-forcepack-rifle-command-lances', 'BT-069', 'BattleTech: ForcePack: Rifle & Command Lances', decimal.Decimal('44.99'), 'https://store.catalystgamelabs.com/cdn/shop/files/BT_Rifle_Command.png?v=1739320528', 'https://store.catalystgamelabs.com/products/battletech-forcepack-rifle-command-lances?_pos=70&_fid=715e41335&_ss=c', 'BattleTech ForcePack Rifle & Command Lances'),
    ('battletech-forcepack-hansens-rough-riders-battle-lance', 'BT-070', 'BattleTech: ForcePack: Hansen\'s Rough Riders Battle Lance', decimal.Decimal('34.99'), 'https://store.catalystgamelabs.com/cdn/shop/files/HansensRoughridersdisplay.png?v=1734215751', 'https://store.catalystgamelabs.com/products/battletech-hansens-rough-riders-battle-lance?_pos=71&_fid=715e41335&_ss=c', 'Hansen\'s Roughriders Battle Lance Battletech Catalyst'),
    ('battletech-forcepack-clan-cavalry-star', 'BT-071', 'BattleTech: ForcePack: Clan Cavalry Star', decimal.Decimal('39.99'), 'https://store.catalystgamelabs.com/cdn/shop/files/ClanCavalryStar_BoxRender.png?v=1739219118', 'https://store.catalystgamelabs.com/products/battletech-forcepack-clan-cavalry-star?_pos=72&_fid=715e41335&_ss=c', 'BattleTech ForcePack Clan Cavalry Star'),
    ('battletech-forcepack-assault-cavalry-lances', 'BT-072', 'BattleTech: ForcePack: Assault & Cavalry Lances', decimal.Decimal('44.99'), 'https://store.catalystgamelabs.com/cdn/shop/files/BattlefieldSupport-Assault_CavalryLances_BoxRender.png?v=1741203944', 'https://store.catalystgamelabs.com/products/battletech-forcepack-assault-calvalry-lances?_pos=73&_fid=715e41335&_ss=c', 'BattleTech ForcePack Assault & Cavalry Lances'),
    ('battletech-battlemat-twycross-plain-of-curtains-great-gash', 'BT-073', 'BattleTech: BattleMat: Twycross Plain of Curtains & Great Gash', decimal.Decimal('39.99'), 'https://store.catalystgamelabs.com/cdn/shop/files/BattleMat-LegendaryBattles-Twycross_BoxRender_1.png?v=1749843639', 'https://store.catalystgamelabs.com/products/battletech-battlemat-twycross-plain-of-curtains-great-gash?_pos=74&_fid=715e41335&_ss=c', 'BattleTech BattleMat Twycross Plain of Curtains & Great Gash'),
    ('battletech-map-pack-savannahs', 'BT-074', 'BattleTech: Map Pack: Savannahs', decimal.Decimal('29.99'), 'https://store.catalystgamelabs.com/cdn/shop/files/MapPack-Savannah_FrontRender.png?v=1739218272', 'https://store.catalystgamelabs.com/products/battletech-map-pack-savannahs?_pos=75&_fid=715e41335&_ss=c', 'BattleTech Map Pack Savannahs'),
    ('battletech-battlefield-support-deck-revised', 'BT-075', 'BattleTech: Battlefield Support Deck (Revised)', decimal.Decimal('9.99'), 'https://store.catalystgamelabs.com/cdn/shop/products/BattleTechBattlefieldSupportDeckDisplayCover9-9a.png?v=1633740503', 'https://store.catalystgamelabs.com/products/battletech-battlefield-support-deck-revised?_pos=76&_fid=715e41335&_ss=c', 'BattleTech Battlefield Support Deck (Revised)'),
    ('battletech-forcepack-support-emplacements', 'BT-076', 'BattleTech: ForcePack: Support Emplacements', decimal.Decimal('49.99'), 'https://store.catalystgamelabs.com/cdn/shop/files/BTEmplacementsBoxwminis3DRender6-4a.png?v=1758119532', 'https://store.catalystgamelabs.com/products/battletech-forcepack-support-emplacements?_pos=77&_fid=715e41335&_ss=c', 'BattleTech ForcePack Support Emplacements'),
    ('battletech-map-pack-city', 'BT-077', 'BattleTech: Map Pack: City', decimal.Decimal('34.99'), 'https://store.catalystgamelabs.com/cdn/shop/files/MapPack-City_FrontRender.png?v=1742576689', 'https://store.catalystgamelabs.com/products/battletech-map-pack-city?_pos=78&_fid=715e41335&_ss=c', 'BattleTech Map Pack City'),
    ('battletech-forcepack-eridani-light-horse-hunter-lance', 'BT-078', 'BattleTech: ForcePack: Eridani Light Horse Hunter Lance', decimal.Decimal('34.99'), 'https://store.catalystgamelabs.com/cdn/shop/files/ELHBNExclusivewebdisplay3-3a.png?v=1734215513', 'https://store.catalystgamelabs.com/products/battletech-eridani-light-horse-hunter-lance?_pos=79&_fid=715e41335&_ss=c', 'BattleTech ForcePack Eridani Light Horse Hunter Lance'),
    ('battletech-forcepack-inner-sphere-pursuit-lance', 'BT-079', 'BattleTech: ForcePack: Inner Sphere Pursuit Lance', decimal.Decimal('34.99'), 'https://store.catalystgamelabs.com/cdn/shop/files/Inner_Sphere_Pursuit_Lance_BoxRender.png?v=1747414125', 'https://store.catalystgamelabs.com/products/battletech-forcepack-inner-sphere-pursuit-lance?_pos=80&_fid=715e41335&_ss=c', 'BattleTech ForcePack Inner Sphere Pursuit Lance'),
    ('battletech-inner-sphere-heavy-recon-lance', 'BT-080', 'BattleTech: Inner Sphere Heavy Recon Lance', decimal.Decimal('34.99'), 'https://store.catalystgamelabs.com/cdn/shop/files/InnerSphereHeavyReconLance_BoxRender.png?v=1743620230', 'https://store.catalystgamelabs.com/products/battletech-inner-sphere-heavy-recon-lance?_pos=81&_fid=715e41335&_ss=c', 'BattleTech Inner Sphere Heavy Recon Lance'),
    ('battletech-forcepack-inner-sphere-battle-armor-platoon', 'BT-081', 'BattleTech: ForcePack: Inner Sphere Battle Armor Platoon', decimal.Decimal('34.99'), 'https://store.catalystgamelabs.com/cdn/shop/files/InnerSphereBattleArmorPlatoon_BoxRender.png?v=1741181825', 'https://store.catalystgamelabs.com/products/battletech-forcepack-inner-sphere-battle-armor-platoon?_pos=82&_fid=715e41335&_ss=c', 'BattleTech ForcePack Inner Sphere Battle Armor Platoon'),
    ('battletech-salvagebox-legendary-warriors-individual', 'BT-082', 'BattleTech SalvageBox: Legendary Warriors [Individual]', decimal.Decimal('8.99'), 'https://store.catalystgamelabs.com/cdn/shop/files/SalvageBoxLEGENDARYWARRIORSIndividualBoxForPrint11-4a.png?v=1777405032', 'https://store.catalystgamelabs.com/products/battletech-salvagebox-legendary-warriors-individual?_pos=83&_fid=715e41335&_ss=c', 'BattleTech Salvage Box: Legendary Warriors'),
    ('battletech-battlefield-support-objectives-forcepack', 'BT-083', 'BattleTech: Battlefield Support: Objectives ForcePack', decimal.Decimal('34.99'), 'https://store.catalystgamelabs.com/cdn/shop/files/BattlefieldSupport-Objectives_BoxRender.png?v=1744793824', 'https://store.catalystgamelabs.com/products/battletech-battlefield-support-objectives-forcepack?_pos=84&_fid=715e41335&_ss=c', 'BattleTech Battlefield Support Objectives ForcePack'),
    ('battletech-bfm-volcanicglacier', 'BT-084', 'BattleTech BFM: Volcanic/Glacier', decimal.Decimal('149.99'), 'https://store.catalystgamelabs.com/cdn/shop/files/FireandIceBFMdisplayRenderBOX4-28a.png?v=1777410476', 'https://store.catalystgamelabs.com/products/battletech-bfm-volcanic-glacier?_pos=85&_fid=715e41335&_ss=c', 'BattleTech battlemat Volcanic/Glacier'),
    ('battletech-battlemat-legendary-battles-thunder-rift-misery', 'BT-085', 'BattleTech: BattleMat: Legendary Battles Thunder Rift & Misery', decimal.Decimal('39.99'), 'https://store.catalystgamelabs.com/cdn/shop/files/BattleMat-LegendaryBattles-ThunderRift_Misery_BoxRender.png?v=1752515657', 'https://store.catalystgamelabs.com/products/battletech-battlemat-legendary-battles-thunder-rift-misery?_pos=86&_fid=715e41335&_ss=c', 'BattleTech BattleMat Legendary Battles Thunder Rift & Misery'),
    ('battletech-legendary-mechwarriors-ii-forcepack', 'BT-086', 'BattleTech: Legendary MechWarriors II ForcePack', decimal.Decimal('39.99'), 'https://store.catalystgamelabs.com/cdn/shop/files/cat35768.jpg?v=1744793918', 'https://store.catalystgamelabs.com/products/battletech-legendary-mechwarriors-ii-forcepack?_pos=87&_fid=715e41335&_ss=c', 'BattleTech Legendary MechWarriors II ForcePack'),
    ('battletech-forcepack-heavy-battle-sweep-lances', 'BT-087', 'BattleTech: ForcePack: Heavy Battle & Sweep Lances', decimal.Decimal('44.99'), 'https://store.catalystgamelabs.com/cdn/shop/files/CAT35778__54581-2.webp?v=1749843045', 'https://store.catalystgamelabs.com/products/battletech-forcepack-heavy-battle-sweep-lances?_pos=88&_fid=715e41335&_ss=c', 'BattleTech ForcePack Heavy Battle & Sweep Lances'),
    ('battletech-forcepack-inner-sphere-assault-lance', 'BT-088', 'BattleTech: ForcePack: Inner Sphere Assault Lance', decimal.Decimal('34.99'), 'https://store.catalystgamelabs.com/cdn/shop/files/InnerSphereAssaultLance_BoxRender.png?v=1749842641', 'https://store.catalystgamelabs.com/products/battletech-forcepack-inner-sphere-assault-lance?_pos=89&_fid=715e41335&_ss=c', 'BattleTech ForcePack Inner Sphere Assault Lance'),
    ('battletech-timber-wolf-c-scale', 'BT-089', 'BattleTech Timber Wolf C-Scale', decimal.Decimal('39.99'), 'https://store.catalystgamelabs.com/cdn/shop/files/BattleTechTimberWolfC-ScaleBoxfront.png?v=1777406549', 'https://store.catalystgamelabs.com/products/battletech-timber-wolf-c-scale?_pos=90&_fid=715e41335&_ss=c', 'BattleTech Timber Wolf C-Scale'),
    ('battletech-mappack-volcanic', 'BT-090', 'BattleTech: MapPack: Volcanic', decimal.Decimal('34.99'), 'https://store.catalystgamelabs.com/cdn/shop/files/CAT35157BattleTechMapPackVolcanicCover.png?v=1779823842', 'https://store.catalystgamelabs.com/products/battletech-mappack-volcanic?_pos=91&_fid=715e41335&_ss=c', 'BattleTech Map Pack Volcanic'),
    ('battletech-somerset-strikers-forcepack', 'BT-091', 'BattleTech: Somerset Strikers ForcePack', decimal.Decimal('39.99'), 'https://store.catalystgamelabs.com/cdn/shop/files/SomersetStrikers_BoxRender.png?v=1742577907', 'https://store.catalystgamelabs.com/products/battletech-somerset-strikers-forcepack?_pos=92&_fid=715e41335&_ss=c', 'Battletech Somerset Strikers Force Pack'),
    ('battletech-encounters', 'BT-092', 'BattleTech Encounters', decimal.Decimal('29.99'), 'https://store.catalystgamelabs.com/cdn/shop/files/BTEncounters.jpg?v=1763510620', 'https://store.catalystgamelabs.com/products/battletech-encounters?_pos=93&_fid=715e41335&_ss=c', 'BattleTech Encounters'),
    ('battletech-battlemat-fire-and-ice-01-erupting-canyon', 'BT-093', 'BattleTech: BattleMat: Fire and Ice 01: Erupting Canyon', decimal.Decimal('39.99'), 'https://store.catalystgamelabs.com/cdn/shop/files/BM_Fire_and_Ice_01_Erupting_Canyon.png?v=1780002748', 'https://store.catalystgamelabs.com/products/battletech-battlemat-fire-and-ice-01-erupting-canyon?_pos=94&_fid=715e41335&_ss=c', 'Battletech Battle Mat Fire And Ice'),
    ('battletech-battlemat-savannah-large-lakes', 'BT-094', 'BattleTech: BattleMat: Savannah Large Lakes', decimal.Decimal('39.99'), 'https://store.catalystgamelabs.com/cdn/shop/files/BattleMat-Savannah-LargeLakes_BoxRender.png?v=1749843260', 'https://store.catalystgamelabs.com/products/battletech-battlemat-savannah-large-lakes?_pos=95&_fid=715e41335&_ss=c', 'Catalyst Battletech Battle Mat Savannah Lakes'),
    ('battletech-battlemat-savannah-desert-sinkholes', 'BT-095', 'BattleTech: BattleMat: Savannah Desert Sinkholes', decimal.Decimal('39.99'), 'https://store.catalystgamelabs.com/cdn/shop/files/BattleMat-Savannah-Sinkholes_BoxRender.png?v=1749843428', 'https://store.catalystgamelabs.com/products/battletech-battlemat-savannah-desert-sinkholes?_pos=96&_fid=715e41335&_ss=c', 'BattleTech BattleMat Savannah Desert Sinkholes'),
    ('battletech-gothic-salvage-box-individual-blind-box', 'BT-096', 'BattleTech Gothic Salvage Box (Individual Blind Box)', decimal.Decimal('9.99'), 'https://store.catalystgamelabs.com/cdn/shop/files/CAT40002BattleTechGothicSalvageIndividualbox_7ea619da-3124-443a-a6c0-054aab631e59.jpg?v=1762361971', 'https://store.catalystgamelabs.com/products/battletech-gothic-salvage-box-individual-blind-box?_pos=97&_fid=715e41335&_ss=c', 'BattleTech Gothic Salvage Box'),
    ('battletech-battlemat-fire-and-ice-02-magma-fjords', 'BT-097', 'BattleTech: BattleMat: Fire and Ice 02: Magma Fjords', decimal.Decimal('39.99'), 'https://store.catalystgamelabs.com/cdn/shop/files/BattleMatFireandIce02MagmaFjordsdisplay5-28a.png?v=1782495760', 'https://store.catalystgamelabs.com/products/battletech-battlemat-fire-and-ice-02-magma-fjords?_pos=98&_fid=715e41335&_ss=c', 'BattleTech Battlemat Fire and Ice Magma Fjords'),
    # BT-098 to BT-106: Inner Sphere Lances, split out of the former BT-001
    # "ForcePacks: Inner Sphere" bundle (removed 2026-07-10) so each lance
    # can be matched to its own listing.
    ('battletech-inner-sphere-command-lance', 'BT-098', 'BattleTech: Inner Sphere Command Lance', decimal.Decimal('34.99'), 'https://store.catalystgamelabs.com/cdn/shop/products/ForcePackISCommandLance.png?v=1615233031', 'https://store.catalystgamelabs.com/products/battletech-forcepack-inner-sphere?_pos=1&_fid=715e41335&_ss=c', 'BattleTech Inner Sphere Command Lance'),
    ('battletech-inner-sphere-battle-lance', 'BT-099', 'BattleTech: Inner Sphere Battle Lance', decimal.Decimal('34.99'), 'https://store.catalystgamelabs.com/cdn/shop/products/ForcePackISCommandLance.png?v=1615233031', 'https://store.catalystgamelabs.com/products/battletech-forcepack-inner-sphere?_pos=1&_fid=715e41335&_ss=c', 'BattleTech Inner Sphere Battle Lance'),
    ('battletech-inner-sphere-direct-fire-lance', 'BT-100', 'BattleTech: Inner Sphere Direct Fire Lance', decimal.Decimal('34.99'), 'https://store.catalystgamelabs.com/cdn/shop/products/ForcePackISCommandLance.png?v=1615233031', 'https://store.catalystgamelabs.com/products/battletech-forcepack-inner-sphere?_pos=1&_fid=715e41335&_ss=c', 'BattleTech Inner Sphere Direct Fire Lance'),
    ('battletech-inner-sphere-heavy-lance', 'BT-101', 'BattleTech: Inner Sphere Heavy Lance', decimal.Decimal('34.99'), 'https://store.catalystgamelabs.com/cdn/shop/products/ForcePackISCommandLance.png?v=1615233031', 'https://store.catalystgamelabs.com/products/battletech-forcepack-inner-sphere?_pos=1&_fid=715e41335&_ss=c', 'BattleTech Inner Sphere Heavy Lance'),
    ('battletech-inner-sphere-striker-lance', 'BT-102', 'BattleTech: Inner Sphere Striker Lance', decimal.Decimal('34.99'), 'https://store.catalystgamelabs.com/cdn/shop/products/ForcePackISCommandLance.png?v=1615233031', 'https://store.catalystgamelabs.com/products/battletech-forcepack-inner-sphere?_pos=1&_fid=715e41335&_ss=c', 'BattleTech Inner Sphere Striker Lance'),
    ('battletech-inner-sphere-fire-lance', 'BT-103', 'BattleTech: Inner Sphere Fire Lance', decimal.Decimal('34.99'), 'https://store.catalystgamelabs.com/cdn/shop/products/ForcePackISCommandLance.png?v=1615233031', 'https://store.catalystgamelabs.com/products/battletech-forcepack-inner-sphere?_pos=1&_fid=715e41335&_ss=c', 'BattleTech Inner Sphere Fire Lance'),
    ('battletech-inner-sphere-heavy-battle-lance', 'BT-104', 'BattleTech: Inner Sphere Heavy Battle Lance', decimal.Decimal('34.99'), 'https://store.catalystgamelabs.com/cdn/shop/products/ForcePackISCommandLance.png?v=1615233031', 'https://store.catalystgamelabs.com/products/battletech-forcepack-inner-sphere?_pos=1&_fid=715e41335&_ss=c', 'BattleTech Inner Sphere Heavy Battle Lance'),
    ('battletech-inner-sphere-urban-lance', 'BT-105', 'BattleTech: Inner Sphere Urban Lance', decimal.Decimal('34.99'), 'https://store.catalystgamelabs.com/cdn/shop/products/ForcePackISCommandLance.png?v=1615233031', 'https://store.catalystgamelabs.com/products/battletech-forcepack-inner-sphere?_pos=1&_fid=715e41335&_ss=c', 'BattleTech Inner Sphere Urban Lance'),
    ('battletech-inner-sphere-support-lance', 'BT-106', 'BattleTech: Inner Sphere Support Lance', decimal.Decimal('34.99'), 'https://store.catalystgamelabs.com/cdn/shop/products/ForcePackISCommandLance.png?v=1615233031', 'https://store.catalystgamelabs.com/products/battletech-forcepack-inner-sphere?_pos=1&_fid=715e41335&_ss=c', 'BattleTech Inner Sphere Support Lance'),
    # BT-107 to BT-115: Clan Stars + Elementals, split out of the former
    # BT-002 "ForcePacks: Clan" bundle (removed 2026-07-10).
    ('battletech-clan-command-star', 'BT-107', 'BattleTech: Clan Command Star', decimal.Decimal('39.99'), 'https://store.catalystgamelabs.com/cdn/shop/products/ForcePackClanCommandStar.png?v=1613413030', 'https://store.catalystgamelabs.com/products/battletech-forcepack-clan?_pos=2&_fid=715e41335&_ss=c', 'BattleTech Clan Command Star'),
    ('battletech-clan-heavy-striker-star', 'BT-108', 'BattleTech: Clan Heavy Striker Star', decimal.Decimal('39.99'), 'https://store.catalystgamelabs.com/cdn/shop/products/ForcePackClanCommandStar.png?v=1613413030', 'https://store.catalystgamelabs.com/products/battletech-forcepack-clan?_pos=2&_fid=715e41335&_ss=c', 'BattleTech Clan Heavy Striker Star'),
    ('battletech-clan-fire-star', 'BT-109', 'BattleTech: Clan Fire Star', decimal.Decimal('39.99'), 'https://store.catalystgamelabs.com/cdn/shop/products/ForcePackClanCommandStar.png?v=1613413030', 'https://store.catalystgamelabs.com/products/battletech-forcepack-clan?_pos=2&_fid=715e41335&_ss=c', 'BattleTech Clan Fire Star'),
    ('battletech-clan-heavy-star', 'BT-110', 'BattleTech: Clan Heavy Star', decimal.Decimal('39.99'), 'https://store.catalystgamelabs.com/cdn/shop/products/ForcePackClanCommandStar.png?v=1613413030', 'https://store.catalystgamelabs.com/products/battletech-forcepack-clan?_pos=2&_fid=715e41335&_ss=c', 'BattleTech Clan Heavy Star'),
    ('battletech-clan-support-star', 'BT-111', 'BattleTech: Clan Support Star', decimal.Decimal('39.99'), 'https://store.catalystgamelabs.com/cdn/shop/products/ForcePackClanCommandStar.png?v=1613413030', 'https://store.catalystgamelabs.com/products/battletech-forcepack-clan?_pos=2&_fid=715e41335&_ss=c', 'BattleTech Clan Support Star'),
    ('battletech-clan-heavy-battle-star', 'BT-112', 'BattleTech: Clan Heavy Battle Star', decimal.Decimal('39.99'), 'https://store.catalystgamelabs.com/cdn/shop/products/ForcePackClanCommandStar.png?v=1613413030', 'https://store.catalystgamelabs.com/products/battletech-forcepack-clan?_pos=2&_fid=715e41335&_ss=c', 'BattleTech Clan Heavy Battle Star'),
    ('battletech-clan-striker-star', 'BT-113', 'BattleTech: Clan Striker Star', decimal.Decimal('39.99'), 'https://store.catalystgamelabs.com/cdn/shop/products/ForcePackClanCommandStar.png?v=1613413030', 'https://store.catalystgamelabs.com/products/battletech-forcepack-clan?_pos=2&_fid=715e41335&_ss=c', 'BattleTech Clan Striker Star'),
    ('battletech-clan-ad-hoc-star', 'BT-114', 'BattleTech: Clan Ad Hoc Star', decimal.Decimal('39.99'), 'https://store.catalystgamelabs.com/cdn/shop/products/ForcePackClanCommandStar.png?v=1613413030', 'https://store.catalystgamelabs.com/products/battletech-forcepack-clan?_pos=2&_fid=715e41335&_ss=c', 'BattleTech Clan Ad Hoc Star'),
    ('battletech-clan-elementals', 'BT-115', 'BattleTech: Clan Elementals', decimal.Decimal('39.99'), 'https://store.catalystgamelabs.com/cdn/shop/products/ForcePackClanCommandStar.png?v=1613413030', 'https://store.catalystgamelabs.com/products/battletech-forcepack-clan?_pos=2&_fid=715e41335&_ss=c', 'BattleTech Clan Elementals'),
    # BT-116 to BT-117: ComStar, split out of the former BT-009
    # "ForcePacks: ComStar" bundle (removed 2026-07-10).
    ('battletech-comstar-command-level-ii', 'BT-116', 'BattleTech: ComStar Command Level II', decimal.Decimal('44.99'), 'https://store.catalystgamelabs.com/cdn/shop/products/ComStarCommandLevelII.jpg?v=1635440161', 'https://store.catalystgamelabs.com/products/battletech-forcepacks-comstar?_pos=10&_fid=715e41335&_ss=c', 'BattleTech ComStar Command Level II'),
    ('battletech-comstar-battle-level-ii', 'BT-117', 'BattleTech: ComStar Battle Level II', decimal.Decimal('44.99'), 'https://store.catalystgamelabs.com/cdn/shop/products/ComStarCommandLevelII.jpg?v=1635440162', 'https://store.catalystgamelabs.com/products/battletech-forcepacks-comstar?_pos=10&_fid=715e41335&_ss=c', 'BattleTech ComStar Battle Level II'),
    # BT-118 to BT-119: Mercenaries, split out of the former BT-020
    # "ForcePacks: Mercenaries" bundle (removed 2026-07-10).
    ('battletech-mercenaries-wolf-dragoons-assault-star', 'BT-118', 'BattleTech: Mercenaries Wolf Dragoon\'s Assault Star', decimal.Decimal('39.99'), 'https://store.catalystgamelabs.com/cdn/shop/products/WolfsDragoonsAssaultStar.jpg?v=1656602212', 'https://store.catalystgamelabs.com/products/battletech-forcepacks-wolfs-dragoons?_pos=21&_fid=715e41335&_ss=c', 'Battletech Wolf\'s Dragoon Assault Star Mech Pack'),
    ('battletech-mercenaries-snords-irregulars-assault-lance', 'BT-119', 'BattleTech: Mercenaries Snord\'s Irregulars Assault Lance', decimal.Decimal('39.99'), 'https://store.catalystgamelabs.com/cdn/shop/products/WolfsDragoonsAssaultStar.jpg?v=1656602213', 'https://store.catalystgamelabs.com/products/battletech-forcepacks-wolfs-dragoons?_pos=21&_fid=715e41335&_ss=c', 'Battletech Snord\'s Irregulars Assault Lance'),
]


class Command(BaseCommand):
    """Populate the BattleTech product line (idempotent)."""

    help = 'Populates BattleTech products (114 SKUs; BT-001/002/005/009/020 retired, BT-098-119 added).'

    def handle(self, *args, **options):
        category, _ = Category.objects.get_or_create(
            slug='battletech',
            defaults={'name': 'Battletech'},
        )

        catalyst, _ = Retailer.objects.get_or_create(
            slug='catalyst-game-labs',
            defaults={
                'name': 'Catalyst Game Labs',
                'website': 'https://store.catalystgamelabs.com',
                'country': 'US',
                'is_active': True,
                'is_uk': False,
            },
        )

        products_created = 0
        products_updated = 0
        prices_created = 0
        prices_updated = 0

        for slug, gw_sku, name, msrp, image_url, product_url, ebay_search_name in PRODUCTS:
            product, created = Product.objects.update_or_create(
                slug=slug,
                defaults={
                    'gw_sku': gw_sku,
                    'name': name,
                    'category': category,
                    'msrp': msrp,
                    'image_url': image_url,
                    'gw_url': product_url,
                    'ebay_search_name': ebay_search_name,
                    # "&" is a common word in BattleTech ForcePack/BattleMat names
                    # (e.g. "Battle & Fire Lances") -- without this, the eBay
                    # bundle-listing filter rejects every otherwise-valid result.
                    'ebay_allowed_title_words': '&',
                    'batch_tag': 'battletech',
                    'is_active': True,
                },
            )
            if created:
                products_created += 1
            else:
                products_updated += 1

            _, price_created = CurrentPrice.objects.update_or_create(
                product=product,
                retailer=catalyst,
                defaults={
                    'price': msrp,
                    'url': product_url,
                    'in_stock': True,
                    'not_available': False,
                },
            )
            if price_created:
                prices_created += 1
            else:
                prices_updated += 1

        self.stdout.write(self.style.SUCCESS(
            f'Products: {products_created} created, {products_updated} updated.'
        ))
        self.stdout.write(self.style.SUCCESS(
            f'Catalyst Game Labs prices: {prices_created} created, {prices_updated} updated.'
        ))
