"""
Management command: populate_star_wars_legion_products

Creates the Star Wars: Legion product line as a new top-level Category
(no Faction subdivision -- Star Wars: Legion is a standalone game system,
not a multi-faction wargame like 40k/AoS).

MSRP/images/URLs come from Asmodee's own store (store.asmodee.com), not
Games Workshop. This category has no GW retailer row at all -- product.msrp
still drives the site's MSRP/discount reference via the existing fallback in
views.py, since that fallback only looks for a not_available=False GW row
before falling back to product.msrp.

product.gw_url is populated with the Asmodee store product URL (not a real
GW link) -- this enables the "View" button on the product detail page, same
pattern as Marvel Crisis Protocol (product_detail.html shows "View on
Asmodee" for both categories via the same conditional).

Usage:
    python manage.py populate_star_wars_legion_products
"""

import decimal

from django.core.management.base import BaseCommand

from prices.models import CurrentPrice
from products.models import Category, Product, Retailer

_AMP_SKUS = {
    'SWL-010', 'SWL-012', 'SWL-038', 'SWL-040', 'SWL-072', 'SWL-081',
    'SWL-083', 'SWL-088', 'SWL-092', 'SWL-099', 'SWL-104', 'SWL-107',
}

# (slug, gw_sku, name, msrp, image_url, product_url, ebay_search_name)
PRODUCTS = [
    ('star-wars-legion-mandalorian-special-edition-army-box', 'SWL-001', 'Star Wars: Legion - Mandalorian Special Edition Army Box', decimal.Decimal('139.99'), 'https://store.asmodee.com/cdn/shop/files/SWQ150-image0_2000_535x.jpg?v=1776692723', 'https://store.asmodee.com/collections/star-wars-legion/products/star-wars-legion-mandalorian-special-edition-army-box', 'Star Wars: Legion - Mandalorian Special Edition Army Box'),
    ('star-wars-legion-mandalorian-leaders', 'SWL-002', 'Star Wars: Legion - Mandalorian Leaders', decimal.Decimal('52.99'), 'https://store.asmodee.com/cdn/shop/files/SWQ82-image0_2000_535x.jpg?v=1776692231', 'https://store.asmodee.com/collections/star-wars-legion/products/star-wars-legion-mandalorian-leaders', 'Star Wars: Legion - Mandalorian Leaders'),
    ('star-wars-legion-galactic-republic-starter-set', 'SWL-003', 'Star Wars: Legion - Galactic Republic Starter Set', decimal.Decimal('99.99'), 'https://store.asmodee.com/cdn/shop/files/SWQ19-image0_2000_535x.jpg?v=1752242067', 'https://store.asmodee.com/collections/star-wars-legion/products/star-wars-legion-galactic-republic-starter-set', 'Star Wars: Legion - Galactic Republic Starter Set'),
    ('star-wars-legion-customizable-jedi-general-and-knight', 'SWL-004', 'Star Wars: Legion - Customizable Jedi General and Knight', decimal.Decimal('39.99'), 'https://store.asmodee.com/cdn/shop/files/SWQ20-image0_2000_535x.jpg?v=1752241984', 'https://store.asmodee.com/collections/star-wars-legion/products/star-wars-legion-customizable-jedi-general-and-knight', 'Star Wars: Legion - Customizable Jedi General and Knight'),
    ('star-wars-legion-upgrades-card-pack', 'SWL-005', 'Star Wars: Legion - Upgrades Card Pack', decimal.Decimal('29.99'), 'https://store.asmodee.com/cdn/shop/files/SWQ144-image0_2000_535x.jpg?v=1752240833', 'https://store.asmodee.com/collections/star-wars-legion/products/star-wars-legion-upgrades-card-pack', 'Star Wars: Legion - Upgrades Card Pack'),
    ('star-wars-legion-galactic-empire-starter-set', 'SWL-006', 'Star Wars: Legion - Galactic Empire Starter Set', decimal.Decimal('99.99'), 'https://store.asmodee.com/cdn/shop/files/SWQ02-image0_2000_535x.jpg?v=1752242139', 'https://store.asmodee.com/collections/star-wars-legion/products/star-wars-legion-galactic-empire-starter-set', 'Star Wars: Legion - Galactic Empire Starter Set'),
    ('star-wars-legion-general-grievous-tsmeu-6-wheel-bike', 'SWL-007', 'Star Wars: Legion - General Grievous\' TSMEU-6 Wheel Bike', decimal.Decimal('59.99'), 'https://store.asmodee.com/cdn/shop/files/SWQ31-image0_2000_535x.jpg?v=1752240279', 'https://store.asmodee.com/collections/star-wars-legion/products/star-wars-legion-general-grievous-tsmeu-6-wheel-bike', 'Star Wars: Legion - General Grievous\' TSMEU-6 Wheel Bike'),
    ('star-wars-legion-separatist-alliance-starter-set', 'SWL-008', 'Star Wars: Legion - Separatist Alliance Starter Set', decimal.Decimal('99.99'), 'https://store.asmodee.com/cdn/shop/files/SWQ28-image0_2000_535x.jpg?v=1752241659', 'https://store.asmodee.com/collections/star-wars-legion/products/star-wars-legion-separatist-alliance-starter-set', 'Star Wars: Legion - Separatist Alliance Starter Set'),
    ('star-wars-legion-empire-card-pack', 'SWL-009', 'Star Wars: Legion - Empire Card Pack', decimal.Decimal('26.99'), 'https://store.asmodee.com/cdn/shop/files/SWQ06-image0_2000_535x.jpg?v=1751377939', 'https://store.asmodee.com/collections/star-wars-legion/products/star-wars-legion-empire-card-pack', 'Star Wars: Legion - Empire Card Pack'),
    ('star-wars-legion-customizable-imperial-officer-agent', 'SWL-010', 'Star Wars: Legion - Customizable Imperial Officer & Agent', decimal.Decimal('39.99'), 'https://store.asmodee.com/cdn/shop/files/SWQ09-image0_2000_535x.jpg?v=1752241439', 'https://store.asmodee.com/collections/star-wars-legion/products/star-wars-legion-customizable-imperial-officer-agent', 'Star Wars: Legion - Customizable Imperial Officer & Agent'),
    ('star-wars-legion-customizable-super-tactical-command-droid', 'SWL-011', 'Star Wars: Legion - Customizable Super Tactical Command Droid', decimal.Decimal('39.99'), 'https://store.asmodee.com/cdn/shop/files/SWQ29-image0_2000_535x.png?v=1752240707', 'https://store.asmodee.com/collections/star-wars-legion/products/star-wars-legion-customizable-super-tactical-command-droid', 'Star Wars: Legion - Customizable Super Tactical Command Droid'),
    ('star-wars-legion-commander-padawan-ahsoka-tano', 'SWL-012', 'Star Wars: Legion - Commander & Padawan Ahsoka Tano', decimal.Decimal('34.99'), 'https://store.asmodee.com/cdn/shop/files/SWQ22-image0_2000_535x.jpg?v=1741274699', 'https://store.asmodee.com/collections/star-wars-legion/products/star-wars-legion-commander-padawan-ahsoka-tano', 'Star Wars: Legion - Commander & Padawan Ahsoka Tano'),
    ('star-wars-legion-arf-troopers', 'SWL-013', 'Star Wars: Legion - ARF Troopers', decimal.Decimal('57.99'), 'https://store.asmodee.com/cdn/shop/files/SWQ135-image0_2000_0203bb4c-1c0e-43b5-9cc5-6b028478c036_535x.jpg?v=1736876446', 'https://store.asmodee.com/collections/star-wars-legion/products/star-wars-legion-arf-troopers', 'Star Wars: Legion - ARF Troopers'),
    ('star-wars-legion-bad-batch-operative-expansion', 'SWL-014', 'Star Wars: Legion - Bad Batch Operative Expansion', decimal.Decimal('49.99'), 'https://store.asmodee.com/cdn/shop/files/SWL119-image0_2000_535x.jpg?v=1713977553', 'https://store.asmodee.com/collections/star-wars-legion/products/star-wars-legion-bad-batch-operative-expansion', 'Star Wars: Legion - Bad Batch Operative Expansion'),
    ('star-wars-legion-galactic-empire-command-card-pack', 'SWL-015', 'Star Wars: Legion - Galactic Empire Command Card Pack', decimal.Decimal('22.99'), 'https://store.asmodee.com/cdn/shop/files/SWQ156-image0_2000_535x.jpg?v=1751377722', 'https://store.asmodee.com/collections/star-wars-legion/products/star-wars-legion-galactic-empire-command-card-pack', 'Star Wars: Legion - Galactic Empire Command Card Pack'),
    ('star-wars-legion-imperial-high-command', 'SWL-016', 'Star Wars: Legion - Imperial High Command', decimal.Decimal('69.99'), 'https://store.asmodee.com/cdn/shop/files/SWQ42-image0_2000_535x.jpg?v=1769786430', 'https://store.asmodee.com/collections/star-wars-legion/products/star-wars-legion-imperial-high-command', 'Star Wars: Legion - Imperial High Command'),
    ('star-wars-legion-customizable-mandalorian-leader-and-hunter', 'SWL-017', 'Star Wars: Legion - Customizable Mandalorian Leader and Hunter', decimal.Decimal('39.99'), 'https://store.asmodee.com/cdn/shop/files/SWQ152-image0_2000_535x.jpg?v=1780666974', 'https://store.asmodee.com/collections/star-wars-legion/products/star-wars-legion-customizable-mandalorian-leader-and-hunter', 'Star Wars: Legion - Customizable Mandalorian Leader and Hunter'),
    ('star-wars-legion-separatist-alliance-card-pack', 'SWL-018', 'Star Wars: Legion - Separatist Alliance Card Pack', decimal.Decimal('21.99'), 'https://store.asmodee.com/cdn/shop/files/SWQ08-image0_2000_535x.jpg?v=1751377787', 'https://store.asmodee.com/collections/star-wars-legion/products/star-wars-legion-separatist-alliance-card-pack', 'Star Wars: Legion - Separatist Alliance Card Pack'),
    ('star-wars-legion-galactic-republic-command-card-pack', 'SWL-019', 'Star Wars: Legion - Galactic Republic Command Card Pack', decimal.Decimal('17.99'), 'https://store.asmodee.com/cdn/shop/files/SWQ157-image0_2000_535x.jpg?v=1751377649', 'https://store.asmodee.com/collections/star-wars-legion/products/star-wars-legion-galactic-republic-command-card-pack', 'Star Wars: Legion - Galactic Republic Command Card Pack'),
    ('star-wars-legion-mercenary-card-pack', 'SWL-020', 'Star Wars: Legion - Mercenary Card Pack', decimal.Decimal('22.99'), 'https://store.asmodee.com/cdn/shop/files/SWQ04-image0_2000_535x.jpg?v=1751378080', 'https://store.asmodee.com/collections/star-wars-legion/products/star-wars-legion-mercenary-card-pack', 'Star Wars: Legion - Mercenary Card Pack'),
    ('star-wars-legion-fifth-brother-and-seventh-sister-operative-expansion', 'SWL-021', 'Star Wars: Legion - Fifth Brother and Seventh Sister Operative Expansion', decimal.Decimal('29.99'), 'https://store.asmodee.com/cdn/shop/files/SWL113-image0_2000_535x.jpg?v=1704295310', 'https://store.asmodee.com/collections/star-wars-legion/products/star-wars-legion-fifth-brother-and-seventh-sister-operative-expansion', 'Star Wars: Legion - Fifth Brother and Seventh Sister Operative Expansion'),
    ('star-wars-legion-mandalorian-warriors', 'SWL-022', 'Star Wars: Legion - Mandalorian Warriors', decimal.Decimal('62.99'), 'https://store.asmodee.com/cdn/shop/files/SWQ81-image0_2000_535x.jpg?v=1779812341', 'https://store.asmodee.com/collections/star-wars-legion/products/star-wars-legion-mandalorian-warriors', 'Star Wars: Legion - Mandalorian Warriors'),
    ('star-wars-legion-leaders-of-the-shadow-collective', 'SWL-023', 'Star Wars: Legion - Leaders of the Shadow Collective', decimal.Decimal('49.99'), 'https://store.asmodee.com/cdn/shop/files/SWQ77-image0_2000_535x.jpg?v=1775072818', 'https://store.asmodee.com/collections/star-wars-legion/products/star-wars-legion-leaders-of-the-shadow-collective', 'Star Wars: Legion - Leaders of the Shadow Collective'),
    ('star-wars-legion-mandalorian-super-commandos', 'SWL-024', 'Star Wars: Legion - Mandalorian Super Commandos', decimal.Decimal('49.99'), 'https://store.asmodee.com/cdn/shop/files/SWQ69-image0_2000_535x.jpg?v=1776692412', 'https://store.asmodee.com/collections/star-wars-legion/products/star-wars-legion-mandalorian-super-commandos-1', 'Star Wars: Legion - Mandalorian Super Commandos'),
    ('star-wars-legion-upgrades-card-pack-2', 'SWL-025', 'Star Wars: Legion - Upgrades Card Pack 2', decimal.Decimal('19.99'), 'https://store.asmodee.com/cdn/shop/files/SWQ214-image0_2000_535x.jpg?v=1781117754', 'https://store.asmodee.com/collections/star-wars-legion/products/star-wars-legion-upgrades-card-pack-2', 'Star Wars: Legion - Upgrades Card Pack 2'),
    ('star-wars-legion-sun-fac-and-poggle-the-lesser-operative-and-commander-expansion', 'SWL-026', 'Star Wars: Legion - Sun Fac and Poggle the Lesser Operative and Commander Expansion', decimal.Decimal('29.99'), 'https://store.asmodee.com/cdn/shop/files/SWL116EN-image0_2000_535x.jpg?v=1698937402', 'https://store.asmodee.com/collections/star-wars-legion/products/star-wars-legion-sun-fac-poogle-the-lesser-commander-expansion', 'Star Wars: Legion - Sun Fac and Poggle the Lesser Operative and Commander Expansion'),
    ('star-wars-legion-stormtroopers', 'SWL-027', 'Star Wars: Legion - Stormtroopers', decimal.Decimal('54.99'), 'https://store.asmodee.com/cdn/shop/files/SWQ11-image0_2000_535x.jpg?v=1741275130', 'https://store.asmodee.com/collections/star-wars-legion/products/star-wars-legion-stormtroopers', 'Star Wars: Legion - Stormtroopers'),
    ('star-wars-legion-tx-130-saber-tank', 'SWL-028', 'Star Wars: Legion - TX-130 Saber Tank', decimal.Decimal('69.99'), 'https://store.asmodee.com/cdn/shop/files/SWQ27-image0_2000_535x.jpg?v=1763414340', 'https://store.asmodee.com/collections/star-wars-legion/products/star-wars-legion-tx-130-saber-tank', 'Star Wars: Legion - TX-130 Saber Tank'),
    ('star-wars-legion-heroes-of-the-rebellion-character-pack', 'SWL-029', 'Star Wars: Legion - Heroes of the Rebellion Character Pack', decimal.Decimal('69.99'), 'https://store.asmodee.com/cdn/shop/files/SWQ14-image0_2000_535x.jpg?v=1752240922', 'https://store.asmodee.com/collections/star-wars-legion/products/star-wars-legion-heroes-of-the-rebellion-character-pack', 'Star Wars: Legion - Heroes of the Rebellion Character Pack'),
    ('star-wars-legion-rebel-troopers', 'SWL-030', 'Star Wars: Legion - Rebel Troopers', decimal.Decimal('54.99'), 'https://store.asmodee.com/cdn/shop/files/SWQ15-image0_2000_535x.jpg?v=1741356678', 'https://store.asmodee.com/collections/star-wars-legion/products/star-wars-legion-rebel-troopers', 'Star Wars: Legion - Rebel Troopers'),
    ('star-wars-legion-3d-objective-tokens', 'SWL-031', 'Star Wars: Legion - 3D Objective Tokens', decimal.Decimal('44.99'), 'https://store.asmodee.com/cdn/shop/files/SWQ102-image0_2000_535x.jpg?v=1752241385', 'https://store.asmodee.com/collections/star-wars-legion/products/star-wars-legion-3d-objective-tokens', 'Star Wars: Legion - 3D Objective Tokens'),
    ('star-wars-legion-b2-super-rocket-battle-droids', 'SWL-032', 'Star Wars: Legion - B2 Super Rocket Battle Droids', decimal.Decimal('57.99'), 'https://store.asmodee.com/cdn/shop/files/SWQ154-image0_2000_535x.jpg?v=1783967141', 'https://store.asmodee.com/collections/star-wars-legion/products/star-wars-legion-b2-super-rocket-battle-droids', 'Star Wars: Legion - B2 Super Rocket Battle Droids'),
    ('star-wars-legion-republic-at-rt', 'SWL-033', 'Star Wars: Legion - Republic AT-RT', decimal.Decimal('34.99'), 'https://store.asmodee.com/cdn/shop/files/SWQ198-image0_2000_535x.jpg?v=1767990388', 'https://store.asmodee.com/collections/star-wars-legion/products/star-wars-legion-republic-at-rt', 'Star Wars: Legion - Republic AT-RT'),
    ('star-wars-legion-leaders-of-the-separatist-alliance', 'SWL-034', 'Star Wars: Legion - Leaders of the Separatist Alliance', decimal.Decimal('62.99'), 'https://store.asmodee.com/cdn/shop/files/SWQ49-image0_2000_535x.png?v=1783966791', 'https://store.asmodee.com/collections/star-wars-legion/products/star-wars-legion-leaders-of-the-separatist-alliance', 'Star Wars: Legion - Leaders of the Separatist Alliance'),
    ('star-wars-legion-bx-series-droid-commandos', 'SWL-035', 'Star Wars: Legion - BX-Series Droid Commandos', decimal.Decimal('49.99'), 'https://store.asmodee.com/cdn/shop/files/SWQ52-image0_2000_535x.jpg?v=1767990479', 'https://store.asmodee.com/collections/star-wars-legion/products/star-wars-legion-bx-series-droid-commandos', 'Star Wars: Legion - BX-Series Droid Commandos'),
    ('star-wars-legion-arc-troopers-unit-expansion', 'SWL-036', 'Star Wars: Legion - ARC Troopers Unit Expansion', decimal.Decimal('54.99'), 'https://store.asmodee.com/cdn/shop/files/SWQ133-image0_2000_535x.jpg?v=1752600637', 'https://store.asmodee.com/collections/star-wars-legion/products/star-wars-legion-arc-troopers-unit-expansion', 'Star Wars: Legion - ARC Troopers Unit Expansion'),
    ('star-wars-legion-imperial-death-troopers', 'SWL-037', 'Star Wars: Legion - Imperial Death Troopers', decimal.Decimal('39.99'), 'https://store.asmodee.com/cdn/shop/files/SWQ205-image0_2000_535x.png?v=1772815075', 'https://store.asmodee.com/collections/star-wars-legion/products/star-wars-legion-imperial-death-troopers-1', 'Star Wars: Legion - Imperial Death Troopers'),
    ('star-wars-legion-darth-vader-general-veers-character-expansion', 'SWL-038', 'Star Wars: Legion - Darth Vader & General Veers Character Expansion', decimal.Decimal('34.99'), 'https://store.asmodee.com/cdn/shop/files/SWQ103-image0_2000_535x.jpg?v=1752241321', 'https://store.asmodee.com/collections/star-wars-legion/products/star-wars-legion-darth-vader-general-veers-character-expansion', 'Star Wars: Legion - Darth Vader & General Veers Character Expansion'),
    ('star-wars-legion-clone-commander-cody', 'SWL-039', 'Star Wars: Legion - Clone Commander Cody', decimal.Decimal('39.99'), 'https://store.asmodee.com/cdn/shop/files/SWQ72-image0_2000_535x.jpg?v=1741270638', 'https://store.asmodee.com/collections/star-wars-legion/products/star-wars-legion-clone-commander-cody', 'Star Wars: Legion - Clone Commander Cody'),
    ('star-wars-legion-rogues-rebels', 'SWL-040', 'Star Wars: Legion - Rogues & Rebels', decimal.Decimal('54.99'), 'https://store.asmodee.com/cdn/shop/files/SWQ50-image0_2000_535x.jpg?v=1778861626', 'https://store.asmodee.com/collections/star-wars-legion/products/star-wars-legion-rogues-rebels', 'Star Wars: Legion - Rogues & Rebels'),
    ('star-wars-legion-outer-rim-outlaws', 'SWL-041', 'Star Wars: Legion - Outer Rim Outlaws', decimal.Decimal('39.99'), 'https://store.asmodee.com/cdn/shop/files/SWQ138-image0_2000_535x.jpg?v=1744817050', 'https://store.asmodee.com/collections/star-wars-legion/products/star-wars-legion-outer-rim-outlaws', 'Star Wars: Legion - Outer Rim Outlaws'),
    ('star-wars-legion-scout-troopers', 'SWL-042', 'Star Wars: Legion - Scout Troopers', decimal.Decimal('52.99'), 'https://store.asmodee.com/cdn/shop/files/SWQ12-image0_2000_535x.jpg?v=1741274979', 'https://store.asmodee.com/collections/star-wars-legion/products/star-wars-legion-scout-troopers-1', 'Star Wars: Legion - Scout Troopers'),
    ('star-wars-legion-imperial-shoretroopers', 'SWL-043', 'Star Wars: Legion - Imperial Shoretroopers', decimal.Decimal('49.99'), 'https://store.asmodee.com/cdn/shop/files/SWQ199-image0_2000_535x.jpg?v=1765464462', 'https://store.asmodee.com/collections/star-wars-legion/products/star-wars-legion-imperial-shoretroopers-1', 'Star Wars: Legion - Imperial Shoretroopers'),
    ('star-wars-legion-geonosian-warriors-unit-expansion', 'SWL-044', 'Star Wars: Legion - Geonosian Warriors Unit Expansion', decimal.Decimal('54.99'), 'https://store.asmodee.com/cdn/shop/files/SWQ37-image0_2000_535x.jpg?v=1738941249', 'https://store.asmodee.com/collections/star-wars-legion/products/star-wars-legion-geonosian-warriors-unit-expansion-1', 'Star Wars: Legion - Geonosian Warriors Unit Expansion'),
    ('star-wars-legion-ahsoka-tano-operative-expansion', 'SWL-045', 'Star Wars: Legion - Ahsoka Tano Operative Expansion', decimal.Decimal('21.99'), 'https://store.asmodee.com/cdn/shop/files/SWL106-image0_2000_535x.jpg?v=1690987913', 'https://store.asmodee.com/collections/star-wars-legion/products/star-wars-legion-ahsoka-tano-operative-expansion', 'Star Wars: Legion - Ahsoka Tano Operative Expansion'),
    ('star-wars-legion-republic-specialists', 'SWL-046', 'Star Wars: Legion - Republic Specialists', decimal.Decimal('39.99'), 'https://store.asmodee.com/cdn/shop/files/SWQ200-image0_2000_535x.png?v=1775072070', 'https://store.asmodee.com/collections/star-wars-legion/products/star-wars-legion-republic-specialists', 'Star Wars: Legion - Republic Specialists'),
    ('star-wars-legion-outer-rim-battles-terrain-pack', 'SWL-047', 'Star Wars: Legion - Outer Rim Battles Terrain Pack', decimal.Decimal('59.99'), 'https://store.asmodee.com/cdn/shop/files/SWQ137-image0_2000_535x.jpg?v=1736438285', 'https://store.asmodee.com/collections/star-wars-legion/products/star-wars-legion-outer-rim-battles-terrain-pack', 'Star Wars: Legion - Outer Rim Battles Terrain Pack'),
    ('star-wars-legion-galactic-bounty-hunters', 'SWL-048', 'Star Wars: Legion - Galactic Bounty Hunters', decimal.Decimal('39.99'), 'https://store.asmodee.com/cdn/shop/files/SWQ44-image0_2000_535x.jpg?v=1781117335', 'https://store.asmodee.com/collections/star-wars-legion/products/star-wars-legion-galactic-bounty-hunters', 'Star Wars: Legion - Galactic Bounty Hunters'),
    ('star-wars-legion-dsd1-dwarf-spider-droid', 'SWL-049', 'Star Wars: Legion - DSD1 Dwarf Spider Droid', decimal.Decimal('29.99'), 'https://store.asmodee.com/cdn/shop/files/SWQ61-image0_2000_535x.jpg?v=1768336866', 'https://store.asmodee.com/collections/star-wars-legion/products/star-wars-legion-dsd1-dwarf-spider-droid', 'Star Wars: Legion - DSD1 Dwarf Spider Droid'),
    ('star-wars-legion-ig-100-magnaguards', 'SWL-050', 'Star Wars: Legion - IG-100 Magnaguards', decimal.Decimal('39.99'), 'https://store.asmodee.com/cdn/shop/files/SWQ58-image0_2000_535x.jpg?v=1765463333', 'https://store.asmodee.com/collections/star-wars-legion/products/star-wars-legion-ig-100-magnaguards', 'Star Wars: Legion - IG-100 Magnaguards'),
    ('star-wars-legion-aat-battle-tank', 'SWL-051', 'Star Wars: Legion - AAT Battle Tank', decimal.Decimal('69.99'), 'https://store.asmodee.com/cdn/shop/files/SWQ33-image0_2000_535x.jpg?v=1763414277', 'https://store.asmodee.com/collections/star-wars-legion/products/star-wars-legion-aat-battle-tank', 'Star Wars: Legion - AAT Battle Tank'),
    ('star-wars-legion-e-web-heavy-blaster-team', 'SWL-052', 'Star Wars: Legion - E-Web Heavy Blaster Team', decimal.Decimal('39.99'), 'https://store.asmodee.com/cdn/shop/files/SWQ206-image0_2000_535x.png?v=1772814836', 'https://store.asmodee.com/collections/star-wars-legion/products/star-wars-legion-e-web-heavy-blaster-team', 'Star Wars: Legion - E-Web Heavy Blaster Team'),
    ('star-wars-legion-legion-attack-dice-pack', 'SWL-053', 'Star Wars: Legion - Legion Attack Dice Pack', decimal.Decimal('17.99'), 'https://store.asmodee.com/cdn/shop/files/SWQ131-image0_2000_535x.jpg?v=1720624663', 'https://store.asmodee.com/collections/star-wars-legion/products/star-wars-legion-legion-attack-dice-pack', 'Star Wars: Legion - Legion Attack Dice Pack'),
    ('star-wars-legion-sabine-wren', 'SWL-054', 'Star Wars: Legion - Sabine Wren', decimal.Decimal('19.99'), 'https://store.asmodee.com/cdn/shop/files/swl37-0_535x.png?v=1690989597', 'https://store.asmodee.com/collections/star-wars-legion/products/star-wars-legion-sabine-wren', 'Star Wars: Legion - Sabine Wren'),
    ('star-wars-legion-clone-troopers-infantry', 'SWL-055', 'Star Wars: Legion - Clone Troopers Infantry', decimal.Decimal('54.99'), 'https://store.asmodee.com/cdn/shop/files/SWQ24-image0_2000_535x.jpg?v=1752241778', 'https://store.asmodee.com/collections/star-wars-legion/products/star-wars-legion-clone-troopers-infantry', 'Star Wars: Legion - Clone Troopers Infantry'),
    ('star-wars-legion-rebel-commandos', 'SWL-056', 'Star Wars: Legion - Rebel Commandos', decimal.Decimal('52.99'), 'https://store.asmodee.com/cdn/shop/files/SWQ16-image0_2000_535x.jpg?v=1741356534', 'https://store.asmodee.com/collections/star-wars-legion/products/star-wars-legion-rebel-commandos-1', 'Star Wars: Legion - Rebel Commandos'),
    ('star-wars-legion-upgrade-card-pack', 'SWL-057', 'Star Wars: Legion - Upgrade Card Pack', decimal.Decimal('9.95'), 'https://store.asmodee.com/cdn/shop/files/swl51-0_535x.png?v=1691000387', 'https://store.asmodee.com/collections/star-wars-legion/products/star-wars-legion-upgrade-card-pack', 'Star Wars: Legion - Upgrade Card Pack'),
    ('star-wars-legion-t-47-airspeeder', 'SWL-058', 'Star Wars: Legion - T-47 Airspeeder', decimal.Decimal('39.99'), 'https://store.asmodee.com/cdn/shop/files/SWQ17-image0_2000_535x.jpg?v=1765464698', 'https://store.asmodee.com/collections/star-wars-legion/products/star-wars-legion-t-47-airspeeder', 'Star Wars: Legion - T-47 Airspeeder'),
    ('star-wars-legion-at-st-walker-expansion', 'SWL-059', 'Star Wars: Legion - AT-ST Walker Expansion', decimal.Decimal('64.99'), 'https://store.asmodee.com/cdn/shop/files/SWL138-image0_2000_535x.jpg?v=1690988427', 'https://store.asmodee.com/collections/star-wars-legion/products/star-wars-legion-at-st-walker-expansion', 'Star Wars: Legion - AT-ST Walker Expansion'),
    ('star-wars-legion-imperial-special-forces', 'SWL-060', 'Star Wars: Legion - Imperial Special Forces', decimal.Decimal('39.99'), 'https://store.asmodee.com/cdn/shop/files/SWQ53-image0_2000_535x.jpg?v=1767990704', 'https://store.asmodee.com/collections/star-wars-legion/products/star-wars-legion-imperial-special-forces', 'Star Wars: Legion - Imperial Special Forces'),
    ('star-wars-legion-ewok-warriors', 'SWL-061', 'Star Wars: Legion - Ewok Warriors', decimal.Decimal('49.99'), 'https://store.asmodee.com/cdn/shop/files/SWQ73-image0_2000_535x.jpg?v=1765462798', 'https://store.asmodee.com/collections/star-wars-legion/products/star-wars-legion-ewok-warriors', 'Star Wars: Legion - Ewok Warriors'),
    ('star-wars-legion-essentials-pack', 'SWL-062', 'Star Wars: Legion - Essentials Pack', decimal.Decimal('29.99'), 'https://store.asmodee.com/cdn/shop/files/SWQ03-image0_2000_535x.jpg?v=1773328140', 'https://store.asmodee.com/collections/star-wars-legion/products/star-wars-legion-essentials-pack', 'Star Wars: Legion - Essentials Pack'),
    ('star-wars-legion-dark-troopers', 'SWL-063', 'Star Wars: Legion - Dark Troopers', decimal.Decimal('59.99'), 'https://store.asmodee.com/cdn/shop/files/SWQ63-image0_2000_535x.jpg?v=1765463044', 'https://store.asmodee.com/collections/star-wars-legion/products/star-wars-legion-dark-troopers', 'Star Wars: Legion - Dark Troopers'),
    ('star-wars-legion-74-z-speeder-bike', 'SWL-064', 'Star Wars: Legion - 74-Z Speeder Bike', decimal.Decimal('39.99'), 'https://store.asmodee.com/cdn/shop/files/SWQ207-image0_2000_535x.png?v=1772814670', 'https://store.asmodee.com/collections/star-wars-legion/products/star-wars-legion-74-z-speeder-bike', 'Star Wars: Legion - 74-Z Speeder Bike'),
    ('star-wars-legion-fleet-troopers-unit', 'SWL-065', 'Star Wars: Legion - Fleet Troopers Unit', decimal.Decimal('57.99'), 'https://store.asmodee.com/cdn/shop/files/SWQ197-image0_2000_535x.jpg?v=1772815149', 'https://store.asmodee.com/collections/star-wars-legion/products/star-wars-legion-fleet-troopers-unit', 'Star Wars: Legion - Fleet Troopers Unit'),
    ('star-wars-legion-a-a5-speeder-truck', 'SWL-066', 'Star Wars: Legion - A-A5 Speeder Truck', decimal.Decimal('74.99'), 'https://store.asmodee.com/cdn/shop/files/SWQ92-image0_2000_535x.jpg?v=1752240091', 'https://store.asmodee.com/collections/star-wars-legion/products/star-wars-legion-a-a5-speeder-truck-1', 'Star Wars: Legion - A-A5 Speeder Truck'),
    ('star-wars-legion-legion-defense-dice-pack', 'SWL-067', 'Star Wars: Legion - Legion Defense Dice Pack', decimal.Decimal('17.99'), 'https://store.asmodee.com/cdn/shop/files/SWQ132-image0_2000_535x.jpg?v=1720624773', 'https://store.asmodee.com/collections/star-wars-legion/products/star-wars-legion-legion-defense-dice-pack', 'Star Wars: Legion - Legion Defense Dice Pack'),
    ('star-wars-legion-b1-battle-droids', 'SWL-068', 'Star Wars: Legion - B1 Battle Droids', decimal.Decimal('54.99'), 'https://store.asmodee.com/cdn/shop/files/SWQ30-image0_2000_535x.png?v=1752240609', 'https://store.asmodee.com/collections/star-wars-legion/products/star-wars-legion-b1-battle-droids-1', 'Star Wars: Legion - B1 Battle Droids'),
    ('star-wars-legion-asajj-ventress-operative-expansion', 'SWL-069', 'Star Wars: Legion - Asajj Ventress Operative Expansion', decimal.Decimal('21.99'), 'https://store.asmodee.com/cdn/shop/files/SWL108-image0_2000_535x.jpg?v=1690988006', 'https://store.asmodee.com/collections/star-wars-legion/products/star-wars-legion-asajj-ventress-operative-expansion', 'Star Wars: Legion - Asajj Ventress Operative Expansion'),
    ('star-wars-legion-tauntaun-riders', 'SWL-070', 'Star Wars: Legion - Tauntaun Riders', decimal.Decimal('49.99'), 'https://store.asmodee.com/cdn/shop/files/SWQ40-image0_2000_535x.jpg?v=1769786582', 'https://store.asmodee.com/collections/star-wars-legion/products/star-wars-legion-tauntaun-riders', 'Star Wars: Legion - Tauntaun Riders'),
    ('star-wars-legion-moff-gideon-commander-expansion', 'SWL-071', 'Star Wars: Legion - Moff Gideon Commander Expansion', decimal.Decimal('19.99'), 'https://store.asmodee.com/cdn/shop/files/SWL102-image0_2000_535x.jpg?v=1690987649', 'https://store.asmodee.com/collections/star-wars-legion/products/star-wars-legion-moff-gideon-commander-expansion', 'Star Wars: Legion - Moff Gideon Commander Expansion'),
    ('star-wars-legion-cassian-andor-jyn-erso-k-2so', 'SWL-072', 'Star Wars: Legion - Cassian Andor, Jyn Erso & K-2SO', decimal.Decimal('34.99'), 'https://store.asmodee.com/cdn/shop/files/SWQ39-image0_2000_535x.png?v=1763414115', 'https://store.asmodee.com/collections/star-wars-legion/products/star-wars-legion-cassian-andor-jyn-erso-k-2so', 'Star Wars: Legion - Cassian Andor, Jyn Erso & K-2SO'),
    ('star-wars-legion-leaders-of-the-republic', 'SWL-073', 'Star Wars: Legion - Leaders of the Republic', decimal.Decimal('34.99'), 'https://store.asmodee.com/cdn/shop/files/SWQ46-image0_2000_535x.jpg?v=1781116628', 'https://store.asmodee.com/collections/star-wars-legion/products/star-wars-legion-leaders-of-the-republic', 'Star Wars: Legion - Leaders of the Republic'),
    ('star-wars-legion-x-34-landspeeder', 'SWL-074', 'Star Wars: Legion - X-34 Landspeeder', decimal.Decimal('34.99'), 'https://store.asmodee.com/cdn/shop/files/SWQ202-image0_2000_535x.jpg?v=1778862439', 'https://store.asmodee.com/collections/star-wars-legion/products/star-wars-legion-x-34-landspeeder-1', 'Star Wars: Legion - X-34 Landspeeder'),
    ('star-wars-legion-imperial-specialists', 'SWL-075', 'Star Wars: Legion - Imperial Specialists', decimal.Decimal('39.99'), 'https://store.asmodee.com/cdn/shop/files/SWQ192-image0_2000_535x.png?v=1775071713', 'https://store.asmodee.com/collections/star-wars-legion/products/star-wars-legion-imperial-specialists-1', 'Star Wars: Legion - Imperial Specialists'),
    ('star-wars-legion-agents-of-the-empire', 'SWL-076', 'Star Wars: Legion - Agents of the Empire', decimal.Decimal('39.99'), 'https://store.asmodee.com/cdn/shop/files/SWQ203-image0_2000_535x.jpg?v=1781118314', 'https://store.asmodee.com/collections/star-wars-legion/products/star-wars-legion-agents-of-the-empire', 'Star Wars: Legion - Agents of the Empire'),
    ('star-wars-legion-ig-series-assassin-droids', 'SWL-077', 'Star Wars: Legion - IG-Series Assassin Droids', decimal.Decimal('34.99'), 'https://store.asmodee.com/cdn/shop/files/SWQ139-image0_2000_535x.jpg?v=1744815049', 'https://store.asmodee.com/collections/star-wars-legion/products/star-wars-legion-ig-series-assassin-droids-1', 'Star Wars: Legion - IG-Series Assassin Droids'),
    ('star-wars-legion-bad-batch', 'SWL-078', 'Star Wars: Legion - Bad Batch', decimal.Decimal('59.99'), 'https://store.asmodee.com/cdn/shop/files/SWQ90-image0_2000_535x.jpg?v=1778593437', 'https://store.asmodee.com/collections/star-wars-legion/products/star-wars-legion-bad-batch', 'Star Wars: Legion - Bad Batch'),
    ('star-wars-legion-separatist-specialists', 'SWL-079', 'Star Wars: Legion - Separatist Specialists', decimal.Decimal('39.99'), 'https://store.asmodee.com/cdn/shop/files/SWQ201-image0_2000_535x.png?v=1775072532', 'https://store.asmodee.com/collections/star-wars-legion/products/star-wars-legion-separatist-specialists', 'Star Wars: Legion - Separatist Specialists'),
    ('star-wars-legion-super-tactical-droid-commanders', 'SWL-080', 'Star Wars: Legion - Super Tactical Droid Commanders', decimal.Decimal('34.99'), 'https://store.asmodee.com/cdn/shop/files/SWQ38-image0_2000_535x.jpg?v=1765463618', 'https://store.asmodee.com/collections/star-wars-legion/products/star-wars-legion-super-tactical-droid-commanders', 'Star Wars: Legion - Super Tactical Droid Commanders'),
    ('star-wars-legion-r2d2-c-3po', 'SWL-081', 'Star Wars: Legion - R2D2 & C-3PO', decimal.Decimal('34.99'), 'https://store.asmodee.com/cdn/shop/files/SWQ142-image0_2000_535x.jpg?v=1765464965', 'https://store.asmodee.com/collections/star-wars-legion/products/star-wars-legion-r2d2-c-3po', 'Star Wars: Legion - R2D2 & C-3PO'),
    ('star-wars-legion-kashyyyk-wookiee-warriors', 'SWL-082', 'Star Wars: Legion - Kashyyyk Wookiee Warriors', decimal.Decimal('49.99'), 'https://store.asmodee.com/cdn/shop/files/SWQ18-image0_2000_535x.jpg?v=1760024528', 'https://store.asmodee.com/collections/star-wars-legion/products/star-wars-legion-kashyyyk-wookie-warriors', 'Star Wars: Legion - Kashyyyk Wookiee Warriors'),
    ('star-wars-legion-logray-wicket-commander-expansion', 'SWL-083', 'Star Wars: Legion - Logray & Wicket Commander Expansion', decimal.Decimal('29.99'), 'https://store.asmodee.com/cdn/shop/files/SWL110-image0_2000_535x.jpg?v=1690988115', 'https://store.asmodee.com/collections/star-wars-legion/products/star-wars-legion-logray-wicket-commander-expansion', 'Star Wars: Legion - Logray & Wicket Commander Expansion'),
    ('star-wars-legion-snowtrooper', 'SWL-084', 'Star Wars: Legion - Snowtrooper', decimal.Decimal('54.99'), 'https://store.asmodee.com/cdn/shop/files/SWQ43-image0_2000_535x.jpg?v=1778862210', 'https://store.asmodee.com/collections/star-wars-legion/products/star-wars-legion-snowtrooper', 'Star Wars: Legion - Snowtrooper'),
    ('star-wars-legion-rebel-specialists', 'SWL-085', 'Star Wars: Legion - Rebel Specialists', decimal.Decimal('39.99'), 'https://store.asmodee.com/cdn/shop/files/SWQ193-image0_2000_535x.png?v=1775071907', 'https://store.asmodee.com/collections/star-wars-legion/products/star-wars-legion-rebel-specialists-1', 'Star Wars: Legion - Rebel Specialists'),
    ('star-wars-legion-rebel-veterans', 'SWL-086', 'Star Wars: Legion - Rebel Veterans', decimal.Decimal('54.99'), 'https://store.asmodee.com/cdn/shop/files/SWQ75-image0_2000_535x.jpg?v=1778861215', 'https://store.asmodee.com/collections/star-wars-legion/products/star-wars-legion-rebel-veterans', 'Star Wars: Legion - Rebel Veterans'),
    ('star-wars-legion-range-troopers', 'SWL-087', 'Star Wars: Legion - Range Troopers', decimal.Decimal('49.99'), 'https://store.asmodee.com/cdn/shop/files/SWQ89-image0_2000_535x.jpg?v=1768336728', 'https://store.asmodee.com/collections/star-wars-legion/products/star-wars-legion-range-troopers-1', 'Star Wars: Legion - Range Troopers'),
    ('star-wars-legion-poggle-the-lesser-sun-fac', 'SWL-088', 'Star Wars: Legion - Poggle the Lesser & Sun Fac', decimal.Decimal('29.99'), 'https://store.asmodee.com/cdn/shop/files/SWQ101-image0_2000_535x.jpg?v=1767990263', 'https://store.asmodee.com/collections/star-wars-legion/products/star-wars-legion-poggle-the-lesser-sun-fac', 'Star Wars: Legion - Poggle the Lesser & Sun Fac'),
    ('star-wars-legion-droidekas', 'SWL-089', 'Star Wars: Legion - Droidekas', decimal.Decimal('34.99'), 'https://store.asmodee.com/cdn/shop/files/SWQ36-image0_2000_535x.jpg?v=1765463818', 'https://store.asmodee.com/collections/star-wars-legion/products/star-wars-legion-droidekas', 'Star Wars: Legion - Droidekas'),
    ('star-wars-legion-rebel-at-rt', 'SWL-090', 'Star Wars: Legion - Rebel AT-RT', decimal.Decimal('28.99'), 'https://store.asmodee.com/cdn/shop/files/SWQ204-image0_2000_535x.jpg?v=1781118094', 'https://store.asmodee.com/collections/star-wars-legion/products/star-wars-legion-rebel-at-rt', 'Star Wars: Legion - Rebel AT-RT'),
    ('star-wars-legion-infantry-support-platform', 'SWL-091', 'Star Wars: Legion - Infantry Support Platform', decimal.Decimal('52.99'), 'https://store.asmodee.com/cdn/shop/files/SWQ97-image0_2000_535x.png?v=1783347483', 'https://store.asmodee.com/collections/star-wars-legion/products/star-wars-legion-infantry-support-platform-1', 'Star Wars: Legion - Infantry Support Platform'),
    ('star-wars-legion-fifth-brother-seventh-sister', 'SWL-092', 'Star Wars: Legion - Fifth Brother & Seventh Sister', decimal.Decimal('34.99'), 'https://store.asmodee.com/cdn/shop/files/SWQ34-image0_2000_535x.jpg?v=1783967490', 'https://store.asmodee.com/collections/star-wars-legion/products/star-wars-legion-fifth-brother-seventh-sister', 'Star Wars: Legion - Fifth Brother & Seventh Sister'),
    ('star-wars-legion-rebel-alliance-starter-set', 'SWL-093', 'Star Wars: Legion - Rebel Alliance Starter Set', decimal.Decimal('99.99'), 'https://store.asmodee.com/cdn/shop/files/SWQ01-image0_2000_535x.jpg?v=1752242261', 'https://store.asmodee.com/collections/star-wars-legion/products/star-wars-legion-rebel-alliance-starter-set', 'Star Wars: Legion - Rebel Alliance Starter Set'),
    ('star-wars-legion-separatist-alliance-command-card-pack', 'SWL-094', 'Star Wars: Legion - Separatist Alliance Command Card Pack', decimal.Decimal('17.99'), 'https://store.asmodee.com/cdn/shop/files/SWQ158-image0_2000_535x.jpg?v=1751377521', 'https://store.asmodee.com/collections/star-wars-legion/products/star-wars-legion-separatist-alliance-command-card-pack', 'Star Wars: Legion - Separatist Alliance Command Card Pack'),
    ('star-wars-legion-rebellion-card-pack', 'SWL-095', 'Star Wars: Legion - Rebellion Card Pack', decimal.Decimal('26.99'), 'https://store.asmodee.com/cdn/shop/files/SWQ05-image0_2000_535x.jpg?v=1751377989', 'https://store.asmodee.com/collections/star-wars-legion/products/star-wars-legion-rebellion-card-pack', 'Star Wars: Legion - Rebellion Card Pack'),
    ('star-wars-legion-rebel-alliance-command-card-pack', 'SWL-096', 'Star Wars: Legion - Rebel Alliance Command Card Pack', decimal.Decimal('22.99'), 'https://store.asmodee.com/cdn/shop/files/SWQ155-image0_2000_535x.jpg?v=1751381790', 'https://store.asmodee.com/collections/star-wars-legion/products/star-wars-legion-rebel-alliance-command-card-pack', 'Star Wars: Legion - Rebel Alliance Command Card Pack'),
    ('star-wars-legion-clone-trooper-marksmen', 'SWL-097', 'Star Wars: Legion - Clone Trooper Marksmen', decimal.Decimal('54.99'), 'https://store.asmodee.com/cdn/shop/files/SWQ23-image0_2000_535x.png?v=1752240773', 'https://store.asmodee.com/collections/star-wars-legion/products/star-wars-legion-clone-trooper-marksmen', 'Star Wars: Legion - Clone Trooper Marksmen'),
    ('star-wars-legion-republic-clone-commandos', 'SWL-098', 'Star Wars: Legion - Republic Clone Commandos', decimal.Decimal('29.99'), 'https://store.asmodee.com/cdn/shop/files/SWQ26-image0_2000_535x.jpg?v=1765464015', 'https://store.asmodee.com/collections/star-wars-legion/products/star-wars-legion-republic-clone-commandos-1', 'Star Wars: Legion - Republic Clone Commandos'),
    ('star-wars-legion-customizable-rebel-officer-agent', 'SWL-099', 'Star Wars: Legion - Customizable Rebel Officer & Agent', decimal.Decimal('39.99'), 'https://store.asmodee.com/cdn/shop/files/SWQ13-image0_2000_535x.jpg?v=1752241086', 'https://store.asmodee.com/collections/star-wars-legion/products/star-wars-legion-customizable-rebel-officer-agent', 'Star Wars: Legion - Customizable Rebel Officer & Agent'),
    ('star-wars-legion-battle-card-pack', 'SWL-100', 'Star Wars: Legion - Battle Card Pack', decimal.Decimal('29.99'), 'https://store.asmodee.com/cdn/shop/files/SWQ125-image0_2000_535x.jpg?v=1752241192', 'https://store.asmodee.com/collections/star-wars-legion/products/star-wars-legion-battle-card-pack', 'Star Wars: Legion - Battle Card Pack'),
    ('star-wars-legion-clan-wren-mandalorians', 'SWL-101', 'Star Wars: Legion - Clan Wren Mandalorians', decimal.Decimal('46.99'), 'https://store.asmodee.com/cdn/shop/files/SWQ56-image0_2000_535x.png?v=1776692654', 'https://store.asmodee.com/collections/star-wars-legion/products/star-wars-legion-clan-wren-mandalorians', 'Star Wars: Legion - Clan Wren Mandalorians'),
    ('star-wars-legion-battle-deck-card-pack-ii', 'SWL-102', 'Star Wars: Legion - Battle Deck Card Pack II', decimal.Decimal('28.99'), 'https://store.asmodee.com/cdn/shop/files/SWQ151-image0_2000_535x.jpg?v=1768336678', 'https://store.asmodee.com/collections/star-wars-legion/products/star-wars-legion-battle-deck-card-pack-ii', 'Star Wars: Legion - Battle Deck Card Pack II'),
    ('star-wars-legion-aqua-droid-unit-expansion', 'SWL-103', 'Star Wars: Legion - Aqua Droid Unit Expansion', decimal.Decimal('64.99'), 'https://store.asmodee.com/cdn/shop/files/SWQ136-image0_2000_109285e4-0b04-4309-9808-415a66bacde6_535x.jpg?v=1732142606', 'https://store.asmodee.com/collections/star-wars-legion/products/star-wars-legion-aqua-droid-unit-expansion', 'Star Wars: Legion - Aqua Droid Unit Expansion'),
    ('star-wars-legion-captain-solo-commander-skywalker-on-tauntauns', 'SWL-104', 'Star Wars: Legion - Captain Solo & Commander Skywalker on Tauntauns', decimal.Decimal('59.99'), 'https://store.asmodee.com/cdn/shop/files/SWQ41-image0_2000_535x.jpg?v=1769786492', 'https://store.asmodee.com/collections/star-wars-legion/products/star-wars-legion-captain-solo-commander-skywalker-on-tauntuns', 'Star Wars: Legion - Captain Solo & Commander Skywalker on Tauntauns'),
    ('star-wars-legion-lm-432-crab-droid-unit-expansion', 'SWL-105', 'Star Wars: Legion - LM-432 Crab Droid Unit Expansion', decimal.Decimal('54.99'), 'https://store.asmodee.com/cdn/shop/files/SWQ134-image0_2000_a2ac267c-a0b8-40ba-a750-3c8896178600_535x.jpg?v=1732142586', 'https://store.asmodee.com/collections/star-wars-legion/products/star-wars-legion-lm-432-crab-droid-unit-expansion', 'Star Wars: Legion - LM-432 Crab Droid Unit Expansion'),
    ('star-wars-legion-imperial-probe-droids', 'SWL-106', 'Star Wars: Legion - Imperial Probe Droids', decimal.Decimal('34.99'), 'https://store.asmodee.com/cdn/shop/files/SWQ98-image0_2000_535x.jpg?v=1769786371', 'https://store.asmodee.com/collections/star-wars-legion/products/star-wars-legion-imperial-probe-droids', 'Star Wars: Legion - Imperial Probe Droids'),
    ('star-wars-legion-hondo-ohnaka-weequay-pirates', 'SWL-107', 'Star Wars: Legion - Hondo Ohnaka & Weequay Pirates', decimal.Decimal('54.99'), 'https://store.asmodee.com/cdn/shop/files/SWQ45-image0_2000_535x.jpg?v=1770386790', 'https://store.asmodee.com/collections/star-wars-legion/products/star-wars-legion-hondo-ohnaka-weequay-pirates', 'Star Wars: Legion - Hondo Ohnaka & Weequay Pirates'),
    ('star-wars-legion-tsmeu-6-personal-wheel-bike', 'SWL-108', 'Star Wars: Legion - TSMEU-6 Personal Wheel Bike', decimal.Decimal('69.99'), 'https://store.asmodee.com/cdn/shop/files/SWQ32-image0_2000_535x.jpg?v=1768336965', 'https://store.asmodee.com/collections/star-wars-legion/products/star-wars-legion-tsmeu-6-personal-wheel-bike', 'Star Wars: Legion - TSMEU-6 Personal Wheel Bike'),
    ('star-wars-legion-heroes-of-the-clone-army', 'SWL-109', 'Star Wars: Legion - Heroes of the Clone Army', decimal.Decimal('54.99'), 'https://store.asmodee.com/cdn/shop/files/SWQ21-image0_2000_e0535b6a-a61a-4048-b4e5-810c3043bd55_535x.jpg?v=1770050231', 'https://store.asmodee.com/collections/star-wars-legion/products/star-wars-legion-heroes-of-the-clone-army', 'Star Wars: Legion - Heroes of the Clone Army'),
    ('star-wars-legion-b2-super-battle-droids', 'SWL-110', 'Star Wars: Legion - B2 Super Battle Droids', decimal.Decimal('49.99'), 'https://store.asmodee.com/cdn/shop/files/SWQ35-image0_2000_535x.jpg?v=1741274547', 'https://store.asmodee.com/collections/star-wars-legion/products/star-wars-legion-b2-super-battle-droids', 'Star Wars: Legion - B2 Super Battle Droids'),
    ('star-wars-legion-jedi-council', 'SWL-111', 'Star Wars: Legion - Jedi Council', decimal.Decimal('59.99'), 'https://store.asmodee.com/cdn/shop/files/SWQ143-image0_2000_535x.jpg?v=1782134076', 'https://store.asmodee.com/collections/star-wars-legion/products/star-wars-legion-jedi-council', 'Star Wars: Legion - Jedi Council'),
    ('star-wars-legion-wl0-5-speeder-tank', 'SWL-112', 'Star Wars: Legion - WL0-5 Speeder Tank', decimal.Decimal('84.99'), 'https://store.asmodee.com/cdn/shop/files/SWQ59-image0_2000_535x.jpg?v=1770306490', 'https://store.asmodee.com/collections/star-wars-legion/products/star-wars-legion-wl0-5-speeder-tank', 'Star Wars: Legion - WL0-5 Speeder Tank'),
]


class Command(BaseCommand):
    """Populate the Star Wars: Legion product line (idempotent)."""

    help = 'Populates Star Wars: Legion products (SWL-001 to SWL-112).'

    def handle(self, *args, **options):
        category, _ = Category.objects.get_or_create(
            slug='star-wars-legion',
            defaults={'name': 'Star Wars: Legion'},
        )

        asmodee, _ = Retailer.objects.get_or_create(
            slug='asmodee',
            defaults={
                'name': 'Asmodee',
                'website': 'https://store.asmodee.com',
                'country': 'US',
                'is_active': True,
                'is_uk': False,
            },
        )

        products_created = 0
        products_updated = 0
        asmodee_prices_created = 0
        asmodee_prices_updated = 0

        for slug, gw_sku, name, msrp, image_url, product_url, ebay_search_name in PRODUCTS:
            product, created = Product.objects.update_or_create(
                slug=slug,
                defaults={
                    'gw_sku': gw_sku,
                    'name': name,
                    'category': category,
                    'msrp': msrp,
                    'image_url': image_url,
                    'gw_url': product_url,
                    'ebay_search_name': ebay_search_name,
                    'ebay_allowed_title_words': '&' if gw_sku in _AMP_SKUS else '',
                    'batch_tag': 'star-wars-legion',
                    'is_active': True,
                },
            )
            if created:
                products_created += 1
            else:
                products_updated += 1

            _, asmodee_price_created = CurrentPrice.objects.update_or_create(
                product=product,
                retailer=asmodee,
                defaults={
                    'price': msrp,
                    'url': product_url,
                    'in_stock': True,
                    'not_available': False,
                },
            )
            if asmodee_price_created:
                asmodee_prices_created += 1
            else:
                asmodee_prices_updated += 1

        self.stdout.write(self.style.SUCCESS(
            f'Products: {products_created} created, {products_updated} updated.'
        ))
        self.stdout.write(self.style.SUCCESS(
            f'Asmodee prices: {asmodee_prices_created} created, {asmodee_prices_updated} updated.'
        ))
