"""
Management command: seed_amazon_prices

Writes all 340 verified Amazon prices (from the March 2026 Octoparse scrape)
into the production database, keyed by GW SKU.

Data source: matched_asins_final_v3.csv — generated by amazon_match_v3.py and
verified manually.  Only high-confidence matches (recall >= 0.75 or manual
override) are included.

Usage:
    python manage.py seed_amazon_prices
    python manage.py seed_amazon_prices --dry-run
"""

import decimal

from django.core.management.base import BaseCommand, CommandError

from prices.models import CurrentPrice
from products.models import Product, Retailer


# ---------------------------------------------------------------------------
# Verified Amazon matches  (gw_sku -> (price_str, url, in_stock))
# Generated from matched_asins_final_v3.csv — March 2026 Octoparse scrape.
# ---------------------------------------------------------------------------
AMAZON_DATA = {
    '52-20': ('55.25', 'https://www.amazon.com/dp/B083P7M8TF', True),  # Adepta Sororitas Battle Sisters Squad
    '52-25': ('143.89', 'https://www.amazon.com/dp/B0D63B2XCY', False),  # Adepta Sororitas Combat Patrol
    '52-08': ('78.20', 'https://www.amazon.com/dp/B09HH3Z7ZC', True),  # Adepta Sororitas Exorcist
    '52-09': ('71.40', 'https://www.amazon.com/dp/B09HJC9CFQ', True),  # Adepta Sororitas Immolator
    '52-02': ('55.00', 'https://www.amazon.com/dp/B0968RM9H1', True),  # Adepta Sororitas Morvenn Vahl
    '52-15': ('53.66', 'https://www.amazon.com/dp/B083P6HN5P', True),  # Adepta Sororitas Retributor Squad
    '52-12': ('55.25', 'https://www.amazon.com/dp/B085Q29R7P', True),  # Adepta Sororitas Seraphim Squad
    '01-20': ('138.53', 'https://www.amazon.com/dp/B0D14W3KTM', True),  # Adeptus Custodes Combat Patrol
    '01-08': ('55.25', 'https://www.amazon.com/dp/B06XT84VV8', False),  # Adeptus Custodes Custodian Guard
    '01-10': ('53.13', 'https://www.amazon.com/dp/B079CJ6YLL', True),  # Adeptus Custodes Custodian Wardens
    '01-07': ('51.00', 'https://www.amazon.com/dp/B0795XTD6L', True),  # Adeptus Custodes Shield-Captain
    '01-11': ('52.18', 'https://www.amazon.com/dp/B09TM1TGZ3', True),  # Adeptus Custodes Vertus Praetors
    '59-25': ('138.29', 'https://www.amazon.com/dp/B0CNTTMBPD', True),  # Adeptus Mechanicus Combat Patrol
    '59-16': ('71.40', 'https://www.amazon.com/dp/B00WA4QHPQ', True),  # Adeptus Mechanicus Dunecrawler
    '59-20': ('28.99', 'https://www.amazon.com/dp/B095J6PXFF', True),  # Adeptus Mechanicus Electropriests
    '59-18': ('35.70', 'https://www.amazon.com/dp/B0CNTVKXZD', True),  # Adeptus Mechanicus Kataphron Destroyers
    '59-10': ('49.30', 'https://www.amazon.com/dp/B00VE6WTPI', True),  # Adeptus Mechanicus Skitarii Rangers
    '59-06': ('33.15', 'https://www.amazon.com/dp/B09BBKFJD4', True),  # Adeptus Mechanicus Tech-Priest Dominus
    '80-20': ('26.70', 'https://www.amazon.com/dp/B0D8LHNZB2', True),  # Age of Sigmar Dice Set
    '80-15': ('58.65', 'https://www.amazon.com/dp/B09B48MGJW', True),  # Age of Sigmar Warrior Starter Set
    '89-30': ('33.15', 'https://www.amazon.com/dp/B0CHRXGQ8N', True),  # Orruk Warclans Ardboys
    '44-03': ('39.95', 'https://www.amazon.com/dp/B0CVXN5W6P', False),  # Dark Angels Asmodai
    '47-17': ('29.75', 'https://www.amazon.com/dp/B0BSFN5XJX', True),  # Astra Militarum Basilisk
    '47-30': ('45.05', 'https://www.amazon.com/dp/B0BSFPT9VX', False),  # Astra Militarum Cadian Shock Troops
    '47-05': ('55.25', 'https://www.amazon.com/dp/B003CRRMU4', True),  # Astra Militarum Chimera
    '47-25': ('138.00', 'https://www.amazon.com/dp/B0DVT8JDQ6', False),  # Astra Militarum Combat Patrol
    '47-08': ('26.99', 'https://www.amazon.com/dp/B0DHLRML9F', True),  # Astra Militarum Commissar
    '47-14': ('29.75', 'https://www.amazon.com/dp/B0BSFN5XJX', True),  # Astra Militarum Hellhound
    '47-06': ('59.50', 'https://www.amazon.com/dp/B0BSFPSMZ6', False),  # Astra Militarum Leman Russ Battle Tank
    '47-12': ('112.49', 'https://www.amazon.com/dp/B0CP189WMR', True),  # Astra Militarum Sentinel
    'KT-103': ('33.15', 'https://www.amazon.com/dp/B0BVMGVP2X', True),  # Kill Team: Veteran Guardsmen
    '44-04': ('40.80', 'https://www.amazon.com/dp/B0C244GN97', False),  # Dark Angels Azrael
    '44-05': ('39.95', 'https://www.amazon.com/dp/B0CVXP43B1', True),  # Dark Angels Belial
    '55-25': ('33.15', 'https://www.amazon.com/dp/B09LG7FH94', False),  # Black Templars Castellan
    '55-24': ('51.00', 'https://www.amazon.com/dp/B09LGDYQ4T', False),  # Black Templars Chaplain Grimaldus
    '55-30': ('144.50', 'https://www.amazon.com/dp/B0FJ91WF8T', True),  # Black Templars Combat Patrol
    '55-27': ('36.98', 'https://www.amazon.com/dp/B0FJ933BDM', True),  # Black Templars Crusade Ancient
    '55-22': ('36.98', 'https://www.amazon.com/dp/B09LG7MHBR', False),  # Black Templars Emperor's Champion
    '55-26': ('35.70', 'https://www.amazon.com/dp/B0FJ923FZS', True),  # Black Templars Execrator
    '55-28': ('51.00', 'https://www.amazon.com/dp/B09LGJBP32', True),  # Black Templars Marshal
    '55-20': ('55.25', 'https://www.amazon.com/dp/B09LG7HSLY', True),  # Black Templars Primaris Crusader Squad
    '55-23': ('53.47', 'https://www.amazon.com/dp/B09LG1SKWF', True),  # Black Templars Sword Brethren
    '97-08': ('', 'https://www.amazon.com/dp/B0DHXCGWN7', False),  # Blades of Khorne Bloodletters
    '41-03': ('29.92', 'https://www.amazon.com/dp/B005FPTQJQ', True),  # Blood Angels Astorath
    '41-10': ('78.41', 'https://www.amazon.com/dp/B003E6N2L6', True),  # Blood Angels Baal Predator
    '41-25': ('130.00', 'https://www.amazon.com/dp/B0DK3T1QSG', True),  # Blood Angels Combat Patrol
    '41-04': ('40.80', 'https://www.amazon.com/dp/B0C2459XDP', True),  # Blood Angels Commander Dante
    '41-07': ('', 'https://www.amazon.com/dp/B08P7YHHCL', False),  # Blood Angels Death Company Marines
    '41-12': ('', 'https://www.amazon.com/dp/B08P7YHHCL', False),  # Blood Angels Death Company Marines with Jump Packs
    '41-05': ('65.59', 'https://www.amazon.com/dp/B0FPR7Q65F', True),  # Blood Angels Lemartes
    '41-15': ('39.38', 'https://www.amazon.com/dp/B00R119G4C', True),  # Blood Angels Librarian Dreadnought
    '41-02': ('40.80', 'https://www.amazon.com/dp/B08PS67BH6', True),  # Blood Angels Mephiston
    '41-06': ('51.00', 'https://www.amazon.com/dp/B08RCBMNNS', True),  # Blood Angels Sanguinary Guard
    '41-09': ('40.00', 'https://www.amazon.com/dp/B08Y5P6S4N', True),  # Blood Angels Sanguinary Priest
    '41-08': ('39.95', 'https://www.amazon.com/dp/B0DJFGCBFS', True),  # Blood Angels The Sanguinor
    'HA-011': ('58.65', 'https://www.amazon.com/dp/B0GJTJPKMV', True),  # Legiones Astartes Cataphractii Terminators
    'HA-011': ('58.65', 'https://www.amazon.com/dp/B0GJV364PB', True),  # Legiones Astartes Cataphractii Terminators
    '31-67': ('167.61', 'https://www.amazon.com/dp/B0CJ9C8T2T', True),  # Cerastus Knight Acheron
    '31-66': ('180.29', 'https://www.amazon.com/dp/B0CJ99HNZ7', True),  # Cerastus Knight Castigator
    '31-06': ('165.00', 'https://www.amazon.com/dp/B0CD7HZXX4', True),  # Cerastus Knight Lancer
    '91-10': ('32.00', 'https://www.amazon.com/dp/B0BPS3W8XM', True),  # Nighthaunt Chainrasps
    '43-09': ('68.00', 'https://www.amazon.com/dp/B000CESE20', False),  # Chaos Predator
    '71-06': ('144.50', 'https://www.amazon.com/dp/B0D3HZ2SG2', True),  # Chaos Space Marines Combat Patrol
    'AP-001': ('6.95', 'https://www.amazon.com/dp/B07SWZ3C5K', True),  # Citadel Air Paint
    'BP-001': ('7.95', 'https://www.amazon.com/dp/B007RQ4060', True),  # Citadel Base Paint
    'BR-001': ('6.80', 'https://www.amazon.com/dp/B094Y8KNQS', True),  # Citadel Brush: Medium Base
    'BR-002': ('9.99', 'https://www.amazon.com/dp/B094Y3SRW9', True),  # Citadel Brush: Medium Layer
    'BS-001': ('4.55', 'https://www.amazon.com/dp/B0B6Z81PKV', False),  # Citadel Colour Base Paint Set
    'CP-005': ('6.99', 'https://www.amazon.com/dp/B0CMTVKVGK', True),  # Citadel Colour Contrast Paint Bundle x5
    'BS-002': ('11.99', 'https://www.amazon.com/dp/B094Y5X3QJ', True),  # Citadel Colour Shade Set
    'CP-003': ('9.99', 'https://www.amazon.com/dp/B07SRQ88S2', True),  # Citadel Contrast Blood Angels Red
    'CP-001': ('9.99', 'https://www.amazon.com/dp/B07SSQ1LG8', True),  # Citadel Contrast Paint
    'CP-010': ('6.99', 'https://www.amazon.com/dp/B0CMTVKVGK', True),  # Citadel Contrast Paint Bundle x10
    'CP-002': ('29.99', 'https://www.amazon.com/dp/B07T5RYSQZ', False),  # Citadel Contrast Wraithbone
    'DB-001': ('9.99', 'https://www.amazon.com/dp/B0CDBWXLK7', False),  # Citadel Detail Brush Set
    'DP-001': ('3.87', 'https://www.amazon.com/dp/B007RRZHLG', True),  # Citadel Dry Paint
    'HK-001': ('7.95', 'https://www.amazon.com/dp/B0743Y2YF4', True),  # Citadel Hobby Knife
    'LP-001': ('4.25', 'https://www.amazon.com/dp/B007RS6EWQ', True),  # Citadel Layer Paint
    'MR-001': ('22.95', 'https://www.amazon.com/dp/B0BHTRDSJ5', False),  # Citadel Mouldline Remover
    'SP-020': ('26.90', 'https://www.amazon.com/dp/B08JJNFHKR', True),  # Citadel Munitorum Varnish
    'PH-001': ('13.67', 'https://www.amazon.com/dp/B08MC88KWZ', False),  # Citadel Painting Handle
    'PH-002': ('17.95', 'https://www.amazon.com/dp/B09KHBPRVL', False),  # Citadel Painting Handle XL
    'PM-001': ('36.80', 'https://www.amazon.com/dp/B01M14EZHF', True),  # Citadel Painting Mat
    'PG-001': ('49.95', 'https://www.amazon.com/dp/B07DGL2FMC', True),  # Citadel Plastic Glue
    'SP-001': ('14.43', 'https://www.amazon.com/dp/B01H7JECW8', True),  # Citadel Shade (Nuln Oil)
    'SP-002': ('9.99', 'https://www.amazon.com/dp/B0B6CK8PD5', False),  # Citadel Shade Agrax Earthshade
    'SP-003': ('15.12', 'https://www.amazon.com/dp/B018GZD62E', True),  # Citadel Shade Reikland Fleshshade
    'SP-010': ('49.95', 'https://www.amazon.com/dp/B07DGL2FMC', True),  # Citadel Spray: Chaos Black
    'CSP-003': ('9.90', 'https://www.amazon.com/dp/B0C5R5MDQ9', True),  # Citadel Spray Corax White
    'SP-011': ('24.60', 'https://www.amazon.com/dp/B08ZHWMFX3', False),  # Citadel Spray: Wraithbone
    'CSP-004': ('25.00', 'https://www.amazon.com/dp/B00T86KNJK', True),  # Citadel Spray Zandri Dust
    'SP-010': ('49.95', 'https://www.amazon.com/dp/B07DGL2FMC', True),  # Citadel Spray: Chaos Black
    'SP-012': ('32.33', 'https://www.amazon.com/dp/B08ZHKMTRV', True),  # Citadel Spray: Grey Seer
    'SP-011': ('24.60', 'https://www.amazon.com/dp/B08ZHWMFX3', False),  # Citadel Spray: Wraithbone
    'SG-001': ('6.99', 'https://www.amazon.com/dp/B0DJN7PGJC', True),  # Citadel Super Glue
    'TCP-001': ('4.55', 'https://www.amazon.com/dp/B0C69CR9JH', True),  # Citadel Technical Paint
    'TE-001': ('4.55', 'https://www.amazon.com/dp/B0C69CR9JH', True),  # Citadel Technical Paint (Nihilakh Oxide)
    'TP-001': ('11.49', 'https://www.amazon.com/dp/B0BZK486FG', True),  # Citadel Texture Paint (Astrogranite)
    'WP-001': ('7.95', 'https://www.amazon.com/dp/B0F3WDR56W', True),  # Citadel Water Pot
    '86-15': ('44.95', 'https://www.amazon.com/dp/B0CLM7582R', True),  # Cities of Sigmar Freeguild Fusiliers
    '71-06': ('141.93', 'https://www.amazon.com/dp/B0D3HZ2SG2', True),  # Chaos Space Marines Combat Patrol
    'HA-002': ('36.48', 'https://www.amazon.com/dp/B0CRH15FDS', True),  # Contemptor Dreadnought
    '39-04': ('81.60', 'https://www.amazon.com/dp/B08MC6BF6V', True),  # Corvus Blackstar
    '46-06': ('40.80', 'https://www.amazon.com/dp/B077XLMHX7', True),  # Craftworlds Dire Avengers
    '46-02': ('', 'https://www.amazon.com/dp/B09WNGQTBT', False),  # Craftworlds Farseer
    '46-14': ('7.99', 'https://www.amazon.com/dp/B0D3CPJRSC', False),  # Craftworlds Fire Dragons
    '46-29': ('60.00', 'https://www.amazon.com/dp/B0746GG3PF', False),  # Craftworlds Wave Serpent
    '46-26': ('51.00', 'https://www.amazon.com/dp/B074MCDX59', True),  # Craftworlds Wraithguard
    '44-20': ('40.95', 'https://www.amazon.com/dp/B0F53YP53G', True),  # Dark Angels Combat Patrol
    '44-10': ('59.48', 'https://www.amazon.com/dp/B0CVXNHD3P', True),  # Dark Angels Deathwing Knights
    '44-11': ('59.48', 'https://www.amazon.com/dp/B0CVXNHD3P', True),  # Dark Angels Deathwing Terminator Squad
    '44-13': ('51.00', 'https://www.amazon.com/dp/B0CVXNJHNP', True),  # Dark Angels Inner Circle Companions
    '44-16': ('133.00', 'https://www.amazon.com/dp/B0CVXCZ5YL', True),  # Dark Angels Land Speeder Vengeance
    '44-07': ('44.00', 'https://www.amazon.com/dp/B08THKXQ5J', True),  # Dark Angels Lazarus
    '44-06': ('155.99', 'https://www.amazon.com/dp/B0CKPSLCQ4', True),  # Dark Angels Lion El'Jonson
    '44-17': ('84.55', 'https://www.amazon.com/dp/B00AYU3YZY', True),  # Dark Angels Nephilim Jetfighter
    '44-12': ('39.95', 'https://www.amazon.com/dp/B0CVXP43B1', True),  # Dark Angels Ravenwing Black Knights
    '44-09': ('55.25', 'https://www.amazon.com/dp/B08THMGCVL', False),  # Dark Angels Ravenwing Command Squad
    '44-14': ('55.25', 'https://www.amazon.com/dp/B00AYUGFZ0', True),  # Dark Angels Ravenwing Dark Talon
    '44-15': ('55.25', 'https://www.amazon.com/dp/B00AYUGFZ0', True),  # Dark Angels Ravenwing Darkshroud
    '44-08': ('44.00', 'https://www.amazon.com/dp/B08THKXQ5J', True),  # Dark Angels Sammael
    '43-54': ('55.25', 'https://www.amazon.com/dp/B08QW34YBG', True),  # Death Guard Blightlord Terminators
    '43-80': ('143.93', 'https://www.amazon.com/dp/B0F63T4RKC', True),  # Death Guard Combat Patrol
    '43-56': ('55.25', 'https://www.amazon.com/dp/B075TH143V', False),  # Death Guard Deathshroud Bodyguard
    '43-55': ('51.00', 'https://www.amazon.com/dp/B0763KGZ9W', True),  # Death Guard Foetid Bloat-drone
    '43-03': ('138.99', 'https://www.amazon.com/dp/B08RK1HD85', True),  # Death Guard Mortarion Daemon Primarch
    '43-50': ('51.00', 'https://www.amazon.com/dp/B08T54H49C', True),  # Death Guard Plague Marines
    '43-53': ('33.15', 'https://www.amazon.com/dp/B08T7K36TM', False),  # Death Guard Poxwalkers
    '39-03': ('63.13', 'https://www.amazon.com/dp/B0FZD1N1FQ', False),  # Deathwatch Decimus Kill Team
    '39-07': ('63.13', 'https://www.amazon.com/dp/B0FZD1N1FQ', False),  # Deathwatch Fortis Kill Team
    '39-08': ('63.13', 'https://www.amazon.com/dp/B0FZD1N1FQ', False),  # Deathwatch Indomitor Kill Team
    '39-10': ('63.13', 'https://www.amazon.com/dp/B0FZD1N1FQ', False),  # Deathwatch Kill Team
    '39-09': ('63.13', 'https://www.amazon.com/dp/B0FZD1N1FQ', False),  # Deathwatch Spectrus Kill Team
    '39-11': ('63.13', 'https://www.amazon.com/dp/B0FZD1N1FQ', False),  # Deathwatch Talonstrike Kill Team
    '39-05': ('51.00', 'https://www.amazon.com/dp/B09C3NTQSP', True),  # Deathwatch Terminator Squad
    '39-06': ('51.00', 'https://www.amazon.com/dp/B08HPXH2GV', True),  # Deathwatch Veteran Squad
    '39-02': ('33.15', 'https://www.amazon.com/dp/B01KUYPREO', True),  # Deathwatch Watch Master
    'HA-012': ('66.30', 'https://www.amazon.com/dp/B0BD5H9WRZ', True),  # Legiones Astartes Predator
    '97-11': ('40.80', 'https://www.amazon.com/dp/B0BL1KFDM5', True),  # Disciples of Tzeentch Pink Horrors
    '45-02': ('34.00', 'https://www.amazon.com/dp/B0FX34K7JW', True),  # Drukhari Archon
    '45-25': ('134.95', 'https://www.amazon.com/dp/B0FS2J7JDV', False),  # Drukhari Combat Patrol
    '45-07': ('', 'https://www.amazon.com/dp/B096SW4W7G', False),  # Drukhari Kabalite Warriors
    '45-10': ('85.05', 'https://www.amazon.com/dp/B091VXBHQ1', True),  # Drukhari Raider
    '45-06': ('46.13', 'https://www.amazon.com/dp/B09998YRWC', True),  # Drukhari Wyches
    '73-14': ('36.00', 'https://www.amazon.com/dp/B0BK9MJ83N', False),  # Leagues of Votann Einhyr Hearthguard
    '44-02': ('9.99', 'https://www.amazon.com/dp/B01MTF7TGE', False),  # Dark Angels Ezekiel
    '91-35': ('49.48', 'https://www.amazon.com/dp/B01FY2RCD6', True),  # Flesh-Eater Courts Crypt Ghouls
    '91-07': ('49.48', 'https://www.amazon.com/dp/B01FY2RCD6', True),  # Flesh-Eater Courts Crypt Horrors
    '91-32': ('22.70', 'https://www.amazon.com/dp/1788264290', True),  # Flesh-Eater Courts Terrorgheist
    '40-21': ('12.49', 'https://www.amazon.com/dp/B000Y4E7RO', False),  # Warhammer 40,000 Measuring Tape
    '51-44': ('40.80', 'https://www.amazon.com/dp/B07NG31CVQ', True),  # Genestealer Cults Aberrants
    '51-41': ('40.80', 'https://www.amazon.com/dp/B09VBDN5BF', True),  # Genestealer Cults Acolyte Hybrids
    '51-69': ('138.00', 'https://www.amazon.com/dp/B0D63C96WS', True),  # Genestealer Cults Combat Patrol
    '51-43': ('29.75', 'https://www.amazon.com/dp/B09RMTQ1HV', True),  # Genestealer Cults Magus
    '51-40': ('51.00', 'https://www.amazon.com/dp/B09XLWHDHP', True),  # Genestealer Cults Neophyte Hybrids
    '89-06': ('53.86', 'https://www.amazon.com/dp/B07MFCSZCZ', True),  # Gloomspite Gitz Fanatics
    '89-11': ('51.00', 'https://www.amazon.com/dp/B0FGK5WQJL', True),  # Gloomspite Gitz Squig Hoppers
    '57-14': ('68.17', 'https://www.amazon.com/dp/B0FPDMT27L', False),  # Grey Knights Dreadknight
    '57-20': ('142.18', 'https://www.amazon.com/dp/B0FJ915PXJ', True),  # Grey Knights Combat Patrol
    '57-02': ('35.70', 'https://www.amazon.com/dp/B074MB4X97', True),  # Grey Knights Grand Master Voldus
    '57-06': ('45.32', 'https://www.amazon.com/dp/B08QJ4FCSL', True),  # Grey Knights Strike Squad
    '55-21': ('51.00', 'https://www.amazon.com/dp/B09LGJBP32', True),  # Black Templars Helbrecht
    'HA-051': ('39.95', 'https://www.amazon.com/dp/B0CJRZJPM9', True),  # Horus Heresy Chaplain in Terminator Armour
    'HA-021': ('55.25', 'https://www.amazon.com/dp/B0B8ZMZ99L', True),  # Horus Heresy Leviathan Dreadnought
    'HA-040': ('89.08', 'https://www.amazon.com/dp/B0F29NXG8C', True),  # Horus Heresy Spartan Assault Tank
    'HH-001': ('38.25', 'https://www.amazon.com/dp/B0FK5KDDQZ', True),  # Horus Heresy: Age of Darkness
    '54-21': ('165.63', 'https://www.amazon.com/dp/B09ZYS4W54', True),  # Imperial Knight Dominus
    '54-15': ('158.77', 'https://www.amazon.com/dp/B0FPDM6H37', True),  # Imperial Knight Preceptor / Canis Rex
    '54-22': ('158.77', 'https://www.amazon.com/dp/B0FPDM6H37', True),  # Imperial Knight Questoris
    '43-60': ('57.45', 'https://www.amazon.com/dp/B0BTDHL1MH', False),  # World Eaters Berzerkers
    'KT-100': ('129.95', 'https://www.amazon.com/dp/B07HMRPD11', True),  # Kill Team Starter Set
    'KT-104': ('28.90', 'https://www.amazon.com/dp/B0DKNVQX8X', True),  # Kill Team: Chaos Legionaries
    'KT-110': ('55.39', 'https://www.amazon.com/dp/1839064218', False),  # Kill Team: Compendium
    'KT-107': ('28.90', 'https://www.amazon.com/dp/B0DPMW8YD9', True),  # Kill Team: Exaction Squad
    'KT-106': ('28.87', 'https://www.amazon.com/dp/B0DH4TQLF4', True),  # Kill Team: Hunter Clade
    'KT-105': ('28.90', 'https://www.amazon.com/dp/B0DPMW8YD9', True),  # Kill Team: Intercession Squad
    'KT-002': ('45.70', 'https://www.amazon.com/dp/1804570087', True),  # Kill Team: Into the Dark
    'KT-001': ('28.87', 'https://www.amazon.com/dp/B0DH4TQLF4', True),  # Kill Team: Nightmare
    'KT-101': ('36.43', 'https://www.amazon.com/dp/B0DH4XZH2D', True),  # Kill Team: Operatives Datacard Pack 2024
    'KT-108': ('28.87', 'https://www.amazon.com/dp/B0DH4TQLF4', True),  # Kill Team: Salvation
    'KT-100': ('129.95', 'https://www.amazon.com/dp/B07HMRPD11', True),  # Kill Team Starter Set
    'KT-109': ('115.00', 'https://www.amazon.com/dp/B0DPMY5CFW', True),  # Kill Team: Terrain – Killzone Essentials
    'KT-103': ('28.87', 'https://www.amazon.com/dp/B0DH4TQLF4', True),  # Kill Team: Veteran Guardsmen
    '54-20': ('85.00', 'https://www.amazon.com/dp/B0B116QHMG', False),  # Imperial Knight Armigers
    '73-25': ('138.56', 'https://www.amazon.com/dp/B0FL37XSL6', True),  # Leagues of Votann Combat Patrol
    '73-14': ('53.13', 'https://www.amazon.com/dp/B0BK9NJJFH', True),  # Leagues of Votann Einhyr Hearthguard
    '73-10': ('51.00', 'https://www.amazon.com/dp/B0BK9NSQDP', True),  # Leagues of Votann Hearthkyn Warriors
    '73-12': ('58.65', 'https://www.amazon.com/dp/B0BK9NKXYW', False),  # Leagues of Votann Hernkyn Pioneers
    '40-02': ('75.14', 'https://www.amazon.com/dp/B0B8ZP1BDL', False),  # Leviathan (10th Edition Starter Set)
    '87-08': ('53.13', 'https://www.amazon.com/dp/B08HWKPQP8', True),  # Lumineth Realm-lords Alarith Stoneguard
    '87-10': ('55.25', 'https://www.amazon.com/dp/B08HK4QRK7', True),  # Lumineth Realm-lords Vanari Auralan Wardens
    '87-06': ('55.25', 'https://www.amazon.com/dp/B08HK4QRK7', True),  # Lumineth Realm-lords Vanari Auralan Wardens (10)
    'HA-010': ('45.05', 'https://www.amazon.com/dp/B0D6RF8C3V', True),  # Legiones Astartes MKIII Infantry Squad
    'HA-001': ('44.00', 'https://www.amazon.com/dp/B0CWBVGDKG', True),  # MKVI Tactical Squad
    '97-09': ('17.00', 'https://www.amazon.com/dp/B09PF8BHJY', True),  # Maggotkin of Nurgle Plaguebearers
    '83-22': ('55.25', 'https://www.amazon.com/dp/B0G9W5XWLR', True),  # Maggotkin of Nurgle Putrid Blightkings
    '55-12': ('69.29', 'https://www.amazon.com/dp/B0F5GGH8LH', True),  # Marneus Calgar
    'NM-010': ('19.99', 'https://www.amazon.com/dp/B0BNJ3ZHVR', True),  # Necromunda Escher Gang
    'NM-011': ('45.05', 'https://www.amazon.com/dp/B0779Q1K7P', True),  # Necromunda Goliath Gang
    'NM-020': ('61.24', 'https://www.amazon.com/dp/B085W6FJ9H', True),  # Necromunda Underhive Terrain Set
    'NM-012': ('45.05', 'https://www.amazon.com/dp/B07CQCCXMD', True),  # Necromunda Van Saar Gang
    '49-20': ('110.50', 'https://www.amazon.com/dp/B08LB8JYHP', True),  # Necron C’tan Shard of the Void Dragon
    '49-14': ('40.80', 'https://www.amazon.com/dp/B007Y9PVA4', True),  # Necron Canoptek Spyder
    '49-12': ('18.00', 'https://www.amazon.com/dp/B0FNN67JTJ', False),  # Necron Doomsday Ark
    '49-17': ('51.00', 'https://www.amazon.com/dp/B095J8FYZP', True),  # Necron Flayed Ones
    '49-10': ('40.80', 'https://www.amazon.com/dp/B00631UMA8', True),  # Necron Immortals
    '49-11': ('51.00', 'https://www.amazon.com/dp/B00631WTB8', True),  # Necron Lychguard
    '49-08': ('33.15', 'https://www.amazon.com/dp/B08GL6VHZZ', True),  # Necron Monolith
    '49-21': ('33.15', 'https://www.amazon.com/dp/B08VHDDS6N', True),  # Necron Psychomancer
    '49-22': ('43.48', 'https://www.amazon.com/dp/B0CTXT3ZM3', False),  # Necron Royal Warden
    '49-06': ('44.20', 'https://www.amazon.com/dp/B08KXCSZ5S', False),  # Necron Warriors
    '91-14': ('55.77', 'https://www.amazon.com/dp/B07G2S55DT', True),  # Nighthaunt Bladegheist Revenants
    '91-12': ('51.00', 'https://www.amazon.com/dp/B07F1YC259', True),  # Nighthaunt Grimghast Reapers
    '91-06': ('52.50', 'https://www.amazon.com/dp/B07FBJQY74', True),  # Nighthaunt Hexwraiths
    '91-15': ('35.70', 'https://www.amazon.com/dp/B0FLZJWWGP', True),  # Nighthaunt Knight of Shrouds
    '91-02': ('51.00', 'https://www.amazon.com/dp/B07F1WS813', True),  # Nighthaunt Lady Olynder
    '50-22': ('', 'https://www.amazon.com/dp/B001O35G0G', False),  # Ork Battlewagon
    '50-10': ('40.80', 'https://www.amazon.com/dp/B07JYGJ4JL', True),  # Ork Boyz
    '50-16': ('35.70', 'https://www.amazon.com/dp/B09HJBSNNW', True),  # Ork Deff Dread
    '50-20': ('55.25', 'https://www.amazon.com/dp/B09HJX1436', False),  # Ork Flash Gitz
    '50-15': ('55.25', 'https://www.amazon.com/dp/B09FYQG7P3', False),  # Ork Killa Kans
    '50-14': ('35.70', 'https://www.amazon.com/dp/B09HJBSNNW', True),  # Ork Lootas
    '50-12': ('62.48', 'https://www.amazon.com/dp/B00LKE10EK', True),  # Ork Meganobz
    '50-09': ('35.70', 'https://www.amazon.com/dp/B09HJNCZNR', True),  # Ork Nobz
    '50-11': ('51.00', 'https://www.amazon.com/dp/B000CESDXA', True),  # Ork Trukk
    '50-05': ('36.98', 'https://www.amazon.com/dp/B09NSSWG75', True),  # Ork Warboss
    '50-02': ('36.98', 'https://www.amazon.com/dp/B09NSSWG75', True),  # Ork Warboss in Mega Armour
    '89-22': ('51.00', 'https://www.amazon.com/dp/B09GBLLTKZ', True),  # Orruk Warclans Gutrippaz
    '89-20': ('53.13', 'https://www.amazon.com/dp/B01EVDPFBK', True),  # Orruk Warclans Ironjawz Brutes
    '94-10': ('55.25', 'https://www.amazon.com/dp/B07ZTPJ69Q', True),  # Ossiarch Bonereapers Mortek Guard
    '94-12': ('51.00', 'https://www.amazon.com/dp/B07ZTQ263Z', True),  # Ossiarch Bonereapers Necropolis Stalkers
    '49-03': ('35.70', 'https://www.amazon.com/dp/B0CNTVXSM6', True),  # Necron Overlord
    '56-19': ('21.87', 'https://www.amazon.com/dp/B07KW5TRCL', True),  # T'au Pathfinders
    '96-55': ('49.30', 'https://www.amazon.com/dp/B09K4K9T89', True),  # Stormcast Eternals Praetors
    '48-23': ('28.99', 'https://www.amazon.com/dp/B0FL3X8DFY', False),  # Space Marine Predator
    '90-10': ('29.75', 'https://www.amazon.com/dp/B0DFWN8F73', True),  # Skaven Clanrats
    '90-12': ('40.80', 'https://www.amazon.com/dp/B013XDID9K', False),  # Skaven Plague Monks
    '90-17': ('69.70', 'https://www.amazon.com/dp/B0C2YQYPB2', True),  # Skaven Stormfiends
    '59-11': ('49.30', 'https://www.amazon.com/dp/B00VE6WTPI', True),  # Adeptus Mechanicus Skitarii Vanguard
    '83-18': ('54.35', 'https://www.amazon.com/dp/B0BRY3JPBX', True),  # Slaves to Darkness Chaos Warriors (10)
    '83-10': ('54.35', 'https://www.amazon.com/dp/B0BRY3JPBX', True),  # Slaves to Darkness Chaos Warriors (12)
    '83-14': ('93.50', 'https://www.amazon.com/dp/B0CH4B6G13', True),  # Slaves to Darkness Varanguard
    '48-34': ('36.98', 'https://www.amazon.com/dp/B09RG8VTR7', False),  # Space Marine Ancient
    '48-33': ('35.70', 'https://www.amazon.com/dp/B08F2V3TP6', True),  # Space Marine Apothecary
    '48-76': ('55.25', 'https://www.amazon.com/dp/B08P7XNWPG', False),  # Space Marine Assault Intercessors
    '48-38': ('51.00', 'https://www.amazon.com/dp/B08VHDSFSC', False),  # Space Marine Bladeguard Veterans
    '48-32': ('69.95', 'https://www.amazon.com/dp/B0055UCUR6', True),  # Space Marine Chaplain
    '48-37': ('57.45', 'https://www.amazon.com/dp/B0CJS1GK5P', True),  # Space Marine Company Heroes
    '48-15': ('55.25', 'https://www.amazon.com/dp/B0775237DV', False),  # Space Marine Devastator Squad
    '48-98': ('42.99', 'https://www.amazon.com/dp/B0D3FN245T', True),  # Space Marine Eliminators
    '48-39': ('51.00', 'https://www.amazon.com/dp/B08VHF72L8', False),  # Space Marine Eradicators
    '48-28': ('152.50', 'https://www.amazon.com/dp/B0FTZYXRQV', True),  # Space Marine Firestrike Servo-Turrets
    '48-27': ('58.65', 'https://www.amazon.com/dp/B08LB95FQ5', False),  # Space Marine Hammerfall Bunker
    '48-94': ('69.70', 'https://www.amazon.com/dp/B08VHDJMBK', True),  # Space Marine Impulsor
    '48-97': ('51.00', 'https://www.amazon.com/dp/B074RJKKBP', True),  # Space Marine Inceptors
    '48-96': ('24.97', 'https://www.amazon.com/dp/B07J3PG964', False),  # Space Marine Incursors
    '48-45': ('51.00', 'https://www.amazon.com/dp/B000CEM3E0', True),  # Space Marine Infernus Squad
    '48-42': ('45.05', 'https://www.amazon.com/dp/B08KHQ2CMC', True),  # Space Marine Invader ATV
    '48-36': ('36.98', 'https://www.amazon.com/dp/B09RG8VTR7', False),  # Space Marine Judiciar
    '48-21': ('97.75', 'https://www.amazon.com/dp/B001GQQT2A', True),  # Space Marine Land Raider
    '48-22': ('97.75', 'https://www.amazon.com/dp/B001GQQT2A', True),  # Space Marine Land Raider Crusader
    '48-30': ('75.00', 'https://www.amazon.com/dp/B08CTK7K4F', True),  # Space Marine Librarian
    '48-40': ('34.99', 'https://www.amazon.com/dp/B0DYJKS2JP', True),  # Space Marine Outriders
    '48-62': ('39.20', 'https://www.amazon.com/dp/B09RGCPT3L', True),  # Space Marine Primaris Captain
    '48-61': ('33.15', 'https://www.amazon.com/dp/B07WJ7CF9D', True),  # Space Marine Primaris Lieutenant
    '48-93': ('69.70', 'https://www.amazon.com/dp/B08HSRX6Z3', False),  # Space Marine Redemptor Dreadnought
    '48-85': ('69.70', 'https://www.amazon.com/dp/B08VHDJMBK', True),  # Space Marine Repulsor
    '48-95': ('97.75', 'https://www.amazon.com/dp/B08J5NZ8RH', False),  # Space Marine Repulsor Executioner
    '55-02': ('62.48', 'https://www.amazon.com/dp/B0795YC5J2', True),  # Space Marine Roboute Guilliman
    '48-29': ('28.90', 'https://www.amazon.com/dp/B0DH4W3XYK', True),  # Space Marine Scouts
    '48-43': ('51.00', 'https://www.amazon.com/dp/B08HPXH2GV', True),  # Space Marine Sternguard Veteran Squad
    '48-99': ('51.00', 'https://www.amazon.com/dp/B08MVMPLJQ', True),  # Space Marine Suppressors
    '48-07': ('51.00', 'https://www.amazon.com/dp/B077Y4PTR4', True),  # Space Marine Tactical Squad
    '48-06': ('51.00', 'https://www.amazon.com/dp/B000CEM3E0', True),  # Space Marine Terminator Squad
    '48-08': ('51.00', 'https://www.amazon.com/dp/B08HPXH2GV', True),  # Space Marine Vanguard Veteran Squad
    '48-26': ('68.00', 'https://www.amazon.com/dp/B00109WAOY', True),  # Space Marine Vindicator
    '48-25': ('74.00', 'https://www.amazon.com/dp/B000CESE1G', True),  # Space Marine Whirlwind
    '48-92': ('33.15', 'https://www.amazon.com/dp/B0CJS1MKVJ', True),  # Space Marine Aggressors
    '48-41': ('55.25', 'https://www.amazon.com/dp/B08GC37WBR', True),  # Space Marine Infiltrators
    '48-75': ('55.25', 'https://www.amazon.com/dp/B074MCKC99', True),  # Space Marine Intercessors
    '53-20': ('144.50', 'https://www.amazon.com/dp/B0FJ935YFL', True),  # Space Wolves Combat Patrol
    '53-06': ('53.13', 'https://www.amazon.com/dp/B0FF4NG625', True),  # Space Wolves Grey Hunters
    '53-02': ('62.99', 'https://www.amazon.com/dp/B0FGJVB1LQ', True),  # Space Wolves Ragnar Blackmane
    '53-10': ('249.00', 'https://www.amazon.com/dp/B0DTDYR7BM', False),  # Space Wolves Thunderwolf Cavalry
    '53-08': ('58.65', 'https://www.amazon.com/dp/B0FF4X73N1', False),  # Space Wolves Wolf Guard Terminators
    '70-17': ('127.50', 'https://www.amazon.com/dp/B0FHHNS29Y', True),  # Spearhead: Blades of Khorne
    '70-22': ('127.50', 'https://www.amazon.com/dp/B0F9YW8SZ5', True),  # Spearhead: Cities of Sigmar
    '70-12': ('127.50', 'https://www.amazon.com/dp/B0D74W7R2H', True),  # Spearhead: Daughters of Khaine
    '70-839': ('127.50', 'https://www.amazon.com/dp/B0D9YXFMNY', True),  # Spearhead: Disciples of Tzeentch – Tzaangor Warflock
    '70-915': ('127.50', 'https://www.amazon.com/dp/B0FLZLQ7YY', True),  # Spearhead: Flesh-Eater Courts – Charnel Watch
    '70-894': ('51.00', 'https://www.amazon.com/dp/B0DZ32PLNB', True),  # Spearhead: Gloomspite Gitz – Snarlpack Huntaz
    '70-10': ('123.99', 'https://www.amazon.com/dp/B0FLZW4SYX', True),  # Spearhead: Nighthaunt – Cursed Shacklehorde
    '70-892': ('124.39', 'https://www.amazon.com/dp/B0D9YT1G2R', True),  # Spearhead: Orruk Warclans
    '70-893': ('127.50', 'https://www.amazon.com/dp/B0DR8VR7Y7', True),  # Spearhead: Orruk Warclans – Ironjawz Bigmob
    '70-901': ('123.25', 'https://www.amazon.com/dp/B0DFWLXLY6', True),  # Spearhead: Skaven
    '70-04': ('123.25', 'https://www.amazon.com/dp/B0DNFZDMWN', True),  # Spearhead: Slaves to Darkness
    '70-21': ('127.00', 'https://www.amazon.com/dp/B0CX1WC7JJ', False),  # Spearhead: Stormcast Eternals
    '96-12': ('22.72', 'https://www.amazon.com/dp/1785813609', True),  # Stormcast Eternals Judicators
    '96-11': ('85.00', 'https://www.amazon.com/dp/B0CJPDMR9C', True),  # Stormcast Eternals Liberators
    '96-14': ('162.35', 'https://www.amazon.com/dp/B09CV9CD6J', True),  # Stormcast Eternals Lord-Celestant
    '96-55': ('49.30', 'https://www.amazon.com/dp/B09K4K9T89', True),  # Stormcast Eternals Praetors
    '71-55': ('22.72', 'https://www.amazon.com/dp/1785813609', True),  # Stormcast Eternals Vanguard
    '96-50': ('35.00', 'https://www.amazon.com/dp/B0C1P2G6ZS', True),  # Stormcast Eternals Vindictors
    '43-30': ('29.75', 'https://www.amazon.com/dp/B0B2PKL77J', True),  # Thousand Sons Ahriman
    '43-90': ('135.96', 'https://www.amazon.com/dp/B0F8BVJ69F', True),  # Thousand Sons Combat Patrol
    '43-38': ('55.25', 'https://www.amazon.com/dp/B09FYQ38GZ', False),  # Thousand Sons Exalted Sorcerers
    '43-02': ('125.99', 'https://www.amazon.com/dp/B0F4QTPVS4', True),  # Thousand Sons Magnus the Red
    '43-35': ('55.25', 'https://www.amazon.com/dp/B01N1LRFWV', False),  # Thousand Sons Rubric Marines
    '43-36': ('55.25', 'https://www.amazon.com/dp/B09FYSF6Y6', True),  # Thousand Sons Scarab Occult Terminators
    '43-08': ('3.99', 'https://www.amazon.com/dp/B06Y47LR8Q', False),  # Death Guard Typhus
    '51-06': ('40.80', 'https://www.amazon.com/dp/B01GU06PFW', True),  # Tyranid Carnifex
    '51-04': ('55.25', 'https://www.amazon.com/dp/B007G9NQ40', True),  # Tyranid Hive Tyrant
    '51-16': ('22.65', 'https://www.amazon.com/dp/B0D5ZSGDC3', True),  # Tyranid Termagants
    '51-08': ('55.26', 'https://www.amazon.com/dp/B075GWMKMT', True),  # Tyranid Warriors
    '56-13': ('55.25', 'https://www.amazon.com/dp/B000CEQBSY', True),  # T'au Broadside Battlesuit
    '56-25': ('144.50', 'https://www.amazon.com/dp/B0D2J2XJG8', False),  # T'au Combat Patrol
    '56-22': ('29.75', 'https://www.amazon.com/dp/B09RFZGL74', True),  # T'au Ethereal
    '56-06': ('59.95', 'https://www.amazon.com/dp/B07G8N6HJ8', True),  # T'au Fire Warriors
    '56-10': ('68.00', 'https://www.amazon.com/dp/B00C4UUYPK', True),  # T'au Hammerhead Gunship
    '56-16': ('103.70', 'https://www.amazon.com/dp/B09SZMQV11', True),  # T'au Riptide Battlesuit
    '56-14': ('', 'https://www.amazon.com/dp/B075X58BFJ', False),  # T'au Stealth Battlesuits
    '55-16': ('28.99', 'https://www.amazon.com/dp/B0F9DPFMP3', False),  # Ultramarines Honour Guard
    'WC-100': ('33.95', 'https://www.amazon.com/dp/B0C8V4T6S9', True),  # Warcry Starter Set
    'WC-102': ('24.99', 'https://www.amazon.com/dp/B0BN1WTFFB', True),  # Warcry: Hunter and Hunted
    '40-10': ('29.75', 'https://www.amazon.com/dp/B0F9B5CTBK', False),  # Warhammer 40,000 Chapter Approved: Leviathan
    '40-01': ('54.40', 'https://www.amazon.com/dp/1804573744', False),  # Warhammer 40,000 Core Rules
    '40-20': ('28.90', 'https://www.amazon.com/dp/B0FS2CWJQ5', True),  # Warhammer 40,000 Dice Set
    '40-03': ('96.90', 'https://www.amazon.com/dp/B0CBKLS5XD', True),  # Warhammer 40,000 Starter Set
    '39-01': ('34.00', 'https://www.amazon.com/dp/B0DC6PBHSD', True),  # Watch Captain Artemis
    '43-04': ('345.00', 'https://www.amazon.com/dp/B0DZZNHNJ2', True),  # World Eaters Angron
    '43-95': ('134.03', 'https://www.amazon.com/dp/B0F5X8GV4B', True),  # World Eaters Combat Patrol
    '43-62': ('55.25', 'https://www.amazon.com/dp/B0BTDD6Z24', False),  # World Eaters Eightbound
    '43-64': ('58.65', 'https://www.amazon.com/dp/B0BTDDBHPM', False),  # World Eaters Lord on Juggernaut
    '56-15': ('75.65', 'https://www.amazon.com/dp/B09SZPLZ7X', True),  # T'au Crisis Battlesuits
    '83-30': ('58.65', 'https://www.amazon.com/dp/B0C481JXJW', True),  # Blades of Khorne Bloodreavers
    'HA-041': ('68.00', 'https://www.amazon.com/dp/B0F29RQ8JH', True),  # Horus Heresy Sicaran Battle Tank
    'HA-013': ('100.30', 'https://www.amazon.com/dp/B0B8ZNSRXZ', True),  # Legiones Astartes Spartan Assault Tank
    'HA-020': ('29.75', 'https://www.amazon.com/dp/B0CYCSZ4QV', True),  # Solar Auxilia Lasrifle Section
    '48-46': ('62.48', 'https://www.amazon.com/dp/B0CVKJJB63', False),  # Space Marine Ballistus Dreadnought
    '48-44': ('72.25', 'https://www.amazon.com/dp/B0CJS1HRQY', False),  # Space Marine Brutalis Dreadnought
}


class Command(BaseCommand):
    """Seed Amazon prices from the March 2026 Octoparse scrape (340 products)."""

    help = (
        'Write 340 verified Amazon prices into CurrentPrice, keyed by GW SKU. '
        'Idempotent — safe to re-run.'
    )

    def add_arguments(self, parser):
        """Add --dry-run flag."""
        parser.add_argument(
            '--dry-run',
            action='store_true',
            default=False,
            help='Print actions without writing to the database.',
        )

    def handle(self, *args, **options):
        """Execute the price seed."""
        dry_run = options['dry_run']

        try:
            amazon_retailer = Retailer.objects.get(name='Amazon')
        except Retailer.DoesNotExist:
            raise CommandError("Retailer 'Amazon' not found in the database.")

        sku_to_product = {
            p.gw_sku: p
            for p in Product.objects.filter(is_active=True).only('id', 'gw_sku', 'name')
        }
        self.stdout.write(f'Active products loaded: {len(sku_to_product)}')
        self.stdout.write(f'Amazon rows to import:  {len(AMAZON_DATA)}')
        self.stdout.write('')

        applied = 0
        skipped = 0

        for sku, (price_str, url, in_stock) in sorted(AMAZON_DATA.items()):
            product = sku_to_product.get(sku)
            if not product:
                self.stdout.write(
                    self.style.WARNING(f'  [skip] {sku} — not found in active products')
                )
                skipped += 1
                continue

            price = decimal.Decimal(price_str) if price_str else None
            self.stdout.write(
                f"  [{'dry' if dry_run else 'set'}] {sku:8s}  "
                f"{'$'+price_str if price_str else 'no price':>10s}  "
                f"{'IN STOCK' if in_stock else 'out-of-stock':12s}  {product.name}"
            )

            if not dry_run:
                CurrentPrice.objects.update_or_create(
                    product=product,
                    retailer=amazon_retailer,
                    defaults={
                        'price'        : price,
                        'url'          : url,
                        'in_stock'     : in_stock,
                        'not_available': False,
                        'listing_title': '',
                    },
                )
            applied += 1

        self.stdout.write(self.style.SUCCESS(
            f"\n{'[DRY RUN] ' if dry_run else ''}Done!  "
            f"Applied: {applied}  Skipped: {skipped}"
        ))
