# Generated by Django 5.2.11 on 2026-02-18 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('url', models.URLField(help_text='Direct link to buy')),
                ('in_stock', models.BooleanField(default=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_prices', to='products.product')),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_prices', to='products.retailer')),
            ],
            options={
                'ordering': ['price'],
                'unique_together': {('product', 'retailer')},
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('in_stock', models.BooleanField(default=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='products.product')),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='products.retailer')),
            ],
            options={
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['product', 'retailer', 'recorded_at'], name='prices_pric_product_02e719_idx')],
            },
        ),
    ]
