# Generated by Django 5.2.11 on 2026-02-18 17:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0003_remove_product_products_pr_is_acti_cat_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrebuiltArmy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('points_total', models.PositiveIntegerField(default=0)),
                ('units_data', models.JSONField(default=list)),
                ('display_order', models.PositiveSmallIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('faction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prebuilt_armies', to='products.faction')),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SavedArmy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='A memorable name for this army list.', max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('points_total', models.PositiveIntegerField(default=0)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, help_text='Best available retail cost at time of saving.', max_digits=10)),
                ('total_retail', models.DecimalField(decimal_places=2, default=0, help_text='GW MSRP total at time of saving.', max_digits=10)),
                ('total_savings', models.DecimalField(decimal_places=2, default=0, help_text='Amount saved vs GW MSRP.', max_digits=10)),
                ('units_data', models.JSONField(default=list)),
                ('is_public', models.BooleanField(default=False, help_text='Public armies can be viewed by anyone with the share link.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('faction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saved_armies', to='products.faction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_armies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UnitType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Unit name as it appears in the army rules.', max_length=200)),
                ('category', models.CharField(choices=[('hq', 'HQ'), ('troops', 'Troops'), ('elites', 'Elites'), ('fast_attack', 'Fast Attack'), ('heavy_support', 'Heavy Support'), ('dedicated_transport', 'Dedicated Transport'), ('lord_of_war', 'Lord of War')], db_index=True, default='troops', max_length=30)),
                ('points_cost', models.PositiveIntegerField(default=0, help_text='Points cost per model (or per unit if fixed-size).')),
                ('typical_quantity', models.PositiveIntegerField(default=1, help_text='Default number of models in a standard unit.')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Inactive units are hidden from the calculator.')),
                ('description', models.TextField(blank=True, help_text='Brief rules flavour or role description shown in the UI.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('faction', models.ForeignKey(blank=True, help_text='Faction this unit belongs to (e.g. Space Marines, Ultramarines).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unit_types', to='products.faction')),
                ('product', models.ForeignKey(blank=True, help_text='Linked product — used to pull live retail prices.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unit_types', to='products.product')),
            ],
            options={
                'ordering': ['category', 'name'],
                'indexes': [models.Index(fields=['is_active', 'category'], name='calculators_is_acti_d7ac96_idx')],
            },
        ),
    ]
