# Generated by Django 5.2.11 on 2026-02-20 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculators', '0001_initial'),
        ('products', '0003_remove_product_products_pr_is_acti_cat_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unittype',
            options={'ordering': ['faction__name', 'category', 'name']},
        ),
        migrations.AlterField(
            model_name='unittype',
            name='category',
            field=models.CharField(choices=[('epic_hero', 'Epic Hero'), ('character', 'Character'), ('battleline', 'Battleline'), ('infantry', 'Infantry'), ('mounted', 'Mounted'), ('vehicle', 'Vehicle'), ('transport', 'Transport'), ('fortification', 'Fortification')], db_index=True, default='infantry', max_length=30),
        ),
        migrations.AlterField(
            model_name='unittype',
            name='faction',
            field=models.ForeignKey(blank=True, help_text="40K faction this unit belongs to (e.g. Space Marines, Necrons, T'au).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unit_types', to='products.faction'),
        ),
        migrations.AddIndex(
            model_name='unittype',
            index=models.Index(fields=['faction', 'is_active'], name='calculators_faction_371d52_idx'),
        ),
    ]
