# Generated by Django 6.0.2 on 2026-03-20 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculators', '0002_update_unit_category_10th_edition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unittype',
            name='category',
            field=models.CharField(choices=[('epic_hero', 'Epic Hero'), ('character', 'Character'), ('battleline', 'Battleline'), ('infantry', 'Infantry'), ('mounted', 'Mounted'), ('monster', 'Monster'), ('vehicle', 'Vehicle'), ('transport', 'Transport'), ('fortification', 'Fortification')], db_index=True, default='infantry', max_length=30),
        ),
    ]
