# Generated by Django 6.0.2 on 2026-03-29 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculators', '0003_add_monster_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unittype',
            name='category',
            field=models.CharField(choices=[('epic_hero', 'Epic Hero'), ('character', 'Character'), ('battleline', 'Battleline'), ('infantry', 'Infantry'), ('mounted', 'Mounted'), ('monster', 'Monster'), ('vehicle', 'Vehicle'), ('transport', 'Transport'), ('fortification', 'Fortification'), ('combo_box', 'Combo Boxes')], db_index=True, default='infantry', max_length=30),
        ),
    ]
