# Generated by Django 6.0.2 on 2026-04-10 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculators', '0006_combat_patrol_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='unittype',
            name='stat_fnp',
            field=models.CharField(blank=True, default='', help_text='Feel No Pain e.g. 5+', max_length=4),
        ),
        migrations.AddField(
            model_name='unittype',
            name='stat_invuln',
            field=models.CharField(blank=True, default='', help_text='Invulnerable save e.g. 4+', max_length=4),
        ),
        migrations.AddField(
            model_name='unittype',
            name='stat_leadership',
            field=models.CharField(blank=True, default='', help_text='e.g. 7+', max_length=4),
        ),
        migrations.AddField(
            model_name='unittype',
            name='stat_movement',
            field=models.CharField(blank=True, default='', help_text='e.g. 5"', max_length=8),
        ),
        migrations.AddField(
            model_name='unittype',
            name='stat_oc',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Objective Control value', null=True),
        ),
        migrations.AddField(
            model_name='unittype',
            name='stat_save',
            field=models.CharField(blank=True, default='', help_text='e.g. 3+', max_length=4),
        ),
        migrations.AddField(
            model_name='unittype',
            name='stat_toughness',
            field=models.PositiveSmallIntegerField(blank=True, help_text='e.g. 5', null=True),
        ),
        migrations.AddField(
            model_name='unittype',
            name='stat_wounds',
            field=models.PositiveSmallIntegerField(blank=True, help_text='e.g. 4', null=True),
        ),
        migrations.CreateModel(
            name='UnitAbility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ability name e.g. "Cyberstimms"', max_length=200)),
                ('description', models.TextField(help_text='Full rules text for this ability.')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('unit_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abilities', to='calculators.unittype')),
            ],
            options={
                'verbose_name_plural': 'Unit abilities',
                'ordering': ['unit_type', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WeaponProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Weapon name e.g. "Autoch-pattern bolter"', max_length=200)),
                ('weapon_type', models.CharField(choices=[('ranged', 'Ranged'), ('melee', 'Melee')], default='ranged', max_length=8)),
                ('range', models.CharField(blank=True, default='', help_text='e.g. 24" or Melee', max_length=12)),
                ('attacks', models.CharField(help_text='e.g. 2 or D6+1', max_length=10)),
                ('skill', models.CharField(help_text='BS or WS value e.g. 3+', max_length=4)),
                ('strength', models.CharField(help_text='e.g. 5 or 12', max_length=8)),
                ('ap', models.CharField(help_text='e.g. 0 or -3', max_length=4)),
                ('damage', models.CharField(help_text='e.g. 1 or D3 or D6+1', max_length=10)),
                ('keywords', models.CharField(blank=True, default='', help_text='Comma-separated special rules e.g. "Blast, Heavy, Indirect Fire"', max_length=300)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Display order within the unit.')),
                ('unit_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weapon_profiles', to='calculators.unittype')),
            ],
            options={
                'ordering': ['unit_type', 'weapon_type', 'order', 'name'],
            },
        ),
    ]
