# Generated by Django 6.0.2 on 2026-04-12 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculators', '0007_add_statline_weapons_abilities'),
    ]

    operations = [
        migrations.RunPython(
            code=lambda apps, schema_editor: (
                apps.get_model('calculators', 'UnitType')
                .objects.filter(name='Seraptek Heavy Construct with Synaptic Obliterators')
                .exclude(pk=645)
                .delete()
            ),
            reverse_code=migrations.RunPython.noop,
        ),
    ]
