# Generated by Django 6.0.2 on 2026-04-13 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculators', '0009_deduplicate_unit_types'),
        ('products', '0031_populate_ork_gw_skus'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='unittype',
            constraint=models.UniqueConstraint(fields=('name', 'faction'), name='unique_unit_type_name_per_faction'),
        ),
    ]
