# Generated by Django 5.2.11 on 2026-02-20 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Post headline — also used as H1.', max_length=200)),
                ('slug', models.SlugField(blank=True, help_text='URL slug — auto-generated from title if blank.', max_length=220, unique=True)),
                ('excerpt', models.TextField(blank=True, help_text='Short summary shown on the list page and in social cards. Max 300 chars.', max_length=300)),
                ('body', models.TextField(help_text='Full post content. Supports HTML.')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], db_index=True, default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, help_text='Set to a past datetime to make the post live.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(blank=True, help_text='<title> tag override. Leave blank to use the post title. Aim for 60 chars or less.', max_length=70)),
                ('meta_description', models.CharField(blank=True, help_text='Meta description for search engines. Aim for 120-160 chars.', max_length=160)),
                ('featured_image_url', models.URLField(blank=True, help_text='Full URL to a featured header image.')),
                ('featured_image_alt', models.CharField(blank=True, help_text='Alt text for the featured image — required for accessibility and SEO.', max_length=200)),
                ('tags', models.ManyToManyField(blank=True, help_text='Optional content tags (e.g. "Space Marines", "Budget Tips").', related_name='posts', to='blog.tag')),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
                'indexes': [models.Index(fields=['status', 'published_at'], name='blog_post_status_5b2843_idx')],
            },
        ),
    ]
