# Generated by Django 6.0.2 on 2026-05-08 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_author'),
    ]

    operations = [
        migrations.RunPython(
            lambda apps, schema_editor: apps.get_model('blog', 'Post').objects.filter(
                slug='most-expensive-largest-warhammer-40k-models-forge-world-resin'
            ).update(featured_image_url='/static/img/blog/expensive-models/expensive-models-featured.jpg'),
            migrations.RunPython.noop,
        ),
    ]
