# Generated by Django 6.0.2 on 2026-02-27 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentprice',
            name='not_available',
            field=models.BooleanField(default=False, help_text='True if this product is not carried by this retailer.'),
        ),
        migrations.AlterField(
            model_name='currentprice',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='currentprice',
            name='url',
            field=models.URLField(blank=True, default='', help_text='Direct link to buy'),
        ),
    ]
