# Generated by Django 6.0.2 on 2026-03-06 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0002_add_not_available_to_currentprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentprice',
            name='url',
            field=models.URLField(blank=True, default='', help_text='Direct link to buy (eBay URLs with tracking params can exceed 200 chars)', max_length=2000),
        ),
    ]
