# Generated by Django 6.0.2 on 2026-03-08 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0003_url_max_length_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentprice',
            name='listing_title',
            field=models.CharField(blank=True, default='', help_text="The retailer's own name for this product listing (e.g. 'Assault Intercessors (2021 Edition)' on Noble Knight). Populated by import commands; used for display and debugging.", max_length=300),
        ),
    ]
