# Generated by Django 6.0.2 on 2026-03-20 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0004_add_listing_title_to_currentprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentprice',
            name='manual_url_override',
            field=models.BooleanField(default=False, help_text='If True, the URL and stock status were set manually and must not be overwritten by automated scrapers or stock checkers.'),
        ),
    ]
