# Generated by Django 6.0.2 on 2026-05-21 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0012_fix_ghost_ark_amazon_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentprice',
            name='currency',
            field=models.CharField(default='USD', help_text='ISO 4217 currency code. USD for US prices, GBP for UK prices.', max_length=3),
        ),
    ]
