# Generated by Django 6.0.2 on 2026-09-04 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0013_add_currency_to_currentprice'),
        ('products', '0066_category_parent_category_product_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookFormatPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(choices=[('ebook', 'E-Book'), ('audiobook', 'Audio Book'), ('softback', 'Softback'), ('hardback', 'Hardback')], db_index=True, max_length=20)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('currency', models.CharField(default='USD', help_text='ISO 4217 currency code. USD for US prices, GBP for UK prices.', max_length=3)),
                ('url', models.URLField(blank=True, default='', max_length=2000)),
                ('listing_title', models.CharField(blank=True, default='', max_length=300)),
                ('in_stock', models.BooleanField(default=True)),
                ('not_available', models.BooleanField(default=False, help_text='True if this retailer does not carry this format.')),
                ('manual_url_override', models.BooleanField(default=False)),
                ('is_msrp_source', models.BooleanField(default=False, help_text='True if this row is the MSRP reference for this product+format (Games Workshop for Softback/Hardback; Audible/Amazon for Audio Book/E-Book). At most one True row per product+format, enforced at the database level.')),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_format_prices', to='products.product')),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_format_prices', to='products.retailer')),
            ],
            options={
                'ordering': ['format', 'price'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_msrp_source', True)), fields=('product', 'format'), name='unique_msrp_source_per_product_format')],
                'unique_together': {('product', 'retailer', 'format')},
            },
        ),
    ]
