# Generated by Django 6.0.2 on 2026-09-04 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0014_bookformatprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookformatprice',
            name='format',
            field=models.CharField(choices=[('ebook', 'E-Book'), ('audiobook', 'Audio Book'), ('softback', 'Paperback'), ('hardback', 'Hardback')], db_index=True, max_length=20),
        ),
    ]
