# Generated by Django 6.0.2 on 2026-09-04 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0015_alter_bookformatprice_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookformatprice',
            name='isbn',
            field=models.CharField(blank=True, default='', help_text='ISBN-13 (or ISBN-10 for older editions) for this specific format/edition. Used as the precise search key for retailer lookups (e.g. Amazon) instead of ambiguous title matching, and displayed on the product page.', max_length=20),
        ),
    ]
