# Generated by Django 6.0.2 on 2026-09-24 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0016_bookformatprice_isbn'),
        ('products', '0072_newslettersignup_consecutive_send_failures_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookformatprice',
            name='is_msrp_source_uk',
            field=models.BooleanField(default=False, help_text='True if this row is the UK (GBP) MSRP reference for this product+format (Games Workshop UK for Softback/Hardback; Amazon UK/Audible UK for Audio Book/E-Book, once sourced). At most one True row per product+format, enforced at the database level, independently of is_msrp_source.'),
        ),
        migrations.AlterField(
            model_name='bookformatprice',
            name='is_msrp_source',
            field=models.BooleanField(default=False, help_text='True if this row is the US (USD) MSRP reference for this product+format (Games Workshop for Softback/Hardback; Audible/Amazon for Audio Book/E-Book). At most one True row per product+format, enforced at the database level. Separate from is_msrp_source_uk -- the two regions never share or contend over the same flag.'),
        ),
        migrations.AddConstraint(
            model_name='bookformatprice',
            constraint=models.UniqueConstraint(condition=models.Q(('is_msrp_source_uk', True)), fields=('product', 'format'), name='unique_msrp_source_uk_per_product_format'),
        ),
    ]
