# Generated by Django 6.0.2 on 2026-09-11 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0068_product_current_edition_product_isbn'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('hero_tagline', models.CharField(blank=True, default='', help_text='Short hero strapline shown on the series page.', max_length=200)),
                ('hero_image_url', models.URLField(blank=True, default='', help_text='URL to series hero banner image.')),
                ('synopsis', models.TextField(blank=True, default='', help_text='SEO-optimised series description (~150-200 words) shown on the series page.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'series',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=300, unique=True)),
                ('grade', models.CharField(blank=True, choices=[('HG', 'High Grade'), ('MG', 'Master Grade'), ('RG', 'Real Grade'), ('PG', 'Perfect Grade'), ('SD', 'Super Deformed'), ('RE100', 'RE/100'), ('CLASSIC', 'Classic Models'), ('FIGURE', 'Figure')], db_index=True, default='', help_text='Product tier filter, cuts across every Series.', max_length=10)),
                ('scale', models.CharField(blank=True, default='', help_text='Physical build scale (e.g. "1/144", "1/100", "1/60"). Verified manually per kit — not auto-derived from Grade.', max_length=20)),
                ('barcode', models.CharField(blank=True, default='', help_text='Manufacturer JAN barcode, used as a precise eBay/Amazon search anchor -- same role as products.Product.isbn plays for books.', max_length=20)),
                ('handle', models.CharField(blank=True, db_index=True, default='', help_text='Gundam Planet\'s product URL slug (e.g. "hguc-msz-006-zeta-gundam-revive"), used to re-fetch/refresh this exact product.', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('msrp', models.DecimalField(blank=True, decimal_places=2, help_text='Gundam Planet retail price (reference MSRP for discount comparisons).', max_digits=10, null=True)),
                ('batch_tag', models.CharField(blank=True, db_index=True, default='', help_text='Internal label used to group products by the batch they were added in (e.g. "zeta-gundam"). Never shown on the site.', max_length=50)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('secondary_series', models.ManyToManyField(blank=True, help_text='Additional series this product should appear under on the site. The primary series FK above is unchanged. Use this for kits that span more than one series (e.g. a Zeta Gundam-era kit also tagged for Gundam ZZ).', related_name='secondary_products', to='gundam.series')),
                ('series', models.ForeignKey(blank=True, help_text='Primary series this product belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='gundam.series')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CurrentPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('url', models.URLField(blank=True, default='', help_text='Direct link to buy.', max_length=2000)),
                ('listing_title', models.CharField(blank=True, default='', max_length=300)),
                ('in_stock', models.BooleanField(default=True)),
                ('not_available', models.BooleanField(default=False, help_text='True if this product is not carried by this retailer.')),
                ('manual_url_override', models.BooleanField(default=False, help_text='If True, URL and stock status were set manually and must not be overwritten by automated scrapers.')),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gundam_current_prices', to='products.retailer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_prices', to='gundam.product')),
            ],
            options={
                'verbose_name_plural': 'current prices',
                'ordering': ['price'],
                'unique_together': {('product', 'retailer')},
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', 'series'], name='gundam_prod_is_acti_8fdfe6_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', 'grade'], name='gundam_prod_is_acti_c398b5_idx'),
        ),
    ]
