# Generated by Django 6.0.2 on 2026-09-13 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gundam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ebay_negative_keywords',
            field=models.CharField(blank=True, default='', help_text='Space-separated words to exclude from eBay searches (eBay -word syntax). Use when eBay returns a similar but wrong product -- e.g. a different colorway/variant Gundam Planet does not carry, or a seller typo. A pure-digit token is treated as a blocked eBay item ID rather than a title keyword. Same field/convention as products.Product.ebay_negative_keywords -- never hardcode per-product exceptions in the matching command itself.', max_length=400),
        ),
    ]
