# Generated by Django 6.0.2 on 2026-02-20 04:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(choices=[('pet', 'What was the name of your first pet?'), ('city', 'What city were you born in?'), ('school', 'What was the name of your primary school?'), ('mother', "What is your mother's maiden name?"), ('street', 'What street did you grow up on?'), ('game', 'What was the first Warhammer army you collected?')], max_length=20)),
                ('answer_hash', models.CharField(max_length=64)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='security_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Security Profile',
            },
        ),
    ]
