# Generated by Django 6.0.2 on 2026-03-18 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_securityprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlistitem',
            name='alert_percent',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Percentage off MSRP that triggers the alert (1–99).', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='watchlistitem',
            name='alert_type',
            field=models.CharField(choices=[('none', 'No alert'), ('price', 'Specific price'), ('site_low', 'Website low'), ('pct_off', '% off MSRP')], default='none', help_text='Which condition triggers the email alert.', max_length=10),
        ),
        migrations.AddField(
            model_name='watchlistitem',
            name='email_alerts',
            field=models.BooleanField(default=False, help_text='Send an email when the alert condition is met.'),
        ),
        migrations.AddField(
            model_name='watchlistitem',
            name='last_alerted_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The price at which we last sent an alert — prevents repeat spam.', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='watchlistitem',
            name='target_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Alert when best price drops at or below this value.', max_digits=8, null=True),
        ),
    ]
