# Generated by Django 6.0.2 on 2026-09-25 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_watchlistitem_last_alerted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlistitem',
            name='last_alerted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the last alert email sent — drives weekly re-alert logic.', null=True),
        ),
        migrations.AlterField(
            model_name='watchlistitem',
            name='last_alerted_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The price at which we last sent an alert (kept for backwards compat).', max_digits=8, null=True),
        ),
    ]
